### PR TITLE
Ignore UserWarning from prefect

### LINKED ISSUE #1532: UserWarning when running ert3
**Describe the bug**
When running the polynomial example (and most likely other setups), the following warning is presented:

> UserWarning: Tasks were created but not added to the flow: {<Task: Task>}. This can occur when `Task` classes, including `Parameters`, are instantiated inside a `with flow:` block but not added to the flow either explicitly or as the input to another task. For more information, see https://docs.prefect.io/core/advanced_tutorials/task-guide.html#adding-tasks-to-flows.
  next(self.gen)

It appears in CI and was reproduced locally. The setup seems to run fine, but the warning should not appear 🤔 

**To Reproduce**
1. Check out master
2. Run `pip install .[ert-storage]`
3. `cd examples/polynomial`
4. `ert-storage&`
5. `ert3 init`
6. `ert3 run evaluation`

**Expected behavior**
No `UserWarning` in terminal

**Local environment**
 - OS: MacOS
 - ERT/Komodo Release: commit: `e1a70985713d1e109c8b484a209e7d20b75169ca` from `master`
 - Python version: 3.7
 - Remote/HPC execution involved: no

**Additional context**
There is also another stack trace appearing currently (`websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason`), but that is documented in a separate issue: https://github.com/equinor/ert/issues/1307

### PR DESCRIPTION
**Pull request by frode-aarstad**
Resolves #1532

Add a filter for ignoring this specific warning and add a test that fails if there are any warnings

### CODE REVIEW

**Review by jondequinor — CHANGES_REQUESTED** [review]
But why is it produced at all? I think we should explain that somewhere, preferably in the code.

**Comment by frode-aarstad** [comment]
Me and @DanSava reviewed the code and the problem probably arises from recent changes in Prefect. In particular how prefect expects tasks to be associated with flows. 

The correct fix for this issue is rather involved and is better suited for fixing in a larger refactor of the prefect ensemble.

**Comment by jondequinor** [comment]
Okay, then I think we should just keep it around. It's a good reminder to actually do that refactor.

**Comment by markusdregi** [comment]
I agree with @jondequinor! Suggest we close the PR and document the findings in the issue...

**Pull request closed without merging**
