### PR TITLE
Make  socket handling in the evaluator server safer

### LINKED ISSUE #1600: Use of `._closed` with sockets
A undocumented method of `sockets` is used:

https://github.com/equinor/ert/blob/e125f3b0ca7fc8b9507d768f80b1d77341c7b121/ert_shared/ensemble_evaluator/config.py#L153

This code should be replaced with better way of checking if the socket is closed.

### PR DESCRIPTION
**Pull request by verveerpj**
**Issue**
Resolves #1600

**Approach**
The `_close` property of socket objects is private for a good reason: it is hard to determine if a socket is alive or not. You have to use it and then see if there is a problem. If you rely on `_socket` you may only detect cases where the socket was closed properly. Your program may hang if you think its alive and try to use it.

Looking at our code I wonder why we are trying to keep that socket alive all the time. Is it not sufficient to open it when we are using it with the evaluator server? I implemented an alternative that turns the `get_socket` method in a context manager that closes the socket properly and use that with the evaluator server. (Strictly spoken the context manager is not needed, since Python will close a socket when it is garbage collected, but the context manager is much clearer).

I am not 100% sure if this is the way to go, it changes the way the sockets were handled before by opening/closing them as needed. So, feedback is very welcome.

### CODE REVIEW

**Comment by jondequinor** [comment]
https://github.com/equinor/ert/issues/1358 is the appropriate  context for this design. If you find an open port when you instantiate the config, the port could likely be taken when you start the server. The fix was to keep the socket around between those two events. 

There are bazillion ways to solve this, but it seems you're reverting to the behaviour that spawned the issue that shaped the current design. Or am I reading this the wrong way?

**Comment by verveerpj** [comment]
That makes sense, and keeping it around will solve that issue. However, it raises a couple of questions for me:
1. Do we still need to detect if that connection got closed? The current solution with checking `._closed` does not seem to be a good idea.
2. Right now, if the socket is found to be closed, we are making a new one and try to open the same port. Then you are back at the original issue that it may taken. That could be solved by looking for a new port, but the current design seems to be to fix the port for the lifetime of the program. (is that by design?)

I guess my point boils down to: if we are going to keep a socket around for repeatedly starting servers on it, are we going to worry about keeping it alive? Is that an issue at all? I don't have too much experience with sockets, so its an honest question...

**Comment by jondequinor** [comment]
>     1. Do we still need to detect if that connection got closed? The current solution with checking `._closed` does not seem to be a good idea.

Maybe we can ask @DanSava to provide some details, if I recall correctly, he has worked on this.

>     2. Right now, if the socket is found to be closed, we are making a new one and try to open the same port. Then you are back at the original issue that it may taken. That could be solved by looking for a new port, but the current design seems to be to fix the port for the lifetime of the program. (is that by design?)

Could be. We write the port (actually URI) to file and then LSF-scheduled jobs open that file and read the URI. It's hard to re-advertise the port, should it change, using this method.

I don't really have a solution for this, but I like to think that using a message broker would solve this, as the only thing that needs to be coordinated between scheduled jobs and the evaluator is the broker—which could be found using service discovery, or just some well-known name.

**Comment by verveerpj** [comment]
I was just starting to look at message brokers. I was thinking of an example case were ert may run for a long time (days, weeks?) on a cluster or so with a wide array of other applications roaming on that same network. Relying on an open port we discovered in the beginning of the run may be optimistic. So maybe we need a proper message broker.

**Comment by verveerpj** [comment]
I was kind of confused about what this issue should be about. It is not about checking if the connection is alive, it is about checking if the socket is still bound to its host and port. We are currently doing the following:
1. Find an open port and bind a socket to it, which we save to reserve the port.
2. We (possibly repeatedly?) use that socket  to start a websocket server.
3. We used the `._closed` to check if the socket is still bound, presumably it could be closed if someone calls `.close()` on it, or maybe for some other reason. However, the intention is that the socket remains bound to that particular port.

Unless we use another mechanism for messaging, (which is another discussion) I propose to stick with the idea of keeping the socket around.

The pull request now does this:
1. Make the socket a private attribute of the config object, so it cannot be easily closed.
2. Checking if the socket is bound by `._closed` seems suspect, but there seems not official way. But sockets basically use file descriptors, so we can check that using `.fileno()`, which will be -1 if the socket is not valid.

**Comment by verveerpj** [comment]
Jenkins, please test this

**Comment by verveerpj** [comment]
Jenkins, test this please

**Comment by DanSava** [comment]
So the use of `_closed` was there because I could not find a more obvious method to check if the socket is still available when somebody tries to retrieve it. And I liked it because it was obvious what was going on when reading the code, but I agree it is not ok to use a private method, and your solution with `.fileno()` seems to work just fine so I must say nice one!

**Review by DanSava — APPROVED** [review]
Very nice :clap: 

Maybe just add a small comment about self._socket.fileno()

**Pull request merged**
