### PR TITLE
Implement OpenPBS queue option`QSTAT_OPTIONS`

### LINKED ISSUE #7747: OpenPBS driver lacks options the documentation claims it has
The OpenPBS driver that has replaced the Torque driver (unless  `--disable-scheduler` is used on the command line) lacks some settings that the documentation claims are valid:

* `QSUB_CMD` 
* `QSTAT_CMD`
* `QDEL_CMD`
* `QSTAT_OPTIONS`
* `QUEUE_QUERY_TIMEOUT`

The last option is not as relevant to the improved Python driver and should just be provided a deprecation warning for (that it is ignored).

The first four should either be deprecated, or implemented (which will not be difficult, and would make it more in line with LSF driver).

Documentation should be updated accordingly.

### PR DESCRIPTION
**Pull request by jonathan-eq**
**Issue**
Resolves #7747

**Approach**
Implement OpenPBS queue option`QSTAT_OPTIONS`

(Screenshot of new behavior in GUI if applicable)

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by jonathan-eq** [comment]
ERT Docs: ```Options to be supplied to the qstat command. This defaults to -x, which tells the qstat command to include exited processes.```

We also `-E` as default qstat option in scheduler. Should I have this be overridden by the queue_option too? Also, what to do about the docs? The default is still only `-x` in the C implementation.

**Comment by jonathan-eq** [comment]
We use different qstat options on the initial and second qstat querying. Maybe we should deprecate this QUEUE_OPTION instead.

**Comment by xjules** [comment]
> We use different qstat options on the initial and second qstat querying. Maybe we should deprecate this QUEUE_OPTION instead.

I guess there might be a point where QSTAT_OPTIONS might be useful, but let's do it when the time comes.

**Comment by berland** [comment]
I think we can deprecate this, if not we are giving the user the possibility of crashing the driver in arbitrary ways.

**Comment by berland** [comment]
> We also `-E` as default qstat option in scheduler. Should I have this be overridden by the queue_option too? 

The `-E` option "should" have been injected into the legacy driver, but we can choose to not care as it is not used anymore.

**Review by berland — APPROVED** [review]
:+1: 🔪

**Pull request merged**
