### PR TITLE
Update workflows docs

### PR DESCRIPTION
**Pull request by dafeda**
**Approach**
Reformatted such that we have one sentence per line. This makes future diffing easier.

Fixed typos, and in some cases changed wording or entire sentences.

**Question**:

In [Internal Workflows](https://ert.readthedocs.io/en/latest/reference/workflows/internal.html#invoke-a-pre-exported-function) we write "Marking a new function as exported is quite simple, but it requires changes to the core code and a new version must be installed.".

Do we have a document describing how to export a function?

### CODE REVIEW

**Comment by markusdregi** [comment]
> Reformatted such that we have one sentence per line. This makes future diffing easier.

The reason it was different was probably due to an 80 character per line approach to the documentation source. I'm probably one of the 80 advocates, but I can live with longer lines also in documentation :)

**Comment by markusdregi** [comment]
The internal workflows are implemented here: https://github.com/equinor/ert/blob/691316d2fd361cd305917eea83a442893d91bbb5/libres/lib/enkf/enkf_main_jobs.cpp.

It is "easy" in the sense that one can add functions here together with some additional configuration (see this [example](https://github.com/equinor/ert/blob/f4a374d6e40156d02673b4d10475986fdf5d6bd4/share/ert/workflows/jobs/internal/config/ANALYSIS_UPDATE)) and then it becomes available. However, I think it is neither "easy" nor the wanted way to develop new workflows unless you really need to implement it at the C-level.

Perhaps, we could rephrase into something like:

> The list of predefined internal workflow jobs in ERT can be found here: Built in Workflow Jobs. Feel free to reach out if you have suggestions for new predefined workflow jobs.

**Comment by dafeda** [comment]
> The reason it was different was probably due to an 80 character per line approach to the documentation source. I'm probably one of the 80 advocates, but I can live with longer lines also in documentation :)

Word Wrap all day!

I realise now that this should have been two commits - one that just fixed line-lengths and one with actual changes to wording.
Sorry about that.

**Comment by markusdregi** [comment]
No need to apologize! Just thought I could bring some context into the discussion...

**Comment by dafeda** [comment]
> The internal workflows are implemented here: https://github.com/equinor/ert/blob/691316d2fd361cd305917eea83a442893d91bbb5/libres/lib/enkf/enkf_main_jobs.cpp.
> 
> It is "easy" in the sense that one can add functions here together with some additional configuration (see this [example](https://github.com/equinor/ert/blob/f4a374d6e40156d02673b4d10475986fdf5d6bd4/share/ert/workflows/jobs/internal/config/ANALYSIS_UPDATE)) and then it becomes available. However, I think it is neither "easy" nor the wanted way to develop new workflows unless you really need to implement it at the C-level.
> 
> Perhaps, we could rephrase into something like:
> 
> > The list of predefined internal workflow jobs in ERT can be found here: Built in Workflow Jobs. Feel free to reach out if you have suggestions for new predefined workflow jobs.

This looks good to me.
I've added the "Feel free to reach out..." part.

**Comment by markusdregi** [comment]
I've wandered around on the internet in search of wisdom... I just checked the documentation source of numpy, pandas and requests and neither of those packages' documentation source apply the sentence per line strategy you've outlined in this PR. I'm starting to become skeptical...

**Comment by dafeda** [comment]
> I've wandered around on the internet in search of wisdom... I just checked the documentation source of numpy, pandas and requests and neither of those packages' documentation source apply the sentence per line strategy you've outlined in this PR. I'm starting to become skeptical...

My proposal to write one sentence per line is a simplified version of [semantic linefeeds](https://rhodesmill.org/brandon/2012/one-sentence-per-line/), in which one splits sentences at **natural** breaks instead of randomly in order to adhere to some imaginary right-margin.

Admittedly, I sometimes find it hard to find **natural** breaks, and so I've simplified and write one sentence per line.

I am a bit surprised that numpy, requests and pandas don't follow this, which also makes me skeptical!

**Comment by markusdregi** [comment]
I must admit that I like the intentions of semantic linefeeds! But it would be interesting to find a project that actually has used it over time with success...

**Comment by markusdregi** [comment]
> be a beacon of light

That is indeed the ambition 😎

Pitch it for the rest of the team in our Slack channel. If nobody brings new context into the discussion or there is large push back we are good 👍🏻 But, if we are to merge this I think the intention of semantic linefeeds should be documented somewhere...

**Comment by markusdregi** [comment]
I'm thinking that we have a go on this one 🚀  A few things to address:
- [ ] can we split the changes to the text from the restructuring of line breaks?
- [ ] state in CONTRIBUTING.md or elsewhere that we aim for sematinc linefeeds
- [ ]  does there exist any formatting tool that can help us out here or will we need to rely on social agreements for the future?

**Comment by dafeda** [comment]
@eivindjahren , you mentioned having experience working in projects using semantic linefeeds.
Care to share?

**Comment by eivindjahren** [comment]
I have worked with projects that have used the "one paragraph per line" approach which makes line wrap look alright if you have your editor set up a certain way, but breaks for instance github. The one sentence per line has the problem of linewraps showing up in the wrong place for paragraphs with many long sentences.

My personal opinion is that anything but a relaxed approach to line breaking natural language (i.e. allowing manual insertion of `'\n'` in a user specified location) will eventually look bad in some tool. That is not to say that the user will put it in the right place every time, but at least you conserve the option of inserting it when things get too out of hand.

Also, this solves an issue which is not too difficult to live with in the first place: worst case, a diff will be longer than it need to for one paragraph.

**Comment by dafeda** [comment]
Jenkins test this please

**Comment by dafeda** [comment]
Thanks for the input @eivindjahren .

I'm perfectly find not going down the semantic linefeed route.

I've removed the changes related to linefeeds and kept the changes related to actual content.

I suggest we merge this as is.

What do you think @markusdregi ?

**Comment by oyvindeide** [comment]
Looks good, can you rebase on main?\

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Review by oyvindeide — APPROVED** [review]

**Pull request merged**
