### PR TITLE
Fix bug where state map was not updated on loading data

### LINKED ISSUE #3418: Load results manually needs to be repeated every time ERT is launhed
User reported in #ert-users

>I have a case, that ran successfully with "OK"-file generated, but due to wrong refcase, all realizations got "STATE_LOAD_FAILURE". I changed the refcase, and used `Load results manually` from the GUI. It worked great, and the case info showed "STATE_HAS_DATA". I then closed ERT, and reopened - to find that "STATE_LOAD_FAILURE" was "back again". Should it not be "saved" in one way or another?

### PR DESCRIPTION
**Pull request by oyvindeide**
**Issue**
Resolves #3418 

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Review by ManInFez — APPROVED** [review]
:bacon:

**Comment by BjarneHerland** [comment]
For my curiosity: Why sync **after** loading and not before?

**Comment by BjarneHerland** [comment]
>  Does that answer your question?

Perfectly - thanks! 😄 

(So `fs,sync()` is basically "_flush memory to persistent storage_", and `load_from_forward_model()` is "_load something into memory but don't bother to persist it_" ?)

**Comment by oyvindeide** [comment]
> (So `fs,sync()` is basically "_flush memory to persistent storage_", and `load_from_forward_model()` is "_load something into memory but don't bother to persist it_" ?)

More or less yes 😆 But it could be that we used to flush `fs` when `EnKFMain` was deleted, should look into that, so that we persist everything when we exit, might make more sense to do that.

**Pull request merged**
