### PR TITLE
Snapshot model copy DUMMY

### PR DESCRIPTION
**Pull request by sondreso**
Dummy

### CODE REVIEW

**Comment by mortalisk** [comment]
> Dummy

I'm rubber and you're glue!

What is going on with this thing?

**Comment by sondreso** [comment]
It was supposed to be a place were Anna could comment on your changes, but that didn't happen! Will close this!

**Comment by mortalisk** [comment]
So it was merged together with the UI refactor?

**Comment by jondequinor** [comment]
no

**Pull request closed without merging**
