### PR TITLE
Remove ert-storage from dev-requirements.txt

### PR DESCRIPTION
**Pull request by ManInFez**
ert-storage should not belong in dev-requirements. Should be installed with `pip install ert[storage]`

### CODE REVIEW

**Comment by ManInFez** [comment]
Test this please!

**Comment by ManInFez** [comment]
Test this please!

**Comment by ManInFez** [comment]
Test this please!

**Review by jondequinor — CHANGES_REQUESTED** [review]
So a user checks out ERT and runs tests. It fails because storage isn't installed?

Either hide tests requiring storage by default (skip if not storage installed) or make storage not an extra of ERT?

**Comment by ManInFez** [comment]
let us make it a regular requirements then

**Comment by sregales-TNO** [comment]
I would opt for hiding storage tests by default

**Review by jondequinor — APPROVED** [review]

**Pull request merged**
