### PR TITLE
Add mailmap for joakim

### PR DESCRIPTION
**Pull request by eivindjahren**
Guessing my the commit messages and frequency, I am guessing this is @joakim-hove . I was hoping he could confirm that this is the case so we can add it to the mailmap.

## Pre review checklist

- [x] Read through the code changes carefully after finishing work
- [x] Make sure tests pass locally (after every commit!)
- [x] Prepare changes in small commits for more convenient review (optional)
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [x] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by joakim-hove** [comment]
I dont fully understand what this is about - but I can confirm that this message reached me, and that I have previously worked on this codebase.

Joakim.hove@gmail.com

**Comment by eivindjahren** [comment]
> I dont fully understand what this is about - but I can confirm that this message reached me, and that I have previously worked on this codebase.
> 
> [Joakim.hove@gmail.com](mailto:Joakim.hove@gmail.com)

Sorry for the confusion @joakim-hove . It regards a unknown username in older commits "a152128" with email "<a152128@ecb61f28-d21e-0410-a4b6-a828cfe0ca3a>" there are about 200 commits for that user, and I thought it might be you, here is an example, the first commit of the repository:

```
commit a1deb7f7aa88db30fc0f090ff7bd048ae9a53ab6
Author: a152128 <a152128@ecb61f28-d21e-0410-a4b6-a828cfe0ca3a>
Date:   Mon Oct 2 11:18:37 2006 +0000

    Prover aa importere ...
    
    git-svn-id: http://ert.nr.no/repos/ert@1 ecb61f28-d21e-0410-a4b6-a828cfe0ca3a
```

we are adding it to the mailmap so that it is attributed to the correct user.

**Comment by joakim-hove** [comment]
Yes - a152128 was my employee number back in the days.

**Comment by eivindjahren** [comment]
@joakim-hove Ah, cool, thanks for confirming @joakim-hove ! :)

**Review by andreas-el — APPROVED** [review]
Gotta have that mailmap! 🚀

**Pull request merged**
