### PR TITLE
Avoid cancelling the returncode on normal failures

### LINKED ISSUE #7657: MAX_SUBMIT does not work with LSF driver and --enable-scheduler
**Describe the bug**
Flaky forward models are not rerun as instructed in the configuration.

**To reproduce**
Steps to reproduce the behaviour:
* Let poly_eval.py fail with some probability, say 10%
* Set MAX_SUBMIT to a number higher than 1, say 10
* Set queue system to LSF
* Remove MIN_REALIZATIONS (if present)
* Run ES_MDA or ensemble_experiement

NB: It works as expected if queue system is LOCAL.

**Expected behaviour**
All (or almost all) realization should eventually finish successfully, and there should be traces of each resubmission in `logs/`.

**Screenshots**

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: Bleeding at april 12
 - Python version: 3.8
 - Remote/HPC execution involved: yes

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves #7657 

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by berland** [comment]
This PR currently fails tests/unit_tests/scheduler/test_scheduler.py::test_that_job_does_not_retry_when_killed

**Comment by jonathan-eq** [comment]
Will this resolve #7676 ?

**Comment by berland** [comment]
> Will this resolve #7676 ?

Probably yes.

**Comment by berland** [comment]
Superseded by #7681

**Pull request closed without merging**
