### PR TITLE
Refactor unix step

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**

A bit of refactoring for the UnixStep now renamed to StepRunner in this PR

### CODE REVIEW

**Comment by markusdregi** [comment]
Is the intent of this PR to make the `unix_step` the base step (step runner) and implement the function step as a step runner? If so, my immediate thought would be that perhaps the other way would be better? Making the function step the base step and implementing the `unix_step` as a special `function_step` that translates input to files and have a dedicated disk area?

If this comment is completely off, feel free to tell me so in clear text ;)

**Comment by DanSava** [comment]
> Is the intent of this PR to make the `unix_step` the base step (step runner) and implement the function step as a step runner?

No, the intent of this PR is to make the `unix_step` into a generalized `step runner` that will handle the execution of both unix_steps (from scripts) and also function_steps. I realized that having different specialized executors for both of them results in a lot of code duplication and using inheritance was something I wanted to avoid.

**Comment by markusdregi** [comment]
Neat 👏 Sounds like a good idea 🚀

**Comment by DanSava** [comment]
No longer relevant after discussion regarding the function step

**Pull request closed without merging**
