### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by BobinMathew**
I see that the community page doesn't have a COC file.
Having a COC strengthens your community profile. 😀

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by markusdregi** [comment]
Thanks for the suggestion @BobinMathew!

Actually Equinor recently made a drafted template for its open source repositories. I think we should at least compare them to see if there are elements we would like to add.

Putting it here to that you can be part of the discussion:

```
# Code of conduct for open source projects in Equinor
In Equinor, [how we deliver is as important as what we deliver](https://www.equinor.com/en/careers/our-culture.html).

This principle applies to all work done in Equinor maintained projects as well
as for any Equinor contribution to other projects within the open source
community.

## Open, Collaborative, Courageous, Caring

As a values-based organization, our code of conduct for open source projects is
simply a reflection of our values and how we live up to these as teams as well
as individuals.

This set the expectations for how we collaborate in our open source projects.
These expectations applies to all community members and participants in any
Equinor maintained project.

In addition to any definition or interpretation of the open source code of
conduct, the company wide [Equinor code of conduct](https://www.equinor.com/content/dam/statoil/documents/ethics/equinor-code-of-conduct.pdf)
always applies to all employees and hired contractors.

# Handling issues within the communities
At any point, if anyone should raise the concern that a group or member is not
acting in accordance with our values, the behaviour in question should cease, be
discussed and tried to be resolved.

We expect all to have a low threshold for raising issues, or in general discuss
how we live up to our values. Equally, we also encourage all community members
to appreciate when concerns are raised, and make its best effort in solving
them.

As well as responsibility for what is delivered the project maintainers are
also responsible for how we deliver. This includes creating an environment for
proper handling of issues raised within the communities.

# Call out for assistance
For any problem not directly resolvable within the community, we encourage you
to call out for assistance. Getting an outsiders perspective on the topic might
be just what is needed for you to proceed.

Send an e-mail to opensource_at_equinor.com and invite for a discussion.
The email will be handled by a team within the Equinor organization.

# Reporting an issue
If you or your team want to report a direct violation of the code of conduct,
or a failed attempt in solving a conflict within the community. Contact the
same team, opensource_at_equinor.com, with a description of the issue.

Your report will be kept confidential from the team or community in question,
unless you chose to disclose it yourself. We have safe environment for
reporting issues.

Consequences of violations are measured after the severity of the issue, or if
it is a matter of repeatedly failing to take actions with respect to a mandated
decision.

For Equinor maintained projects, only the Equinor open source team has the
mandate for making a corrective action against individuals based on the code of
conduct. These decisions are never made within each project alone. As a last
resort, a potential consequence may be exclusion from participation in that
particular community.

# Ethics helpline
In Equinor, we want you to speak up whenever you see unethical behaviour that
conflicts with our values or threatens our reputation.

To underline this, we continuously encourage and remind our employees and any
external third parties interacting with us to raise concerns or report any
suspected or potential breaches of law or company policies.

For any questions or issues that one suspect falls outside the scope of
behaviour regulated, and handled within the open source code of conduct, or you
wish to place an anonymous, confidential report we encourage to use the
[Equinor Ethics helpline](https://secure.ethicspoint.eu/domain/media/en/gui/102166/index.html).

This helpline is hosted by a third party helpline provider.
```

**Comment by BobinMathew** [comment]
Hi @markusdregi 
The COC that I proposed is just a basic one.
I can see that your custom made COC looks good and seems to cover most of the basic pars of a COC and more notably it reflects your teams/groups values.

**Comment by markusdregi** [comment]
I know, I just wanted to follow up your suggestion since you took the initiative! 👏 

If you update the PR with the suggestion from Equinor instead I’ll merge it. If not, I’ll close it within a few days and do it myself ;)

**Review by markusdregi — APPROVED** [review]
Thank you for the reminder to add a Code of Conduct 👏

**Pull request merged**
