### PR TITLE
Add tests for workspace pollution

### LINKED ISSUE #1387: ert3 taints the workspace
When running ert3 it creates files in the workspace outside of the `.ert`-folder (besides the `data.json` export). This should not be... I therefore suggest that:

- we create a test ensuring that the workspace remains untainted after a run (which will fail) and
- make it pass.

### PR DESCRIPTION
**Pull request by verveerpj**
**Issue**
Resolves #1387 

`ert3` should not pollute the workspace with unexpected files outside of the `.ert` folder, besides `data.json` files. This is currently indeed not the case, so testing code is sufficient for now. Note that currently no logs are created by default. As soon as that happens the tests need to adjusted, or possible the location of the logs.

**Approach**
Adapt existing tests to compare the contents of the workspace before and after running and exporting experiments.

### CODE REVIEW

**Comment by verveerpj** [comment]
Since we are essentially checking the state of the workspace after running a full evaluation, these tests are essentially a kind of integration test. For this reason, I have added them to the existing integration tests in "test_engine.py". 

**Two remarks:**
- It would probably be better to have independent tests for this, not adding to some existing tests. Then it would be clearer in the future that whenever some experiment type is added, you  need a test like this. However, these tests are very slow, so it is more practical to add them to the existing integration tests.
- Currently the tests check that no files are added, except `data.json` files after exporting, while ignoring the `.ert` folder. An exception is the fast sensitivity algorithm, which generates a `fast_sensitiviy.json` file. If this is intended behavior that is now covered by the tests. If not, and that file should not exist, we should probably make an issue to fix that algorithm.

**Review by sondreso — COMMENTED** [review]
Looks good! Would it be more readable if we made it into a function decorator and use it something like this ´@ensure_no_workspace_pollution(allowed_files=["data.json"])´. Or is that maybe not possible since we need the workspace variable? (If that's the case, maybe a context manager could do the same job?)

**Comment by verveerpj** [comment]
> Looks good! Would it be more readable if we made it into a function decorator and use it something like this ´@ensure_no_workspace_pollution(allowed_files=["data.json"])´. Or is that maybe not possible since we need the workspace variable? (If that's the case, maybe a context manager could do the same job?)

A decorator seems difficult without restructuring the tests, but a context manager seems feasible. I will have a look.

**Comment by verveerpj** [comment]
Need help/discussion:

There appears to be an issue that I missed, until I changed the tests now to use a context manager. It seems that the relevant tests create storage files in the workspace. Earlier my tests did not pick them up, apparently because the test fixtures caused them to be created before I check the content of the directory. That is still the case when I run locally, but on GitHub not anymore, apparently the files appear later, after my tests check the directory content.

Real question is: do we tolerated storage files in the workspace? If not, the tests need to be adapted to make sure the storage files are somewhere else.

**Comment by sondreso** [comment]
Did you figure out what happened? 🤔

**Review by sondreso — APPROVED** [review]
Nice!

**Pull request merged**
