### PR TITLE
Run tests in parallel

### PR DESCRIPTION
**Pull request by mortalisk**

### CODE REVIEW

**Comment by eivindjahren** [comment]
This seems to have little effect on runtime for the job, or am I missing something?

**Comment by mortalisk** [comment]
It has some effect even here. But since we have split the running in 3 jobs, we are spending an inordinate amount of time setting up the environment, so the actual running doesn't impact the time as much. Though, if we want, it should be possible to merge the 3 jobs into 1, and they will still run at about the same amount of time, but consuming a 3rd of the github action resources.

**Comment by eivindjahren** [comment]
> It has some effect even here. But since we have split the running in 3 jobs, we are spending an inordinate amount of time setting up the environment, so the actual running doesn't impact the time as much. Though, if we want, it should be possible to merge the 3 jobs into 1, and they will still run at about the same amount of time, but consuming a 3rd of the github action resources.

I guess you can attempt to put it back into 1 part, but it should be noted, as the author of that split, the runtime went from 29 minutes to about 16 so parallelization will have to pick up the slack.

**Comment by mortalisk** [comment]
See https://github.com/equinor/ert/pull/2612 where I combined the jobs into one

**Comment by eivindjahren** [comment]
Seems speedy so should be nice :) Feel free to revert the introduction of the pytest marks as well.

**Comment by markusdregi** [comment]
First, could you document the intent and result towards that intent in the PR description? I presume it is faster CI and then some concrete numbers this PR yields?

Second and more importantly, which steps have we taken to ensure that the Python test suite is stable under parallell test run?

**Comment by oyvindeide** [comment]
Will close this as it looks stale, feel free to reopen if you pick it back up.

**Pull request closed without merging**
