### PR TITLE
Make flakiness test for qstat faster

### LINKED ISSUE #7686: test_that_openpbs_driver_ignores_qstat_flakiness is too slow
```
$ pytest tests/*_tests/scheduler/ -sxv -k flakiness
tests/integration_tests/scheduler/test_openpbs_driver.py::test_that_openpbs_driver_ignores_qstat_flakiness[pbs_iff: cannot connect to host\npbs_iff: all reserved ports in use] PASSED
tests/integration_tests/scheduler/test_openpbs_driver.py::test_that_openpbs_driver_ignores_qstat_flakiness[qstat: Invalid credential] PASSED
tests/unit_tests/scheduler/test_openpbs_driver.py::test_that_openpbs_driver_ignores_qstat_flakiness[pbs_iff: cannot connect to host\npbs_iff: all reserved ports in use] PASSED
tests/unit_tests/scheduler/test_openpbs_driver.py::test_that_openpbs_driver_ignores_qstat_flakiness[qstat: Invalid credential] PASSED

======== 4 passed, 182 deselected in 46.86s =================
```

47 seconds is too much for this test.

### PR DESCRIPTION
**Pull request by berland**
Delete the integration test, the unit test should be sufficient.

Let the polling period be configurable for tests, in line with lsf_driver

This cuts the test time from 46 seconds to 1 second

**Issue**
Resolves #7686 

**Approach**
:brain: and ✂️ 

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by jonathan-eq** [comment]
In the unit test, should we assert that the error message does not appear in the logs? That's what the integration test here tested, but that is not present in the unit test.

**Comment by berland** [comment]
> In the unit test, should we assert that the error message does not appear in the logs? That's what the integration test here tested, but that is not present in the unit test.

I think I managed to fix this. At least I am able to fail the unit test by injecting a logger.debug() in the drivers polling code that logs stderr.

**Comment by jonathan-eq** [comment]
> In the unit test, should we assert that the error message does not appear in the logs? That's what the integration test here tested, but that is not present in the unit test.

I was wrong, it was being checked...

**Review by jonathan-eq — APPROVED** [review]
LGTM!

**Pull request merged**
