### PR TITLE
Fix wrong use of STDERR identifier

### PR DESCRIPTION
**Pull request by sondreso**

### CODE REVIEW

**Comment by markusdregi** [comment]
Is it possible to write a test for this?

**Comment by sondreso** [comment]
Sort of, because this actually fixes two errors in one. So I added a commit which amends a test such that it will fail because of the misspelled `FM_STDERR` and fixes that. The second commit then adds the `ERROR_MSG` identifier and uses that instead in the prefect ensemble, since `STDERR` should point to a file and should be set at startup, not when the job fails.

**Review by markusdregi — APPROVED** [review]
Thanks for the test! Looks good to me 👍

**Comment by mortalisk** [comment]
It seems this is why HM-tut was failing.

**Pull request merged**
