### PR TITLE
Use public MonkeyPatch

### PR DESCRIPTION
**Pull request by oyvindeide**

### CODE REVIEW

**Review by markusdregi — APPROVED** [review]
LGTM 👍🏻

**Comment by oyvindeide** [comment]
Ahh, we have a requirement of pytest<6, will check why.

**Comment by lars-petter-hauge** [comment]
is me.. https://github.com/equinor/ert/commit/c543710c441b097617c45ba39426ae567a7b5494

**Comment by jondequinor** [comment]
@oyvindeide Doesn't this require a quite recent pytest? With 6.0.0 and 5.4.something it fails with ImportError. @oyvindeide could you take a look at this, and pin pytest to the correct version?

**Comment by oyvindeide** [comment]
It does require 6.2, I made a PR to set the lower bound if you would like: https://github.com/equinor/ert/pull/1644

**Pull request merged**
