### PR TITLE
Allow to run ert3 example with ert-storage

### LINKED ISSUE #1738: ERT Storage extraction should use `userdata` instead of `metadata`

### LINKED ISSUE #1744: Make ert3 run with ert-storage
Adjust corresponding changes to ert3 extraction to work with the current ert-storage. This predominantly includes:

1. Rename `metadata` to `userdata`
2. Rename `ensembles` to `ensemble_ids`

### PR DESCRIPTION
**Pull request by xjules**
**Issue**
Resolves #1744 
Resolves #1738 

**Approach**
Make corresponding changes by renaming of endpoints / attributes to work with ert-storage.

### CODE REVIEW

**Comment by markusdregi** [comment]
Is this PR moving `ert3` away from deprecated API usage @xjules? Or should it also include an `ert-storage` version bump?

**Comment by xjules** [comment]
> Is this PR moving `ert3` away from deprecated API usage @xjules? Or should it also include an `ert-storage` version bump?

Yes, this PR replaces deprecated API usage. I will include version bump once tested against the latest `ert-storage`.

**Comment by xjules** [comment]
Test this please!

**Review by ManInFez — APPROVED** [review]
:bacon: ert-storage can now be upgraded to `main` in `bleeding`

**Pull request merged**
