### PR TITLE
Fix crash in plot window

### LINKED ISSUE #720: Incorrect attribute referenced for pandas object in histogram
The `data` `dict` that is looked up contains pandas `DataFrame`'s which use `dtypes` not `dtype` (in some cases they contain `Series` instead, which contains both and as such the code would pass).

```
--------------------------------------------------------------------------------
  File "/work/venvs/ert_36/lib/python3.6/site-packages/ert_gui/tools/plot/plot_widget.py", line 73, in updatePlot
    self._plotter.plot(self._figure, plot_context, case_to_data_map, observations)
  File "/work/venvs/ert_36/lib/python3.6/site-packages/ert_gui/plottery/plots/histogram.py", line 14, in plot
    plotHistogram(figure, plot_context, case_to_data_map, _observation_data)
  File "/work/venvs/ert_36/lib/python3.6/site-packages/ert_gui/plottery/plots/histogram.py", line 47, in plotHistogram
    if data[case].dtype == "object":
  File "/work/venvs/ert_36/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
Exception type: AttributeError
'DataFrame' object has no attribute 'dtype'

```

### PR DESCRIPTION
**Pull request by mortalisk**
**Issue**
Resolves #720

### CODE REVIEW

**Comment by markusdregi** [comment]
@mortalisk: This needs a rebase

**Comment by sondreso** [comment]
Is this not already fixed in this: https://github.com/equinor/ert/pull/751?

**Comment by markusdregi** [comment]
🤷 @xjules ⬆️

**Comment by lars-petter-hauge** [comment]
@sondreso is correct about the PR fixing it at least.

**Comment by lars-petter-hauge** [comment]
I recall that changing from `if not data.columns.is_all_dates` to `if not data.index.is_all_dates` had nothing to do with the problem in the issue, but was a fix we added when we saw it. @mortalisk

**Comment by sondreso** [comment]
@mortalisk Should we close this?

**Comment by mortalisk** [comment]
@sondreso If we are planning to fix the crashing of the plot when merging the new storage, then yes, we should close this. If we want to fix that temporarily while we wait for new storage, then no.

**Comment by sondreso** [comment]
But did we not fix it in this? 
> Is this not already fixed in this: #751?

**Pull request closed without merging**
