### PR TITLE
Add ES-MDA example in example notebooks

### LINKED ISSUE #3708: Include 'es-mda' method in ert/docs/advanced folder examples
Hello.
Examples in the folder  'ert/docs/advanced' show 'ensemble_smoother' and 'iterative_smoother' methods. It will be good to add 'es-mda' to the same for clarity and comparison purpose.

Also, importing 'ies' does not work. Instead '_ies' works.

Thanks.

### PR DESCRIPTION
**Pull request by ajikmr**
**Issue**
Resolves #3708 

**Approach**
Added section for ES-MDA based update in two example notebooks.

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by ajikmr** [comment]
Corresponding python (.py) files can be generated once notebooks are finalized.

**Comment by oyvindeide** [comment]
Hi and thanks for your contribution! This would be really good to have an example of. When it comes to .py vs ipynb we usually go the other way, and produce the .py files first to get an easier to read diff, but if you are working on it feel free to do that at a later stage. We are a bit busy this week, but will get back to you as soon as possible with a proper review.

**Comment by oyvindeide** [comment]
Great thanks, we started looking at it, but as you noticed some of the imports had to be private ( prefaced with `_`) for the example to work. The reason for that is that we are currently restructuring the repository and splitting out the algorithms into a different package: https://github.com/equinor/iterative_ensemble_smoother so they can be stand-alone. We would love to have the example in that package, but the moving is not fully complete yet, which is the reason for the delayed review. If it is ok with you we will hold off a little while longer and pick it up once we have that working properly?

**Comment by ajikmr** [comment]
Thanks for update. Yes, I have noticed the changes too. It makes sense to wait till code changes stabilize.

**Comment by dafeda** [comment]
ERT should now be ready for this, so do try and rebase.
Let us know if you need assistance.

**Comment by ajikmr** [comment]
Thanks for the update. I will look into code and see how to add the changes. I will let you know if I need any assistance with git.

**Comment by ajikmr** [comment]
I have added the changes in 'iterative_ensemble_smoother' repository and made a fresh pull request. 

We can close this request here.

**Comment by dafeda** [comment]
> I have added the changes in 'iterative_ensemble_smoother' repository and made a fresh pull request.
> 
> [equinor/iterative_ensemble_smoother#29](https://github.com/equinor/iterative_ensemble_smoother/pull/29)
> 
> We can close this request here.

Thank you.
Closing this and continuing discussion in the other repo.

**Pull request closed without merging**
