### PR TITLE
Move tool buttons to side pane

### LINKED ISSUE #8702: Ert UI sidebar
Look into how difficult it would be to achieve the following:
- Visual studio code-style sidebar with selectable items
- Embedding run_dialog as a frame in the Ert window
- Re-opening / toggle visibility for different dialogs

### PR DESCRIPTION
**Pull request by andreas-el**
Updated with library_add icon and renew plotter on subsequent clicks.

TGX
Screenshot 2024-10-25 at 12 21 07

macOS
Screenshot 2024-10-25 at 12 12 05

Update after comments
Added visual padding, reversed names in menu, added experiment type in menu description.

Screenshot 2024-10-23 at 08 42 57 1

---

Screenshot 2024-10-15 at 12 14 55

**Issue**
Resolves #8702 

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

##
**TODO**:
- [x] Fix layout / resizing, so pytest snapshots don't `Error: Image dimensions did not match`
- [x] Remove done-button completely, rely on signals
- [x] Fix notifier, so other widgets get updated
- [ ] Look into how to share tools differently
- [x] Have text under icons in sidebar
- [x] Change toolbar order

### CODE REVIEW

**Comment by berland** [comment]
Some observations:
* In the "start simulation" pane, there should maybe be some more padding to the left of the dropdown menu
* In dropdown for "Simulation status" pane, add ensemble type to the timestamp for easier navigation

The first icon in the sidepanel looks like the button to actually start the simulations, but it will not. Maybe we will learn to click the other play button..

**Comment by andreas-el** [comment]
> Some observations:
> 
> * In the "start simulation" pane, there should maybe be some more padding to the left of the dropdown menu
>   image
> * In dropdown for "Simulation status" pane, add ensemble type to the timestamp for easier navigation. Order here is reversed compared to what we find under "Manage experiments".
> 
> The first icon in the sidepanel looks like the button to actually start the simulations, but it will not. Maybe we will learn to click the other play button..

I agree we should replace the start button. Could any of these be an alternative? We are a bit limited by what EDS provides in the context of icons.

library_books
library_books

library_image
library_image

file
file

library_add
library_add

https://storybook.eds.equinor.com/?path=/docs/icons-preview--docs

**Comment by sondreso** [comment]
> I agree we should replace the start button. Could any of these be an alternative? We are a bit limited by what EDS provides in the context of icons.
> 
> library_books library_books
> 
> library_image library_image
> 
> file file
> 
> library_add library_add
> 
> https://storybook.eds.equinor.com/?path=/docs/icons-preview--docs

My vote would be on the library_add button

**Review by eivindjahren — APPROVED** [review]
amazing! :dancers:

**Pull request merged**
