### PR TITLE
Modified the confusing prompt - existing runpath dialog

### LINKED ISSUE #4643: Dialog for existing runpath has confusing prompts
While doing weird stuff I triggered this error dialog:

Screenshot 2023-01-15 at 22 41 23

It is not obvious which button does what.

To reproduce:
1. run ert gui poly.ert
2. run an experiment
3. do step 1-2 again
4. observe dialog

Expected:
A question that the yes/no buttons would answer, or some other reasonable connection between dialog text and buttons.

### PR DESCRIPTION
**Pull request by Jehan-h20220012**
This will solve the issue #4643

**Issue** 
Resolves #4643 

**Approach**
The code related to the GUI simulation was identified and the proposed new line was added to the existing set of intructions in the prompt. 

## Pre review checklist

- [ ] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [x] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by oyvindeide** [comment]
Jenkins: test this please

**Comment by Jehan-h20220012** [comment]
I have updated the main branch from my side.

**Comment by oyvindeide** [comment]
Jenkins: test this please

**Comment by oyvindeide** [comment]
LGTM! Thanks for being patient!

**Review by oyvindeide — APPROVED** [review]

**Pull request merged**
