### PR TITLE
Update error msg

### PR DESCRIPTION
**Pull request by oyvindeide**
Blocked by https://github.com/equinor/libres/pull/1119

### CODE REVIEW

**Review by ManInFez — DISMISSED** [review]
:bacon:

**Comment by oyvindeide** [comment]
test this please

**Comment by oysteoh** [comment]
Loooks fine, will approve after you have squashed your commits 👍

**Review by oysteoh — CHANGES_REQUESTED** [review]
Squash commits 🚀

**Comment by oysteoh** [comment]
Then it is working, but is this correct? The OpenAPI Docs that is. 🤔 
```
OpenAPI Docs: http://ac-cdaf1fdasfdasr.home:51821/docs
 Starting up your webviz application. Please wait...
 Opening the application (http://localhost:5000) in your browser.
 Note that your browser might display security issues.
 See: https://equinor.github.io/webviz-config/#/?id=localhost-hsts
 Press CTRL + C in this terminal window to stop the application.
```

**Comment by oyvindeide** [comment]
> Squash commits 🚀

Do you want just one commit? I can do that, but they doing two different things (I squashed one of them)

**Comment by oyvindeide** [comment]
> Then it is working, but is this correct? The OpenAPI Docs that is. 🤔
> 
> ```
> OpenAPI Docs: http://ac-cdaf1fdasfdasr.home:51821/docs
>  Starting up your webviz application. Please wait...
>  Opening the application (http://localhost:5000) in your browser.
>  Note that your browser might display security issues.
>  See: https://equinor.github.io/webviz-config/#/?id=localhost-hsts
>  Press CTRL + C in this terminal window to stop the application.
> ```

Think this might be for a different PR?

**Comment by oysteoh** [comment]
> Think this might be for a different PR?

Yes - i was reviewing multiple at the same time 😂  Deleted my comment - feel free to delete your response as well

**Comment by oysteoh** [comment]
> > Squash commits 🚀
> 
> Do you want just one commit? I can do that, but they are doing two different things (I squashed one of them)

Two are perfectly fine - was most concerned about the middle one which you have squashed - so then it's all good! 👍

**Review by oysteoh — APPROVED** [review]

**Pull request merged**
