### PR TITLE
Use pattern matching for config schema

### PR DESCRIPTION
**Pull request by eivindjahren**
Use pattern matching now that we no longer support python 3.9

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Make sure unit tests pass locally after every commit (`git rebase -i main
      --exec 'pytest tests/ert/unit_tests -n logical -m "not integration_test"'`)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by berland** [comment]
This change will make it slightly more awkward to backport any future critical bugfix into the 3.8 code.

**Comment by eivindjahren** [comment]
> This change will make it slightly more awkward to backport any future critical bugfix into the 3.8 code.

Yes, we talked a bit about this at the office. We can discuss it after lunch and decide what to do then.

**Comment by eivindjahren** [comment]
We will just wait until backporting python 3.8 fixes is less urgent.

**Review by andreas-el — APPROVED** [review]
💯

**Pull request merged**
