### PR TITLE
Remove the prefect option from ert

### LINKED ISSUE #1324: Remove the possibility to use the prefect evaluator with ert
The functionality of the prefect evaluator is currently exposed both in `ert` and `ert3`. For increased speed and less weight moving forward we should remove the possibility of running the prefect ensemble using `ert` and clean up the code accordingly.

### PR DESCRIPTION
**Pull request by frode-aarstad**
Resolves #1324

### CODE REVIEW

**Comment by markusdregi** [comment]
```
mfane$ grep -r "prefect" ert_shared  --exclude-dir=ert_shared/ensemble_evaluator
ert_shared/models/ensemble_prefect_experiment.py:from ert_shared.ensemble_evaluator.prefect_ensemble.prefect_ensemble import (
ert_shared/models/__init__.py:from .ensemble_prefect_experiment import EnsemblePrefectExperiment
ert_shared/cli/__init__.py:ENSEMBLE_PREFECT_EXPERIMENT_MODE = "ensemble_prefect_experiment"
ert_shared/cli/model_factory.py:from ert_shared.models.ensemble_prefect_experiment import EnsemblePrefectExperiment
ert_shared/cli/model_factory.py:    elif args.mode == "ensemble_prefect_experiment":
ert_shared/cli/model_factory.py:        model, argument = _setup_prefect_ensemble_experiment(args)
ert_shared/cli/model_factory.py:def _setup_prefect_ensemble_experiment(args):
```

Should some of there be removed?

**Comment by frode-aarstad** [comment]
> 
> 
> ```
> mfane$ grep -r "prefect" ert_shared  --exclude-dir=ert_shared/ensemble_evaluator
> ert_shared/models/ensemble_prefect_experiment.py:from ert_shared.ensemble_evaluator.prefect_ensemble.prefect_ensemble import (
> ert_shared/models/__init__.py:from .ensemble_prefect_experiment import EnsemblePrefectExperiment
> ert_shared/cli/__init__.py:ENSEMBLE_PREFECT_EXPERIMENT_MODE = "ensemble_prefect_experiment"
> ert_shared/cli/model_factory.py:from ert_shared.models.ensemble_prefect_experiment import EnsemblePrefectExperiment
> ert_shared/cli/model_factory.py:    elif args.mode == "ensemble_prefect_experiment":
> ert_shared/cli/model_factory.py:        model, argument = _setup_prefect_ensemble_experiment(args)
> ert_shared/cli/model_factory.py:def _setup_prefect_ensemble_experiment(args):
> ```
> 
> Should some of these be removed?

Will have a look

**Comment by frode-aarstad** [comment]
Not sure what to do here. Did the "use the command line" instructions but the status of the PR is the same

**Comment by markusdregi** [comment]
As in, you need help rebasing this @frode-aarstad?

**Review by DanSava — APPROVED** [review]
Looks good to me!

**Pull request merged**
