### PR TITLE
Cache python dependency for GitHub workflows

### PR DESCRIPTION
**Pull request by sregales-TNO**
This is an idea in order to improve GitHub action by caching the python dependencies

### CODE REVIEW

**Comment by markusdregi** [comment]
I'm sorry, but I don't understand what you are trying to improve here :) Care to elaborate?

**Comment by sregales-TNO** [comment]
I remember listening to a podcast about caching virtual environment on your CI pipeline in order to reduce overhead per test run. So I decided in my spare time to go research about it and give it a try. 
- https://github.com/marketplace/actions/restore-or-create-a-python-virtualenv
- https://github.com/python-gino/gino/actions/runs/574815170/workflow
The concept is that the requirement of a project doesn't change much, but the code does, thus rebuilding/reinstalling the environment/dependencies for every run is redundant. Currently, our CI pipeline installs the dependency at each step per run. This is time-consuming and can be cached, allowing faster runs on the following runs until the next requirement change. The resource uses `requirements.txt | pipenv.lock | poetry.lock` in order to see a requirement change
My end goal is to speed up `Run ert tests` and `Run libres tests`

**Comment by markusdregi** [comment]
I see. A quick look gives an estimate of the building in total taking 10% of the total runtime for the test suite. So, it might give some speed up...

But is the plan to cache the Python environment for the different jobs in a run? Or from one run to another? How does this work if the requirements are different for different Python versions?

**Comment by sregales-TNO** [comment]
You can create a matrix of the python environments that you wish to create and each will be cached separately.

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by sondreso** [comment]
Jenkins add to whitelist

**Comment by oyvindeide** [comment]
Will close this due to inactivity, feel free to reopen if you find time to work on it.

**Pull request closed without merging**
