### PR TITLE
Update snake_oil's checked in storage

### LINKED ISSUE #4166: Update checked in storage folder in snake_oil
It's been a while since this was updated.
Some tests will need to be updated.

### PR DESCRIPTION
**Pull request by dafeda**
**Issue**
Resolves #4166

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by eivindjahren** [comment]
This adds data that seems to be about 4 times larger than the current size of the repository. Are we sure we want to do this? What is the runtime cost of generating this on the fly? Also, there are copies of snake-oil other places (semeio for instance). What do we do with those? Would it be better to make snake-oil a standalone integration-test suite (which would also test against other packages)?

**Review by eivindjahren — CHANGES_REQUESTED** [review]
Should probably discuss going directly to not including storage in the repo instead to avoid increasing the download size of `git clone` forever.

**Comment by dafeda** [comment]
> This adds data that seems to be about 4 times larger than the current size of the repository. Are we sure we want to do this? What is the runtime cost of generating this on the fly? Also, there are copies of snake-oil other places (semeio for instance). What do we do with those? Would it be better to make snake-oil a standalone integration-test suite (which would also test against other packages)?

Not a big fan of having storages checked in at all.
I've now run one ensemble experiment and one single realisation run to create two cases; `default` and `default_1`.
Before checking in, I removed all but the folder `realisation-0` from the folder `runpath`.
The currently checked in storage is 8 Mb, while the new one in this PR is 4.2 Mb so that's something.
However, I think we should get rid of it completely.

**Comment by eivindjahren** [comment]
> > This adds data that seems to be about 4 times larger than the current size of the repository. Are we sure we want to do this? What is the runtime cost of generating this on the fly? Also, there are copies of snake-oil other places (semeio for instance). What do we do with those? Would it be better to make snake-oil a standalone integration-test suite (which would also test against other packages)?
> 
> Not a big fan of having storages checked in at all. I've now run one ensemble experiment and one single realisation run to create two cases; `default` and `default_1`. Before checking in, I removed all but the folder `realisation-0` from the folder `runpath`. The currently checked in storage is 8 Mb, while the new one in this PR is 4.2 Mb so that's something. However, I think we should get rid of it completely.

Nice! Just discuss possible actions within sloths and I will not stand in your way :)

**Comment by dafeda** [comment]
This will be solved by making tests not depend on a checked-in storage.

**Pull request closed without merging**
