### PR TITLE
Propagate and show lsf exec_hosts in run_dialog label

### PR DESCRIPTION
**Pull request by andreas-el**
**Issue**
Resolves https://github.com/equinor/ert/issues/999

Screenshot 2024-10-04 at 15 11 09

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure unit tests pass locally after every commit (`git rebase -i main
      --exec 'pytest tests/ert/unit_tests -n logical -m "not integration_test"'`)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by berland** [comment]
Should we do an attempt to obtain a FQDN when printing the hostnames?

**Comment by andreas-el** [comment]
> Should we do an attempt to obtain a FQDN when printing the hostnames?

We could.
Currently bjobs will output like this;
```
(rhel8-bleed-py38-env + bleeding-py38-rhel8) [andrli@st-lintgx0264 komodo]$ bjobs -noheader -o "jobid stat exec_host" 568264
568264 RUN 4*st-rsb17-17-04
```

Do note that `4*st-rsb17-17-04` is not a valid hostname, but I thought this would be useful to see how many slots were assigned on that specific node.

**Comment by berland** [comment]
> Do note that `4*st-rsb17-17-04` is not a valid hostname, but I thought this would be useful to see how many slots were assigned on that specific node.

Right. Maybe just better print the string from bjobs to avoid having to parse something we don't really control.

**Comment by andreas-el** [comment]
There was an additional comment on the original issue;

> While at it, perhaps more realization metadata could be contemplated; RUNPATH, job queue name, LSF log files,

In my opinion the most valuable of these might be the `job_queue_name` ?
The process of adding this will be identical to what was done for `exec_hosts`, even so for the tests, so this should be very low hanging fruit atm.

**Review by berland — APPROVED** [review]
💯

**Pull request merged**
