### PR TITLE
Remove all references to ENKF_SCHED_FILE and ENKF_MERGE_OBSERVATIONS

### LINKED ISSUE #2397: Check if keyword: `ENKF_SCHED_FILE` can be removed
This does not seem to be used, and could probably be removed.

### PR DESCRIPTION
**Pull request by BjarneHerland**
**Issue**
Resolves #2397

**Approach**
Basically a cleanup of unused code

### CODE REVIEW

**Comment by BjarneHerland** [comment]
test ert please

**Comment by oyvindeide** [comment]
If removing `ENKF_SHED_FILE`, must we also remove `ENKF_MERGE_OBSERVATIONS`? The latter might have an impact on the result I believe, and someone might actually use it. Maybe we should deprecate it instead?

**Comment by BjarneHerland** [comment]
Well...  not sure. My understanding from docs
```
The ENKF_MODE keyword is optional.

ENKF_MERGE_OBSERVATIONS

If you use the ENKF_SCHED_FILE option to jump over several dates at a time you can choose whether you want to use all the observations in between, or just the final. If set to TRUE, all observations will be used. If set to FALSE, only the final observation is used. The default value for ENKF_MERGE_OBSERVATIONS is FALSE.
```
is that `ENKF_MERGE_OBSERVATIONS` is used to refine semantics when specifying `ENKF_SCHED_FILE`.

Moreover, I cannot find any place in the logic where this flag actually makes a difference. (Can clearly be mistaken here though...)

@joakim-hove Perhaps you can shed light over the usage of this flag?

**Comment by BjarneHerland** [comment]
> @joakim-hove Perhaps you can shed light over the usage of this flag?

@joakim-hove Did you have any more insight into this?  [Your reply here](https://github.com/equinor/ert/issues/2397#issuecomment-979822420) indicates that it is safe to remove  `ENKF_MERGE_OBSERVATIONS` but please also comment on @oyvindeide s [concerns here](https://github.com/equinor/ert/pull/2453#issuecomment-981406725).

**Comment by joakim-hove** [comment]
Sorry - I did not reply; lost the original notification. The short answer is: *remove it*. The slightly longer answer is that this is remnants of the EnKF algorithm - long gone. If you don't really understand what I mean with EnKF algorithm I am happy to take a video meeting.

**Comment by BjarneHerland** [comment]
> Sorry - I did not reply; lost the original notification. The short answer is: _remove it_. The slightly longer answer is that this is remnants of the EnKF algorithm - long gone. If you don't really understand what I mean with EnKF algorithm I am happy to take a video meeting.

Thanks for clarification. 😄   Will push this one further then.

**Review by sregales-TNO — APPROVED** [review]
LGTM

**Pull request merged**
