### PR TITLE
Updated the logger file and changed websockets setting for issue #5158

### PR DESCRIPTION
**Pull request by Jehan-h20220012**
**Issue**
Resolves #my_issue
#5158 

**Approach**
_Short description of the approach_

## Pre review checklist

- [x ] Added appropriate release note label
- [x ] PR title captures the intent of the changes, and is fitting for release notes.
- [x ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by Jehan-h20220012** [comment]
@berland do let me know if this requires any more changes for issue #5158

**Comment by berland** [comment]
Thanks for your contribution! I see that this also removes the websocket logging from the  `ee-log*txt `files, in that log file I suppose we want to have this information for debugging future errors. Can you see if it is possible to only remove it from the` ert-log*txt` and keep it in `ee-log*txt`?

**Comment by Jehan-h20220012** [comment]
> Thanks for your contribution! I see that this also removes the websocket logging from the `ee-log*txt `files, in that log file I suppose we want to have this information for debugging future errors. Can you see if it is possible to only remove it from the` ert-log*txt` and keep it in `ee-log*txt`?

Thanks @berland... that's the reason why I earlier commented on the issue that we might not want changes in the log files as we need them for DEBUG. I will have to look upon how to individually remove it for ert-log*txt. Happy to have some insights from you regarding the same.

**Comment by berland** [comment]
Hi, can you describe the effect of changing this "propagation"?

**Comment by oyvindeide** [comment]
Will close this due to inactivity, thanks for you contribution, if you pick it up again, feel free to reopen the PR

**Pull request closed without merging**
