### PR TITLE
Remove unused summary2json script from spe1

### PR DESCRIPTION
**Pull request by xjules**
**Issue**
After the new EclSum transformation 19068cc the ert3 spe1 example does not require summary2json script anymore. Therefore this removes the file.

- [x] Added appropriate labels

### CODE REVIEW

**Comment by berland** [comment]
The readme also should be modified, as it talks about summary2json and ecl2df.

**Comment by berland** [comment]
The file `.github/workflows/run_examples_spe1.yml` installs `ecl2df` which is no longer needed.

**Review by sondreso — APPROVED** [review]
LGTM

**Comment by xjules** [comment]
Test this please!

**Comment by markusdregi** [comment]
Please evaluate whether to hold off merging this until this one is resolved: https://github.com/equinor/ert/issues/2684. This PR does simplify the setup, but additional changes to a broken setup might complicate fixing it also ⚖️

**Comment by berland** [comment]
Swallowed by #2684

**Pull request closed without merging**
