### PR TITLE
Remove inactive analysis module options

### LINKED ISSUE #3105: AttributeError when trying to change IES_ENKF settings in GUI
**Describe the bug**

Getting AttributeError: 'AnalysisModule' object has no attribute 'getStr' when trying to change IES_ENKF settings in GUI.

**To Reproduce**
```console
ert gui test-data/local/poly_example/poly.ert
```
- Pick "Iterated Ensemble Smoother" in "Simulation mode".
- Click on Settings button next to "IES_ENKF" under "Analysis Module"
**Expected behavior**

**Enviromment**
 - OS: MacOS, Ubuntu 20
 - main branch
 - Python 3.8
 - Remote/HPC execution involved: [no]

### PR DESCRIPTION
**Pull request by oyvindeide**
**Issue**
GUI crashes when analysis options is pressed. Closes #3105

**Approach**
_Short description of the approach_

## Pre review checklist

- [x] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Review by dafeda — APPROVED** [review]
Very nice 👍

**Comment by oyvindeide** [comment]
test this please

**Comment by oyvindeide** [comment]
test this please

**Comment by oyvindeide** [comment]
test ert please

**Pull request merged**
