### PR TITLE
Stop logging to stdout

### LINKED ISSUE #2096: Stop logging to stdout
As we are adding logging statements for `WARNING` and above these will show up on `stdout`, we might want to remove this handler so we dont pollute `stdout` with information that is useful to log, but not that useful to the user.

https://github.com/equinor/ert/blob/f79b4a294288429956cd932d8b39e06cf4d8fd9d/ert_logging/logger.conf#L10

### PR DESCRIPTION
**Pull request by dafeda**
**Issue**
Resolves #2096

### CODE REVIEW

**Comment by sregales-TNO** [comment]
Could you at least at the reasoning for the removal in the title description. (It's for future retrieval)

**Comment by sregales-TNO** [comment]
Test this please

**Review by sregales-TNO — APPROVED** [review]

**Comment by jondequinor** [comment]
@dafeda could you back port this to `version-2.28`?

**Comment by dafeda** [comment]
> @dafeda could you back port this to `version-2.28`?

Sure, here's the PR:

https://github.com/equinor/ert/pull/2116

**Pull request merged**
