### PR TITLE
Fix ruff preview option PLR6301

### LINKED ISSUE #7528: Fix ruff preview option PLR6301
**Describe the bug**
Related to #7377 
``````
(py3.10-venv) x86_64 ➜  ert git:(improve-ruff-coverage) ✗ ruff rule PLR6301                                            
# no-self-use (PLR6301)

Derived from the **Pylint** linter.

This rule is in preview and is not stable. The `--preview` flag is required for use.

## What it does
Checks for the presence of unused `self` parameter in methods definitions.

## Why is this bad?
Unused `self` parameters are usually a sign of a method that could be
replaced by a function, class method, or static method.

## Example
```python
class Person:
    def greeting(self):
        print("Greetings friend!")
```

Use instead:
```python
def greeting():
    print("Greetings friend!")
```
``````

### PR DESCRIPTION
**Pull request by jonathan-eq**
**Issue**
Resolves #7528 

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by berland** [comment]
I think you can skip the `staticmethod` decorator on maybe all these functions, check f.ex. https://stackoverflow.com/questions/55080991/does-the-staticmethod-decorator-do-anything

**Comment by jonathan-eq** [comment]
> I think you can skip the `staticmethod` decorator on maybe all these functions, check f.ex. https://stackoverflow.com/questions/55080991/does-the-staticmethod-decorator-do-anything

I chose to use `@staticmethod` to avoid having to rewrite all method calls from `class_instance.method()` to `Class.method()` as the first one would pass `self` as first argument. `@staticmethod` ignores `self` as first argument.

**Comment by berland** [comment]
ah, right, so the diff would actually become larger if staticmethod was not used. 👍🏻

**Review by berland — APPROVED** [review]
LGTM 🧹

**Pull request merged**
