### PR TITLE
Communicate analysis completion

### PR DESCRIPTION
**Pull request by jondequinor**
**Issue**
Resolves https://github.com/equinor/ert/issues/338

**Approach**
Use existing `msg` (`QMessageBox`) to communicate success.
Test using `mock`.

### CODE REVIEW

**Comment by markusdregi** [comment]
Seems like the tests are failing due to the `mock` module not being present. You should probably add it to `tests_require` in `setup.py`...

**Comment by jondequinor** [comment]
It also seems the qt mocking isn't 100%.

**Comment by jondequinor** [comment]
Mocking is a bit awkward, see https://github.com/equinor/ert/issues/422.

**Comment by andreabrambilla** [comment]
I have some stuff to mock aways dialogs in Everest, have a look at `test_ui.py`, maybe you can fnd something useful in there

**Comment by jondequinor** [comment]
Thanks, Andrea. The current approach is sufficiently straight forward, I think, but dependency injection and some inversion of control would address the real problem.

**Pull request merged**
