### PR TITLE
Enable HTML autoescape feature in `template_render.py`

### PR DESCRIPTION
**Pull request by fazledyn-or**
The 'jinja2.Environment' method sets `autoescape` to `False` by default which disables HTML autoescape mechanism globally .This can lead to XSS vulnerabilities. A more pragmatic approach is to escape by default and to manually disable escaping when needed. In this change, I've enabled the autoescaping mechanism.

**Issue**
None. A security hardening step.

**Approach**
Add `autoescape=True` to `_load_template` method.

(Screenshot of new behavior in GUI if applicable)

## Pre review checklist

- [ ] Read through the code changes carefully after finishing work
- [ ] Make sure tests pass locally (after every commit!)
- [ ] Prepare changes in small commits for more convenient review (optional)
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### Sponsorship and Support:

This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.

The bug is found by running the Intelligent Code Repair (iCR) tool by OpenRefactory and then manually triaging the results.

### CODE REVIEW

**Comment by sondreso** [comment]
Hi, and thank you for you contribution! Apologies for not getting to this earlier.

The patch looks good, would you have time to resolve the merge conflict? (The file has just been moved to `src/ert/resources/forward-models/templating/script/template_render.py`)

**Comment by fazledyn-or** [comment]
Sure, let me get to that as soon as possible

**Comment by sondreso** [comment]
On a second look: 

We are not templating html files here, so isn't there a possibility that this change will escape characters that are not intended to be escaped? (For example a "<" that is not the start of a tag)

**Comment by fazledyn-or** [comment]
> On a second look:
> 
> We are not templating html files here, so isn't there a possibility that this change will escape characters that are not intended to be escaped? (For example a "<" that is not the start of a tag)

In that case, can you provide me an example of how the script is being used? If the consumer isn't consuming any sort of HTML or JSON file, then maybe the `autoescape` isn't really needed.

**Comment by sondreso** [comment]
> In that case, can you provide me an example of how the script is being used? If the consumer isn't consuming any sort of HTML or JSON file, then maybe the autoescape isn't really needed.

The script is intended to be used to template in parameters (numbers) into configuration files for a varying set of simulators that people may use. So I agree with you that `autoescape` is probably not needed here :slightly_smiling_face:

**Comment by fazledyn-or** [comment]
> > In that case, can you provide me an example of how the script is being used? If the consumer isn't consuming any sort of HTML or JSON file, then maybe the autoescape isn't really needed.
> 
> The script is intended to be used to template in parameters (numbers) into configuration files for a varying set of simulators that people may use. So I agree with you that `autoescape` is probably not needed here 🙂

In that case, let's close the PR here?

**Comment by sondreso** [comment]
Yes, I'll close it :slightly_smiling_face:  But thanks for the contribution and interest in the project!

**Pull request closed without merging**
