### PR TITLE
Fix spelling error in _post_update_data, algorithms -> algorithm

### PR DESCRIPTION
**Pull request by oysteoh**

### CODE REVIEW

**Review by dotfloat — APPROVED** [review]

**Comment by markusdregi** [comment]
Is this feasible to test?

**Comment by oysteoh** [comment]
> Is this feasible to test?

I guess so - i would probably never argue something to be impossible to test. But - the actual `post_update_data` is tested, this is the `_post_update_data` in `base_run_model` which does nothing but setting phase-name and call the `post_update_data` with the correct input. Unit-testing of the base-run model though i guess is quite hard to achieve, and - as seen in the HM tut which I think of as an integration-test failed and picked up this error. Not sure if it's worth doing more, but I will not argue against it 👍

**Comment by markusdregi** [comment]
Good point! This is food for our integration tests 👍🏻

**Review by markusdregi — APPROVED** [review]

**Comment by oysteoh** [comment]
Retest this please!

**Comment by oysteoh** [comment]
Test this please!

**Pull request merged**
