### PR TITLE
Use ert_storage.client

### LINKED ISSUE #2516: Utilizing storage-client in ert2 and ert3
We should utilize the storage-client in ert2 and ert3 and remove the old ways of connecting to ert-api.

### PR DESCRIPTION
**Pull request by frode-aarstad**
Resolves #2516

### CODE REVIEW

**Comment by pinkwah** [comment]
Feel free to @ me when this is ready for review (or if the original implementation is borked)

**Comment by jondequinor** [comment]
If I recall correctly, does not this produce intermittent crashes on Mac due to our use of bare `fork()`?

**Comment by pinkwah** [comment]
The client was basically moved to `ert-storage` and rewritten to use `httpx` as backend rather than `requests` for the sync version. What you're refering to was most likely the async stuff from `httpx`/`aiohttp`?

**Review by pinkwah — APPROVED** [review]
🥳 

Should probably wait for @jondequinor before merging though.

**Comment by jondequinor** [comment]
> The client was basically moved to `ert-storage` and rewritten to use `httpx` as backend rather than `requests` for the sync version. What you're refering to was most likely the async stuff from `httpx`/`aiohttp`?

Yes, thanks for pointing that out! Proceed!

**Comment by frode-aarstad** [comment]
Jenkins test this please

**Comment by frode-aarstad** [comment]
Jenkins test this please

**Comment by frode-aarstad** [comment]
Jenklins test this please

**Comment by frode-aarstad** [comment]
Jenkins test this please

**Pull request merged**
