### PR TITLE
Move parameter keys to ensemble_config

### PR DESCRIPTION
**Pull request by oyvindeide**
## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by oyvindeide** [comment]
Test this please

**Comment by oyvindeide** [comment]
Test failure is related to protobuf and not this PR

**Comment by oyvindeide** [comment]
test c please

**Review by eivindjahren — APPROVED** [review]
Already started building on top of it!

**Comment by oyvindeide** [comment]
test this please

**Pull request merged**
