### PR TITLE
Remove code that did nothing

### PR DESCRIPTION
**Pull request by oyvindeide**
get_mask() returns a copy of a bool_vector and deselectMatching
changes that mask inplace, so this code does nothing.

## Pre review checklist

- [ ] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Comment by jondequinor** [comment]
How did you come to this conclusion?

Doesn't `_select_matching` ultimately mutate the statemap itself?

**Comment by oyvindeide** [comment]
> How did you come to this conclusion?

> Doesn't _select_matching ultimately mutate the statemap itself?

Quite sure it doesnt, but will have to add some tests or something before this can be merged.

**Comment by joakim-hove** [comment]
> Doesn't `_select_matching` ultimately mutate the statemap itself?

The signature of `state_map_select_matching` is:
```C++
void state_map_select_matching(const state_map_type *map,
                               bool_vector_type *select_target, int select_mask,
                               bool select) {
```

I.e. the `state_map` itself is immutable; the selection is done on variable `select_target` where all elements where `select_mask & state_map_value != 0` are selected.

**Comment by oyvindeide** [comment]
> > Doesn't `_select_matching` ultimately mutate the statemap itself?
> 
> The signature of `state_map_select_matching` is:
> 
> ```c++
> void state_map_select_matching(const state_map_type *map,
>                                bool_vector_type *select_target, int select_mask,
>                                bool select) {
> ```
> 
> I.e. the `state_map` itself is immutable; the selection is done on variable `select_target` where all elements where `select_mask & state_map_value != 0` are selected.

Yes, and I believe the run-context is unaltered as well as the `select_target` in this case should be a copy which is not used.

**Comment by joakim-hove** [comment]
> Yes, and I believe the run-context is unaltered as well as the select_target in this case should be a copy which is not used.

Yes I agree - since the select process works on a copy this code does not have any effect. I don't know the slightly larger context here - but possibly this code should rather have used `ErtRunContext.deactive_realization()` to actually work on the mask of the run context?

**Comment by jondequinor** [comment]
To ensure we don't have holes in our test coverage, you could do this manual test to ensure you're not introducing regressions:

1. Run the poly smoother experiment, but introduce some random failures in poly.py
2. Ensure that for iter 1, no previously failed realizations exist

**Comment by oyvindeide** [comment]
I checked now, and this PR does not change the behavior compared with main, which is: if a realization fails at any iteration, it remains inactive in all subsequent iterations, meaning they are cumulative.

**Comment by oyvindeide** [comment]
test ert please

**Review by ManInFez — APPROVED** [review]

**Pull request merged**
