### PR TITLE
Remove unused functions on EnKFMain

### PR DESCRIPTION
**Pull request by oyvindeide**
## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by oyvindeide** [comment]
Error not related to PR:
`ModuleNotFoundError: No module named 'fmu.dataio.scripts'`

**Comment by sondreso** [comment]
Jenkins test this please

**Comment by oyvindeide** [comment]
> LGTM, what is the reason for removing the possibility to shrink the ensemble? 🤔

Because it is never used as far as I can tell, and just adds complexity. It is not tested, so there is no way of saying that it works as intended. Can leave it in though if you think it can add value in the future?

**Comment by sondreso** [comment]
No, I think this is fine! Just merge as is!

**Pull request merged**
