### PR TITLE
Update snake oil field test

### LINKED ISSUE #3938: Delete or verify that snake_oil_field works
**Describe the bug**
We are not sure that [test-data/local/snake_oil_field/make_data.py](https://github.com/equinor/ert/pull/3851/files#diff-3b7a85ae1dce0d6bfe4c230af28d4de4f91d080322d114239ae1573db664b9ef)is working. Check if this is the case and fix or delete.
Problem identified while reviewing #3851.

### PR DESCRIPTION
**Pull request by andreas-el**
**Issue**
Resolves #3938

**Approach**
Resolve exceptions caused during execution of snake_oil_field test
Refactor warnings caused by use of deprecated functionality

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by andreas-el** [comment]
We should consider updating the affected grid file in the repo, add the make_data.py as part of the testing/usecase or remove the generation script altogether.

**Review by DanSava — COMMENTED** [review]
The `make_data.py` is a very good example of how **not** to write python code! 

But the updates seem to fix the script and it looks OK. Not really clear if this script is still being used or was used just once to set things up and was left in the codebase in 2016. Maybe somebody with some more background information can pick in here.

**Comment by DanSava** [comment]
Jenkins add to whitelist!

**Review by DanSava — APPROVED** [review]
LGTM :+1:

**Comment by DanSava** [comment]
Jenkins test this, please!

**Comment by oysteoh** [comment]
> The `make_data.py` is a very good example of how **not** to write python code!
> 
> But the updates seem to fix the script and it looks OK. Not really clear if this script is still being used or was used just once to set things up and was left in the codebase in 2016. Maybe somebody with some more background information can pitch in here.

Based on history it seems the creator of this file is long gone from Equinor. But maybe @sondreso have an idea?

**Comment by sondreso** [comment]
I don't have any more information on this 😅

**Comment by oysteoh** [comment]
> I don't have any more information on this sweat_smile

Sorry - i actually mixed up with some other review and thought you had made changes to this file :sweat_smile: You have had absolutely nothing to do with it  !

**Pull request closed without merging**
