### PR TITLE
Fix circular import

### LINKED ISSUE #8840: Circular imports error when running gui.plottery tests
### What happened? (You can include a screenshot if it helps explain)

When running pytest in `gui/plottery` on main we are getting circular imports error:
For instance:
`pytest -svv tests/ert/unit_tests/gui/plottery/test_ensemble_plot.py`
will produce
```
ImportError while importing test module '/data/workspace/ert/tests/ert/unit_tests/gui/plottery/test_ensemble_plot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/data/env/py311-std/lib64/python3.11/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
/data/env/py311-std/lib64/python3.11/site-packages/_pytest/pathlib.py:582: in import_path
    importlib.import_module(module_name)
/usr/lib64/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1204: in _gcd_import
    ???
<frozen importlib._bootstrap>:1176: in _find_and_load
    ???
<frozen importlib._bootstrap>:1147: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:690: in _load_unlocked
    ???
/data/env/py311-std/lib64/python3.11/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
    exec(co, module.__dict__)
tests/ert/unit_tests/gui/plottery/test_ensemble_plot.py:7: in <module>
    from ert.gui.plottery import PlotConfig, PlotContext
src/ert/gui/plottery/__init__.py:13: in <module>
    from .plot_context import PlotContext  # noqa
src/ert/gui/plottery/plot_context.py:5: in <module>
    from ert.gui.tools.plot.plot_api import EnsembleObject
src/ert/gui/tools/plot/__init__.py:4: in <module>
    from .plot_tool import PlotTool
src/ert/gui/tools/plot/plot_tool.py:8: in <module>
    from .plot_window import PlotWindow
src/ert/gui/tools/plot/plot_window.py:13: in <module>
    from ert.gui.plottery import PlotConfig, PlotContext
E   ImportError: cannot import name 'PlotContext' from partially initialized module 'ert.gui.plottery' (most likely due to a circular import) (/data/workspace/ert/src/ert/gui/plottery/__init__.py)
```

It might be related to this commit:  https://github.com/equinor/ert/commit/156e202efac9f112f189acbf53270e2fc31955ec

### What did you expect to happen?

Just run pytest...

### steps to reproduce

```Python
`pytest -svv tests/ert/unit_tests/gui/plottery/test_ensemble_plot.py`
```

### Environment where bug has been observed

- [X] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [X] python 3.11
- [X] python 3.12
- [ ] macosx
- [X] rhel7
- [X] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

### PR DESCRIPTION
**Pull request by eivindjahren**
**Issue**
Resolves #8840

**Approach**
Use `TYPE_CHECKING`

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Make sure unit tests pass locally after every commit (`git rebase -i main
      --exec 'pytest tests/ert/unit_tests -n logical -m "not integration_test"'`)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Review by berland — APPROVED** [review]
👍🏻

**Comment by xjules** [comment]
Were this all occurrences? Not at the least  the histogram was failing...

**Comment by eivindjahren** [comment]
> Were this all occurrences? Not at the least the histogram was failing...

The issue did not mention that test. I will create a separate PR for that

**Comment by xjules** [comment]
> > Were this all occurrences? Not at the least the histogram was failing...
> 
> The issue did not mention that test. I created a separate PR for that: #8897

That is not correct. The issue mentions circular imports in plottery tests and give  the ensemble.py as an example.

**Pull request merged**
