### PR TITLE
Add dataflow diagram for ERT

### LINKED ISSUE #6252: Create diagram illustrating class/component interaction in ERT experiment
**The problem**
It is difficult visualizing and understanding ERT when it is split into dozens of classes which seemingly all call one another somehow.

**A potential solution**
A dataflow diagram showing how an experiment is run and in what order the components/classes are ran

### PR DESCRIPTION
**Pull request by jonathan-eq**
**Issue**
Resolves #6252 

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

## Pre review checklist

- [ ] Read through the code changes carefully after finishing work
- [ ] Make sure tests pass locally (after every commit!)
- [ ] Prepare changes in small commits for more convenient review (optional)
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jonathan-eq** [comment]
To open the diagram, you need mermaid cli.
Run mmdc -i ERT_SYSTEM_DIAGRAM.md

**Comment by berland** [comment]
That is a good overview. I could not easily install mmdc on my workstation (RHEL7) but I could view it online.

This is certainly a nice diagram to look at while studying the ert code. I do however wonder where we should put it. My bets are that this diagram will be quickly outdated while refactorings are continously performed, and will not receive the needed love and care for it to stay up to date. A possiblity could be to put it https://github.com/equinor/scout/tree/main/discussions-summaries-workshops but the downside is that it is a closed repository.

**Comment by jonathan-eq** [comment]
Yes, it is probably already outdated, but I am sure it can be used at least until new years for helping the new joiners get a basic understanding of the ert code

**Comment by xjules** [comment]
> That is a good overview. I could not easily install mmdc on my workstation (RHEL7) but I could view it online.
> 
> This is certainly a nice diagram to look at while studying the ert code. I do however wonder where we should put it. My bets are that this diagram will be quickly outdated while refactorings are continously performed, and will not receive the needed love and care for it to stay up to date. A possiblity could be to put it https://github.com/equinor/scout/tree/main/discussions-summaries-workshops but the downside is that it is a closed repository.

The diagram itself is an internal "help" for ert developers so I don't see a problem to put it there.

**Comment by xjules** [comment]
What about this one @jonathan-eq ?

**Comment by jonathan-eq** [comment]
It is getting outdated very fast, so do we update it, or abandon it?
For my part, it has been extremely useful to see the big picture of ERTs architecture and design, but that was mostly by having to read ALL the code.

**Pull request closed without merging**
