### PR TITLE
Support blob output records

### LINKED ISSUE #1920: Support blob output records
**Introduction**
The forward model will generate blobs of data that we need to transport.

**Requested feature**
Make it possible to have output records that are blobs.

**Definition of done**
When the SPE1 example internalises its summary files as blob data that can be retrieved afterwards used the storage API.

**Additional information**
I think it is a good idea to first solve #1919, as currently the blob record is lingering somewhere between being fixed over an ensemble and being treated as a normal record. Making the current usage explicitly not what this issue is asking for will most likely be beneficial.

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #1920

### CODE REVIEW

**Comment by verveerpj** [comment]
This looks good to me. One question: looking at the changes, they seem mostly to be a (nice) refactoring to have a better resources handling. Does is resolve the connected issue? I.e. are blob output records handled properly? there seems to be no code changes directly related to that, but maybe that was not needed?

**Comment by DanSava** [comment]
This commit `Fix stage config loading of mime types` contains some changes that allow output results to be also blobs. And yes most of the changes focus on loading data into storage without the explicit use of the load record command.

**Comment by verveerpj** [comment]
> This commit `Fix stage config loading of mime types` contains some changes that allow output results to be also blobs. And yes most of the changes focus on loading data into storage without the explicit use of the load record command.

Yes, see it now. Looks fine to me, will approve.

**Review by verveerpj — APPROVED** [review]
LGTM!

**Pull request merged**
