### PR TITLE
Add record class 'response' to extracted responses

### PR DESCRIPTION
**Pull request by ManInFez**
add record class 'response extracted ert2 responses

### CODE REVIEW

**Review by xjules — APPROVED** [review]
LGMT!

**Comment by ManInFez** [comment]
Test this please!

**Comment by markusdregi** [comment]
Should not responses from `ert3` also be labelled?

**Comment by ManInFez** [comment]
In the first iteration of ert3 - ert-storage, we only used "files" for storing data, as defining types and class was not available in the config. For ert2, we already know that the extracted vectors are matrices and responses. But yes, when the ert3 config is a bit more complete, we should label the data from ert3 as well :) This will most likely happen in the transmitters.

**Comment by markusdregi** [comment]
Makes sense 👍🏻 We can deal with it later... Just remember that the definition of done for the milestone includes being able to visualize output data from an `ert3` run :)

**Pull request merged**
