### PR TITLE
Flaky distribution tests

### LINKED ISSUE #1215: The distribution tests are flaky
We have some tests verifying the correctness of distribution sampling. They do occasionally fail, which is expected due to the design of the tests. We should fix this.

**Some possible approaches**
- Allow a larger error to decrease the probability of failing,
- Run the tests multiple times and require it to pass almost always,
- Run the tests with multiple, but fixed random seeds,
- Others?

### PR DESCRIPTION
**Pull request by markusdregi**
Resolves #1215

**Approach**
Increased the size of the sampling a bit and then I introduced `flaky` and let it enforce that the tests should pass at least 2 out of 3 times.

### CODE REVIEW

**Comment by markusdregi** [comment]
I also installed `pytest-repeat` and I'm now in the process of running:

```
pytest -vs -k test_gaussian_distribution -x --count=1000
```

which will run all of the tests 1000 times and fail it a single one of them fail. So that should at least verify that the flakiness have been reduced. It have also turned out to be excellent morning gymnastics for my laptop :)

**Comment by markusdregi** [comment]
```
===End Flaky Test Report===

============================================================================== 5000 passed, 224125 deselected in 685.38s (0:11:25) ===============================================================================
```

It passed :)

**Comment by autt** [comment]
Maybe a similar approach can be considered for the integration tests asserting the parameter statistics? I have experienced some of the same flakiness there

**Comment by markusdregi** [comment]
@autt We can do that 👍 I was actually thinking that we could just remove that part of the integration testing, ref: https://github.com/equinor/ert/issues/1204.

The correctness of the sampling is tested when testing the sampling. That the correct sampling is used in the evaluation and that the responses are computed correctly is tested in the integration, but there is no need for again testing the sampling itself 🤷 And by removing that part of the test we can decrease the size of the ensemble and bring down the test runtime quite a bit :)

**Comment by markusdregi** [comment]
After a quick round with myself I followed up on your suggestion of making it flaky until the referred issue above is solved @autt

**Comment by autt** [comment]
I see your point about just removing them @markusdregi! But thanks for fixing, now we hopefully won't be bothered by the flakiness until the issue mentioned above is solved 👍

**Review by autt — APPROVED** [review]

**Pull request merged**
