### PR TITLE
[WIP] Parameter visualization

### LINKED ISSUE #773: Visualize the parameters from the API

### PR DESCRIPTION
**Pull request by asnyv**
**Issue**
Resolves #773 

**Approach**
Added an example of parameter distribution visualization beneath the response graph in the dash prototype. Just a rewrite of the [Webviz ParameterDistribution](https://github.com/equinor/webviz-subsurface/blob/master/webviz_subsurface/plugins/_parameter_distribution.py) to use Ert API live.
_Working_, but terribly slow when changing parameter. Room for optimization. Would most likely benefit greatly from #793

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by lars-petter-hauge** [comment]
Cool! although there are performance issues (both in terms of how the api is structured, and the backend that we use), I think this is a good start showcasing how the usage would be. Happy to see that there's already an issue made to improve the API

**Comment by anders-kiaer** [comment]
@asnyv @lars-petter-hauge Should we wait with merge of this until after #793?

@asnyv  Any remaining points (`WIP`) of this prototype visualization as you see it, except data input performance?

**Comment by asnyv** [comment]
@anders-kiaer I think we should wait for #793. As it is now, it isn't as responsive as you would like a demo to be. Could also be done some work on getting a more coherent codestyle (some copy-pasted code from Webviz with minimal adjustments combined with the existing code. Typically things like method/variable naming, use of `'` vs `"` and etc. 
Also the design of the response graph and the parameter distribution doesn't combine that well. Not sure if we care? A bit limited what we can do with the parameter distribution without rewriting the JavaScript code in wsc (or making a new class). E.g. now we have two different ensemble selectors: A dropdown for the response graph and a slider for the parameter distribution.

**Comment by lars-petter-hauge** [comment]
>Also the design of the response graph and the parameter distribution doesn't combine that well. Not sure if we care? A bit limited what we can do with the parameter distribution without rewriting the JavaScript code in wsc (or making a new class). E.g. now we have two different ensemble selectors: A dropdown for the response graph and a slider for the parameter distribution.

Is it necessary to import anything from `webviz`?  I suggest that the `dash` implementation here is completely trivial regarding how it looks. The most important part here is that it should showcase what is possible and how it is done (as in collecting data). Therefore I think the only necessary component should be `dash`. We might have other users than `Equinor` as well, we shouldn't make things more complicated than it is :)

> Typically things like method/variable naming, use of ' vs " and etc.

Run all the `dash` files with `Black`?

Remember to also rebase this pr on `ertviz-workshop`

**Comment by asnyv** [comment]
> Is it necessary to import anything from webviz? I suggest that the dash implementation here is completely trivial regarding how it looks. The most important part here is that it should showcase what is possible and how it is done (as in collecting data). Therefore I think the only necessary component should be dash. We might have other users than Equinor as well, we shouldn't make things more complicated than it is :)

We don't have to, was just a quick way to get something up as the code was already there (and only requires a `pip install webviz-subsurface-components`, so it isn't _that hard_ to get going). Could switch to something trivial like a basic histogram of a parameter for a given ensemble.

> Run all the dash files with Black?

Yes, this is not really an issue, just a reason not to merge as is.

> Remember to also rebase this pr on ertviz-workshop

Will do that before a merge 👍

**Pull request closed without merging**
