### PR TITLE
Force fortran order for row scaling

### PR DESCRIPTION
**Pull request by dafeda**
Row scaling calls C++ code via pybind11 that expects Fortran order.

## Pre review checklist

- [ ] Read through the code changes carefully after finishing work
- [ ] Make sure tests pass locally (after every commit!)
- [ ] Prepare changes in small commits for more convenient review (optional)
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by oddvarlia — COMMENTED** [review]
When I tested this with your change and without your change I got the same result (The order is not changed), but it does not mean the the memory layout is not changed.  But anyway it looks like it works using the version without this.  So when the scaling parameter is delivered from the non-adaptive localisation as a c-order flatten masked array, the result seems to be correct. I assume parameter.row_scaling contains the scaling factors calculated by the non-adaptive localisation code where the scaling factors are delivered to rowscaling object. Maybe I misunderstand numpy, but numpy.asfortranarray(vector) rearrange in memory to be fortran contiguous, but it does not change the index order like what numpy.ndarray.flatten(order=something) may do. So for me it looks like the index order is not change and that works anyway, but probably using fortrancontiguous input to the C++ library is more efficient?

**Comment by dafeda** [comment]
> When I tested this with your change and without your change I got the same result (The order is not changed), but it does not mean the the memory layout is not changed. But anyway it looks like it works using the version without this. So when the scaling parameter is delivered from the non-adaptive localisation as a c-order flatten masked array, the result seems to be correct. I assume parameter.row_scaling contains the scaling factors calculated by the non-adaptive localisation code where the scaling factors are delivered to rowscaling object. Maybe I misunderstand numpy, but numpy.asfortranarray(vector) rearrange in memory to be fortran contiguous, but it does not change the index order like what numpy.ndarray.flatten(order=something) may do. So for me it looks like the index order is not change and that works anyway, but probably using fortrancontiguous input to the C++ library is more efficient?

The main reason to convert to Fortran order here is because `pybind11` will make a copy of the array if it's C-order.
The results should however stay the same as you observe.

**Review by oyvindeide — APPROVED** [review]
> The main reason to convert to Fortran order here is because pybind11 will make a copy of the array if it's C-order.
The results should however stay the same as you observe.

That is not very obvious, so perhaps add a comment about that?

**Comment by dafeda** [comment]
> > The main reason to convert to Fortran order here is because pybind11 will make a copy of the array if it's C-order.
> > The results should however stay the same as you observe.
> 
> That is not very obvious, so perhaps add a comment about that?

Good point. I've added a comment.

**Pull request merged**
