### PR TITLE
Rename test to avoid conflict

### PR DESCRIPTION
**Pull request by dafeda**
**Issue**
Resolves #my_issue

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Review by BjarneHerland — APPROVED** [review]
Good

**Comment by dafeda** [comment]
> Dont mind this change, but the long term solution to this problem should most likely be to move source under `src/` and introduce `__init__.py` files in the test folders, it is the recommended pytest [practice](https://docs.pytest.org/en/6.2.x/goodpractices.html).

Thanks, was not aware.

What should be put into the `src` folder?
`ert`, `ert3` ++?

Do you think we should do the change now, in this PR even?

**Comment by oyvindeide** [comment]
> What should be put into the `src` folder? `ert`, `ert3` ++?

Yes, all of the above

> Do you think we should do the change now, in this PR even?

I you are willing to try, sure. Though I was informed by @sondreso that this has been attempted before, and there was some issues related to editable install (and `src/`), though we have made some changes to the build system since then. Do you think that might have fixed the issues you saw @pinkwah?

**Comment by dafeda** [comment]
> > What should be put into the `src` folder? `ert`, `ert3` ++?
> 
> Yes, all of the above
> 
> > Do you think we should do the change now, in this PR even?
> 
> I you are willing to try, sure. Though I was informed by @sondreso that this has been attempted before, and there was some issues related to editable install (and `src/`), though we have made some changes to the build system since then. Do you think that might have fixed the issues you saw @pinkwah?

I'll merge this now just to have things working, but great if we can fix it properly.

**Pull request merged**
