### PR TITLE
Re-enable retries for function and unix tasks

### LINKED ISSUE #1583: Re-enable retries for function and unix tasks
**Description**
In the refactoring process, it seems the prefect retry functionality was lost in translation.

Put it back. and make sure the `max_retries` from the prefect config is used when creating the tasks.

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #1583

### CODE REVIEW

**Comment by jondequinor** [comment]
Could we have a test for this, so that we do not accidentally remove it twice?

**Comment by DanSava** [comment]
> Could we have a test for this, so that we do not accidentally remove it twice?

I was already working on that :sunglasses:

**Comment by markusdregi** [comment]
Jenkins: Test this please

**Comment by DanSava** [comment]
Jenkins: Test this please

**Comment by jondequinor** [comment]
`Address already in use`. Not quite sure what's going on.

**Comment by DanSava** [comment]
Yes, that is a bit strange, but I don't think my changes are causing the instability.

**Review by sondreso — COMMENTED** [review]
Think this looks good, but needs a rebase now that the context PR was merged!

**Review by sondreso — APPROVED** [review]
Nice 👏

**Pull request merged**
