### PR TITLE
The startup feedback screen now uses equinor design system colors and icons

### PR DESCRIPTION
**Pull request by eivindjahren**
The following image shows the general idea. The PR does not as of yet set the font until we can figure out how to handle CDN.

image

## Pre review checklist

- [x] Read through the code changes carefully after finishing work
- [x] Make sure tests pass locally (after every commit!)
- [ ] Prepare changes in small commits for more convenient review (optional)
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by kwinkunks — APPROVED** [review]
Looks super nice

**Comment by kwinkunks** [comment]
Oh, oops, approved a draft :facepalm:

**Comment by eivindjahren** [comment]
Just need to figure out the resources :D

**Review by oyvindeide — APPROVED** [review]
LGTM! Nice improvement!

**Review by oyvindeide — APPROVED** [review]
Double approve!

**Pull request merged**
