### PR TITLE
Gui optimization

### LINKED ISSUE #1838: Reports of unresponsive monitoring GUI on RGS nodes
Users are reporting unresponsive monitoring GUI on RGS nodes. A first step would be to try to recreate this with a benchmark setup with ~200 jobs and ~200 realisations. We should also look into whether the local and lsf queue system makes a difference here.

### PR DESCRIPTION
**Pull request by jondequinor**
**Issue**
Resolves #1838 

**Approach**
- Avoid pydantic models in GUI-affine threads
- Pre-render data outside GUI-affine threads, in our case in the `TrackerWorker` thread
- Introduce `QueueDiffer` into legacy evaluation tracking
- QImage rendering of job statuses
- Use pre-rendered data in views

**Queue Differ**
In the legacy ensemble evaluator, the queue and its state, is tracked by keeping a list of statuses and mutating it as time passes. The difference before and after mutation is communicated to the ensemble evaluator.

This approach wasn't used by the legacy-legacy evaluation, where a status would be sent regardless if it had been sent previously—i.e. we did not compare pre-mutation to post-mutation. This led to excessive updates in the GUI. A `QueueDiffer` class has been created and is now used by both legacy EE and legacy-legacy.

**Avoiding pydantic models**
In the GUI-affine threads, objects should be as simple as possible. Pydantic models are quite heavy, and allocation even heavier, so GUI now avoids them. This questions the usefulness of the `SnapshotDict` class, and I have created an issue to track this discussion and potential resolution [here](https://github.com/equinor/ert/issues/1869).

**QImage rendering**
Instead of allocating and drawing—potentially thousands of `QRect`s—I've gone back to how it used to be in the old days. The job statuses as they appear inside the realization grid are drawn from (cached) `QImages`, where one pixel represents a job status, that QT then scales up. This is, by rough estimates, twice as fast.

**Pre-rendered data**
During painting of various elements of the snapshot, it is preferable to not having to allocate the same colors (represented by the `QColor` class`) thousands of times, so we allocate these _once_ and insert them where appropriate. Additionally, we want to lay out e.g. realizations in an orderly fashion; reals have no order in the snapshot model, but we order them by casting their ids as ints and then doing numerical sort. This ordering is pre-rendered so as to do it as few times as possible, and _not_ in the GUI-affine threads.

Highly recommend commit-based review

### CODE REVIEW

**Review by markusdregi — COMMENTED** [review]
I've done some testing on an RGS node and I can confirm that the performance is significantly better 👍🏻I tested on a modified polynomial case repeating the polynomial calculation step 200 times with 200 realisations.

My findings where:
 - With the bleeding build the performance was terrible on the local queue. The GUI froze completely, the OS suggested to kill the application and I did not manage to shut it down again via the GUI (in the end I accepted the OS killing it).
 - With the patch in this PR the performance improved vastly. The application never had problems keeping alive. As long as I did not interact with the GUI the timer looked smooth. However, when interacting with the GUI it typically had a response time of a second. The OS never suggested to kill ERT.
 - Similar performance was experienced when running the above patch on the lsf cluster.
 - When running the same setup over lsf with `--enable-ensemble-evaluator` it seems like I'm getting no updates for the different jobs...

**Comment by markusdregi** [comment]
I'll report back ASAP whether the last point is a regression or not...

**Comment by markusdregi** [comment]
The last can be reproduced also with `bleeding` and is hence not a regression in this PR. I'll create an issue 👍🏻

**Comment by jondequinor** [comment]
Thanks for testing!

**Review by markusdregi — APPROVED** [review]
The changes seems good and the performance definitively improved 👍🏻

**Pull request merged**
