### PR TITLE
UUID primary key

### PR DESCRIPTION
**Pull request by oysteoh**
instead of using autoincremented integers we want to use uuid's and expose those as identifiers through the api. To avoid human interpretation of the id's - i think it's better have an id which have no other purpose than to identify an object.

### CODE REVIEW

**Comment by jondequinor** [comment]
Have we considered using composite keys? In some cases, a distinct `id` on some entity might be duplicating data.

E.g. if an ensemble member is fully identifiable by the iteration number and member number, the primary key could be a composition of the two.

**Comment by oysteoh** [comment]
> Have we considered using composite keys? In some cases, a distinct `id` on some entity might be duplicating data.
> 
> E.g. if an ensemble member is fully identifiable by the iteration number and member number, the primary key could be a composition of the two.

i guess we might have discussed at one point - but not lately. we have just discussed and agreed on going away from integers at the moment. I'm all open for discussions though - and i will welcome suggestions! 

do you see any particular drawbacks of using uuids except from the _duplicating data_ issue you mentioned? and is that one relevant for us?

**Comment by jondequinor** [comment]
Yes, I agree automatically incremented IDs present numerous problems. In distributed computing, UUIDS makes more sense.

My suggestion to consider finding composite keys to use instead of introducing _non-natural_ keys, like `id` is a bit flawed. It assumes it is at all _possible_ to find natural keys that eternally, uniquely identify some relation (e.g. an ensemble). I don't think, for example, an iteration number and a realization number _is_ a natural key of an ensemble. And it's hard to find natural keys for the other relations as well.

The classic example is `ssn` (social security number). Is it a natural key? No, because it can change for a person. A natural key must remain uniquely identifying over time. 

In practice, introducing these `id` keys may have theoretical downsides, but I think they can largely be mitigated by imposing constrains on e.g iter and real numbers for some "case". And I think the benefits (speed, ease of use, conventional) outweighs the downsides (bad joins, slight redundancy i.e. not fully normalized, etc).

**Comment by jondequinor** [comment]
A second question is one of migration. Where's the data migration defined? :smile:

**Comment by oysteoh** [comment]
closing this for now - if picked up again it will be a new pr as a lot of things have changed!

**Pull request closed without merging**
