### PR TITLE
Replace console progressbar

### PR DESCRIPTION
**Pull request by dafeda**
**Approach**

[console-progressbar](https://github.com/bozoh/console_progressbar) is not a particularly popular project (9 ⭐ ), and according to its [pypi-page](https://pypi.org/project/console-progressbar/) only supports up to Python 3.6.

It is specified as `console-progressbar==1.1.2` in our `setup.py`, which according to [our ongoing discussion around specifying versions](https://github.com/equinor/ert/issues/1999) is perhaps not what we want.

I propose replacing it with [tqdm](https://github.com/tqdm/tqdm).

Before I spend too much time on making it look pretty, I would like some feedback on whether you think this is a good idea or not.

### CODE REVIEW

**Comment by dafeda** [comment]
I have not spent too much time making the output look identical, and not sure whether I should.


Using `console-progressbar`:

Screenshot 2021-09-21 at 12 51 30

Using `tqdm`:

Screenshot 2021-09-21 at 12 55 44

**Comment by jondequinor** [comment]
I favor the esthetics of the first one—can't that be fixed in tqdm?? pipe it through a filter? :p

**Comment by markusdregi** [comment]
I did some comparison locally of the two progress bars on the polynomial example. First, I'm very happy to see the colors still being around 🎉 Second, it seemed to work really well 👍🏻 Third, I really missed the iteration count. It does not make much of a difference when running an experiment as you did above, but with the smoother (or algorithms with even more iterations) it is really nice to easily see which iteration one is at. I used the smoother for comparison (`ert ensemble_smoother poly.ert --target-case=posterior`) and the old progress bar would have the `1/2` go into a `2/2` and then complete later :) Can we have it?

**Comment by dafeda** [comment]
I have tried to cater to both your aesthetical senses @semafor and @markusdregi , by adding some nice padding and bringing back the phase numbers.

Better?

Screenshot 2021-09-23 at 13 03 51

**Comment by markusdregi** [comment]
The iteration works now 👏🏻 But the `Running time` seems to not update?

Also, when down sizing my terminal window the bar becomes a bit ugly over multiple lines. I don't think that is completely avoidable, but perhaps slightly better if we do a maximum width of the bar independent of the terminal size?

**Comment by dafeda** [comment]
Fixed the elapsed time and changed width.

Screenshot 2021-09-23 at 16 03 50

**Comment by jondequinor** [comment]
I'm ready to approve this, but final (optional) nitpick:

```
1/1: |████|100% Running time: 4s
   ^       ^
remove?    add a space?    
```

**Review by jondequinor — APPROVED** [review]
Approval with final (optional) nitpick:

```
1/1: |████|100% Running time: 4s
   ^       ^
remove?    add a space?    
```

Great work!

**Comment by dafeda** [comment]
> Approval with final (optional) nitpick:
> 
> ```
> 1/1: |████|100% Running time: 4s
>    ^       ^
> remove?    add a space?    
> ```
> 
> Great work!

Your nitpicking is appreciated.

I agree that this looks better:

Screenshot 2021-09-24 at 09 30 14

Something a bit strange is going on in the test `test_print_progress`.
Even though the function that draws the progress-bar is only called once, two lines containing a progress-bar show up:

```python
        expected = """    --> Test Phase

    |                                                                        |   0% Running time: it
    1/2 |##################################                                  |  50% Running time: 0s
    Waiting        50/100
    Pending         0/100
    Running         0/100
    Failed          0/100
    Finished       50/100
    Unknown         0/100

"""
```

Also, which phase is running is not shown in the first line.

I suspect this has something to do with the way `tqdm` does its refreshing, but am not sure how to fix it.

Any immediate ideas @semafor ?

**Comment by jondequinor** [comment]
@dafeda did you find the issue?

**Comment by dafeda** [comment]
> @dafeda did you find the issue?

No, figured I should not spend too much time on it given that it seems to work fine during normal usage.
You think I should have another look?

**Comment by dafeda** [comment]
Jenkins test this please

**Pull request merged**
