### PR TITLE
Remove nfs_adaptor

### LINKED ISSUE #1344: Legacy evaluator should stop writing events to disk
Currently the legacy evaluator writes the events to disk over the  `NFSAdapter`. We have now open ports, should use them instead.

### PR DESCRIPTION
**Pull request by mortalisk**
Resolves #1344 

Depends on https://github.com/equinor/libres/pull/1130

### CODE REVIEW

**Comment by sondreso** [comment]
Is this ready for review? Tests seems to be cancelled due to hanging :thinking:

**Comment by mortalisk** [comment]
The code depends on the libres changes.

**Review by sondreso — COMMENTED** [review]
This looks good to me but needs an update to the requirements when https://github.com/equinor/ert/pull/1517/files is merged 🚀

**Comment by sondreso** [comment]
Created https://github.com/equinor/libres/releases/tag/10.0.0b0

**Review by sondreso — APPROVED** [review]
LGTM!

**Pull request merged**
