### PR TITLE
Adjust the size of ERT main window after config warnings

### LINKED ISSUE #6461: ERT GUI window does not resize properly after displaying warnings on startup
**Describe the bug**
When opening ert with a configuration warning, the "Something is wrong" window will be displayed. If you then choose to press "Open ERT", ERT main window will open with a very unpractical size.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Fabricate a warning in the poly.ert file. For instance MIN_REALIZATIONS > NUM_REALIZATIONS.
3. `ert gui my_config.ert`
4. Press "Open ERT" in the Warnings Window.

**Expected behaviour**
ERT main window should open in same size as it would without any warnings.

**Screenshots**
image

**Environment**
 - OS: MacOS
 - ERT/Komodo release: main
 - Python version: 3.11
 - Remote/HPC execution involved: [no]

### PR DESCRIPTION
**Pull request by larsevj**
**Issue**
Resolves #6461 

## Pre review checklist

- [x] Read through the code changes carefully after finishing work
- [x] Make sure tests pass locally (after every commit!)
- [x] Prepare changes in small commits for more convenient review (optional)
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [x] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by larsevj** [comment]
Not entirely sure what goes wrong, but explicitly resizing when activating main window seems to fix this. I also removed the somewhat arbitrarily resizing to (300, 700) after initialization as I cannot see why this is done?

**Comment by larsevj** [comment]
Also I cannot see that `self.__main_widget` in ErtMainWindow is used at all? Should it be removed or does it have a purpose?

**Comment by andreas-el** [comment]
> Not entirely sure what goes wrong, but explicitly resizing when activating main window seems to fix this. I also removed the somewhat arbitrarily resizing to (300, 700) after initialization as I cannot see why this is done?

I think removing this makes sense. These numbers certainly wasn't part of any design-spec for sure.

**Comment by andreas-el** [comment]
> Also I cannot see that `self.__main_widget` in ErtMainWindow is used at all? Should it be removed or does it have a purpose?

```
 def setWidget(self, widget):
        self.__main_widget = widget
        actions = widget.getActions()
        for action in actions:
            self.__view_menu.addAction(action)

        self.central_layout.addWidget(widget)
```

It seems to be updated here. This might also affect lifetime of the Qt object.

**Comment by andreas-el** [comment]
BTW. I've tried replicating this issue, but seem to fail doing so. Is this a Mac specific problem, or have you been able to reproduce this elsewhere also?

**Review by andreas-el — APPROVED** [review]
I think this is a slight step in the right direction. 👍

**Pull request merged**
