### PR TITLE
New storage

### PR DESCRIPTION
**Pull request by sondreso**
Adds new storage :)

### CODE REVIEW

**Comment by markusdregi** [comment]
Is there any hope of splitting this into multiple commits?

**Comment by markusdregi** [comment]
Besides that my initial comment is 🤩

**Comment by sondreso** [comment]
I can try to get the black stuff and the feature toggling in separate commits, other than that it's very difficult!

**Comment by markusdregi** [comment]
It would help a lot if we could bring the changes outside of the storage module into separate commits. Debugging a breaking change in this commit will be not so much fun 😬

**Comment by sondreso** [comment]
I will do my best

**Comment by markusdregi** [comment]
Perfect 👏 With the amount of work you've done together in a feature branch, some serious amount of work on fixing the git history is to be expected afterwards ;)

**Pull request closed without merging**
