### PR TITLE
Make run path label copiable in the gui

### LINKED ISSUE #4641: Make Runpath in GUI copyable
**Is your feature request related to a problem? Please describe.**
I have observed users manually typing the runpath displayed in the GUI to send it to colleagues.

**Describe the solution you'd like**
Be able to copy the runpath. 
Perhaps add a copy symbol.

**Additional context**
copyable_runpath

### PR DESCRIPTION
**Pull request by yngve-sk**
**Issue**
Resolves #4641 

**Approach**
image

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Updated documentation
- [x] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by eivindjahren** [comment]
The style check workflow is failing, so you need to address that first :)

**Comment by eivindjahren** [comment]
I think it would be nice to use a icon instead of the text "copy". We could use one of the (remixicons)[https://remixicon.com/] and load it with ertwidgets.resourceImage

**Comment by oyvindeide** [comment]
Jenkins: add to allowlist

**Pull request closed without merging**
