### PR TITLE
Minor fixes and corrections to the observation format docs

### PR DESCRIPTION
**Pull request by berland**
* Typos
* Error in ERROR_COVAR keyword name
* Remove erroneous colour highlighting
* Header levels adjusted.
* Whitespace cleanup by `vim`

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Review by sondreso — APPROVED** [review]
LGTM! Thanks for the contribution!

**Comment by sondreso** [comment]
Jenkins safe to test

**Comment by sondreso** [comment]
Jenkins test this please

**Pull request merged**
