### PR TITLE
Cleanup RST files, and doc hint

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves:

1. Whitespace issues, both critical for formatting and for maintenance (tabs -> spaces)
2. User request on a hint on REFCASE in OBS_CONFIG

**Approach**
text edit

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by markusdregi** [comment]
Looks like a good clean-up 👏 Regarding the tabs, any reason you choose to replace them with 8 instead of 4 spaces?

**Comment by berland** [comment]
> Looks like a good clean-up  Regarding the tabs, any reason you choose to replace them with 8 instead of 4 spaces?

Trial and error! Replacing each tab with 4 space left a big mess. Replacing with 8 aligned everything perfectly.

**Review by markusdregi — APPROVED** [review]
Good enough of a reason for me 👍 Thanks for the fixes 👏

**Pull request merged**
