### PR TITLE
WIP: ERT3 inputs: handling directories / tar files

### LINKED ISSUE #2016: Allow directories to be passed as input in ert3
**Is your feature request related to a problem? Please describe.**
Currently ert3 does not allow the user to specify an entire directory that they would like to transport to the compute environment. 
This is something we would like to support.

**Describe the solution you'd like**
For the user to specify a directory as input and have the directory show up in some specific location in the step. (Only applies to the Unix step, the function step would just receive a byte stream)

**Describe alternatives you've considered**
We would have toe extend the Unix step to accept a DirectoryIO type (or extend FileIO), and do custom handling similar to the executable files. Then we need to expose these concepts in the ert3 configuration

### PR DESCRIPTION
**Pull request by xjules**
**Issue**
Resolves #2016 

**Approach**
We need to provide a way that a given input (in the stage/step config) can be specified as directory or a tar file (essentially created and passed over). The unix step can then process such an input by unpacking it first. In the first iteration, this will add `application/x-tar` type into the file mimes. 

We might drop `RecordType.TAR` type when we make sure that specifying such input in the config suffices.

### CODE REVIEW

**Review by jondequinor — COMMENTED** [review]
- This looks good, but could you add a TODO and link to an issue tracking the second iteration of this? 
- did you consider gzipping the tarball?

**Comment by markusdregi** [comment]
How will this be handled in the cli when loading the input data? Are we planning to deduce the mime-type based on whether the path is a file or directory or will there be a recursive flag to ensure that the user really intended to bring it all along?

**Comment by xjules** [comment]
> This looks good, but could you add a TODO and link to an issue tracking the second iteration of this?
did you consider gzipping the tarball?

I've put this PR/issue back in TODO and the related issues (ie. replacing one) is here: https://github.com/equinor/ert/issues/2038

**Comment by xjules** [comment]
> How will this be handled in the cli when loading the input data? Are we planning to deduce the mime-type based on whether the path is a file or directory or will there be a recursive flag to ensure that the user really intended to bring it all along?

Yes, in the current version the `mime-type` will be determined whether it is a file or a directory - given `tar` archive at least. Later on we aim to propose `RecordTransforms` which should provide users to select chain of such transformations from a predefined set. More here: https://github.com/equinor/ert/issues/2038

**Comment by xjules** [comment]
Closing this PR since it's been superseded by https://github.com/equinor/ert/pull/2040

**Pull request closed without merging**
