### PR TITLE
Replace deprecated `..index.is_all_dates` in plottery

### PR DESCRIPTION
**Pull request by oysteoh**
**Issue**
`..index.is_all_dates` is deprecated and needs to be replaced. 

**Approach**
Extracted functionality making the check and verified the behavior with test.

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by BjarneHerland** [comment]
Looks sane but I don't really see the need for the util-method. Why not just replace

`if not data.index.is_all_dates`

with

`if data.index.inferred_type != "datetime64"`

It eliminates the need for a test (which in reality just tests Pandas-functionality) as well as a number of imports. If checking the inferred type feels confusing, just add a comment a-la

`if data.index.inferred_type != "datetime64" # index is not all datetime`

**Comment by oysteoh** [comment]
Agree- it was mostly when fixing verifying the behavior was the same.. I will fix it!

**Review by DanSava — APPROVED** [review]
LGTM

**Comment by BjarneHerland** [comment]
Uhh....  agreed changes has not bee performed yet, but due to auto-merge enabled, it merged anyway  😬

**Pull request merged**
