### PR TITLE
Remove more unused files and other cleanup

### PR DESCRIPTION
**Pull request by BjarneHerland**
Changed suffix on two files which are not source but README's, removed several files not used, removed two files which apparently have served as templates for new tests.

I decided to put this in one PR but the commits are atomic.

### CODE REVIEW

**Comment by ManInFez** [comment]
Could you add which files are removed in the commit message?

**Review by eivindjahren — CHANGES_REQUESTED** [review]
Less files is good, no objection from me. The documentation in README.new_type.hpp is, in my opinion outdated or at least standard C practice. Recent discussion suggests that new types should be (or at least could be) created as C++ classes. I suggest we simply remove this file.

**Review by dafeda — APPROVED** [review]
Good stuff 👍

**Comment by BjarneHerland** [comment]
Thx. The files mentioned by @eivindjahren are actually deleted in b46927c1c3e1b55f54b0b5a0f72009b5fd6a0cf7, however I don't know how to ack the requested change in order to merge and push...  😬

**Comment by dafeda** [comment]
> Thx. The files mentioned by @eivindjahren are actually deleted in [b46927c](https://github.com/equinor/ert/commit/b46927c1c3e1b55f54b0b5a0f72009b5fd6a0cf7), however I don't know how to ack the requested change in order to merge and push... 😬

I did it for you, but here's how you can do it yourself:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/dismissing-a-pull-request-review

**Comment by BjarneHerland** [comment]
> I did it for you, but here's how you can do it yourself:

Thx again. Your google-foo is stronger than mine... 😅

**Pull request merged**
