### PR TITLE
Test ert on Python 3.10

### PR DESCRIPTION
**Pull request by sondreso**
**Issue**
Test ert with python 3.10

**Approach**

### CODE REVIEW

**Comment by dafeda** [comment]
What do the quotes around 3.10 do?
Asking because the other versions are without quotes...

**Comment by dafeda** [comment]
> Without the quote it is interpreted as a number and not a string, meaning 3.10 -> 3.1. Ideally I think all of them should be strings, so would change this before we should consider merging this 🙂

Ah I see, and agree that all should be strings before merge.
Thanks

**Review by dafeda — DISMISSED** [review]
LGTM 👍

**Comment by sondreso** [comment]
ecl now supports Python 3.10. But now this PR is blocked by missing scipy support for Python 3.10

**Comment by sondreso** [comment]
This is no longer blocked by scipy. Failures are now due to our incompatibilities with Python 3.10.

**Comment by oyvindeide** [comment]
Also consider adding: `"Programming Language :: Python :: 3.10",` to `setup.py` and perhaps also adding `python_requires=">=3.6"`

**Comment by sondreso** [comment]
Some test are failing. Created https://github.com/equinor/ert/issues/2555, so will close this for now.

**Pull request closed without merging**
