### PR TITLE
Fix restart for ensemble experiment

### LINKED ISSUE #8032: `Restart` experiment (or realization) from GUI does unexpected things
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Modify `poly_eval.py` such that some realizations fail:

```python
#!/usr/bin/env python3
import json
import random

def _load_coeffs(filename):
    with open(filename, encoding="utf-8") as f:
        return json.load(f)["COEFFS"]


def _evaluate(coeffs, x):
    return coeffs["a"] * x**2 + coeffs["b"] * x + coeffs["c"]


if __name__ == "__main__":
    if random.random() > 0.5:
        raise ValueError("Failed realization.")
    coeffs = _load_coeffs("parameters.json")
    output = [_evaluate(coeffs, x) for x in range(10)]
    with open("poly.out", "w", encoding="utf-8") as f:
        f.write("\n".join(map(str, output)))

```
3. Run `Ensemble experiment`
About 50% of realizations should fail:

image

4. Hit `Restart`
Notice that only the failed realizations remain:

image

**Expected behaviour**
I expect `Restart` to restart only the failed realizations and keep the successful ones (successful ones should still be visisble in the gui).

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by dafeda** [comment]
As far as I can tell, this does not fix the problem described in #8032 .
Or am I missing something?

**Comment by frode-aarstad** [comment]
> As far as I can tell, this does not fix the problem described in #8032 . Or am I missing something?

If the problem you are referring to is that you want the successful reals to also show up after you do a restart, I am not sure that is even possible to do without major refactoring

**Comment by dafeda** [comment]
> > As far as I can tell, this does not fix the problem described in #8032 . Or am I missing something?
> 
> If the problem you are referring to is that you want the successful reals to also show up after you do a restart, I am not sure that is even possible to do without major refactoring

That is what issue #8032 describes I guess, so I was checking whether this PR solves that.
Which part does this PR solve?

**Comment by frode-aarstad** [comment]
> > > As far as I can tell, this does not fix the problem described in #8032 . Or am I missing something?
> > 
> > 
> > If the problem you are referring to is that you want the successful reals to also show up after you do a restart, I am not sure that is even possible to do without major refactoring
> 
> That is what issue #8032 describes I guess, so I was checking whether this PR solves that. Which part does this PR solve?

It solves a bug that corrupts the active realizations selected after the second restart. Perhaps I can detatch this PR from the issue and put the parent issue back in todo

**Comment by dafeda** [comment]
> > > > As far as I can tell, this does not fix the problem described in #8032 . Or am I missing something?
> > > 
> > > 
> > > If the problem you are referring to is that you want the successful reals to also show up after you do a restart, I am not sure that is even possible to do without major refactoring
> > 
> > 
> > That is what issue #8032 describes I guess, so I was checking whether this PR solves that. Which part does this PR solve?
> 
> It solves a bug that corrupts the active realizations selected after the second restart. It also makes each restart run in the same ensemble/experiment. Perhaps I can detatch this PR from the issue and put the parent issue back in todo

I think that makes sense as the other issue is still unsolved and I think we do want it solved eventually.

**Review by dafeda — APPROVED** [review]

**Pull request merged**
