### PR TITLE
Remove unused parameter in add help to widget

### PR DESCRIPTION
**Pull request by yngve-sk**
**Issue**
Resolves #my_issue

**Approach**
_Short description of the approach_

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by oyvindeide** [comment]
Jenkins: test this please

**Comment by oyvindeide** [comment]
Is this still being worked on?

**Comment by oyvindeide** [comment]
Closing due to inactivity

**Pull request closed without merging**
