### PR TITLE
Add realizations to experiment manager

### LINKED ISSUE #7508: Add level to Ensemble manager tree view
Move the ensemble info to a new level in the Ensemble manager tree view. The new level is under the ensemble, which expands to show all the realizations. Clicking a realization will show the status of that realization in the details window.

### PR DESCRIPTION
**Pull request by aronhoyer**
**Issue**
Resolves #7508 

**Approach**

image

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by dafeda** [comment]
What's the ordering of the realizations?

**Comment by aronhoyer** [comment]
> What's the ordering of the realizations?

it's just default sorting (i take it it's just alphabetical)

**Comment by aronhoyer** [comment]
> > > What's the ordering of the realizations?
> > 
> > 
> > it's just default sorting (i take it it's just alphabetical)
> 
> Would it not be better to have it ordered by realization number? I don't think alphabetical makes sense here.

i'll look into how sorting is customized in qt :+1:

**Review by dafeda — APPROVED** [review]
Nicely done 👍

**Comment by oyvindeide** [comment]
Closing this PR and moved it to: https://github.com/equinor/ert/pull/7826, kept original author.

**Pull request closed without merging**
