### PR TITLE
Remove ext param

### PR DESCRIPTION
**Pull request by ManInFez**
## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by oyvindeide** [comment]
As this is only used in the `batch_simulator`, would it make sense to just move everthing there instead? And make that self contained?

**Comment by pinkwah** [comment]
Looks good to me although I'll withhold approval until Øyvind's question is resolved.

**Comment by ManInFez** [comment]
> As this is only used in the `batch_simulator`, would it make sense to just move everthing there instead? And make that self contained?

As this is a bit of a drastic change, I would prefer to do this first, then move it to everest

**Comment by ManInFez** [comment]
created an issue for it: https://github.com/orgs/equinor/projects/84/views/10

**Review by pinkwah — APPROVED** [review]

**Pull request merged**
