### PR TITLE
Mark empty stdout/stderr files in simulation

### LINKED ISSUE #996: Simulation details GUI, mark empty stdout/stderr files
Suggest to have a way of displaying which of these files are empty. Empty files are not so interesting to open
image

### PR DESCRIPTION
**Pull request by AugustoMagalhaes**
**Issue**
Resolves #996

**Approach**
Implements a feature to give a visual feedback of empty stdout/stderr files in the simulation panel, according to the following image:

image

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [x] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Review by eivindjahren — COMMENTED** [review]
Just fix the [style issues](https://github.com/equinor/ert/actions/runs/10142992583/job/28043449700?pr=8309) and this one should be ready to go :)

**Comment by AugustoMagalhaes** [comment]
@eivindjahren I had to update **tests/unit_tests/gui/simulation/test_run_dialog.py::test_that_run_dialog_can_be_closed_while_file_plot_is_open** due to the fact that poly case will not be able to open the FileDialog anymore, since its stdout and stderr files are both empty, so I've changed to the snake_oil case with the original purpose

**Review by eivindjahren — APPROVED** [review]
Looks really good! Thanks for the contribution! Especially nice to get some of these older "sticky" issues closed :grin:

**Comment by AugustoMagalhaes** [comment]
> Looks really good! Thanks for the contribution! Especially nice to get some of these older "sticky" issues closed 😁

You are welcome, it has been a good experience too :wink:

**Pull request merged**
