### PR TITLE
Corrected spelling to ERT in the README for consistency

### PR DESCRIPTION
**Pull request by alin256**
Not much, just consistency. The last section seemed to have a different spelling.

### CODE REVIEW

**Comment by oyvindeide** [comment]
Hi @alin256 and thanks for your contribution! :smile:

**Review by oyvindeide — APPROVED** [review]

**Comment by oyvindeide** [comment]
Jenkins: test required please

**Comment by oyvindeide** [comment]
I see that the style test is failing, it is not directly related to your, but think it will be fixed by fetching again and rebasing on main.

**Comment by alin256** [comment]
@oyvindeide do you want me to fix it?

**Comment by oyvindeide** [comment]
> @oyvindeide do you want me to fix it?

That would be great, should be enough with  a rebase and a force push :smile: Let me know if you need any help

**Comment by alin256** [comment]
@oyvindeide, does it work now?

**Comment by oyvindeide** [comment]
Yes, everything seems to work now, thanks for your patience 😊 Just one more test that needs to run: Jenkins: test required please

**Pull request merged**
