### PR TITLE
Verify if active realizations is less than minimum set

### LINKED ISSUE #3727: Warn user instead of error after run when active realisations < MIN_REALIZATIONS
**Describe the bug**

If the user specifies a set of realizations that is smaller than `MIN_REALIZATIONS` in the config file, all forward models can succeed and still ert will produce a failure. Ert has enough information before running that this will fail.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Make sure `MIN_REALIZATIONS` > 1
3. `ert gui my_config.ert`
4. Run experiment and specify single realization

**Expected behaviour**
A warning that user has specified less than `MIN_REALIZATIONS` from config and have them either specify more realizations or change `MIN_REALIZATIONS`.

**Environment**
 - OS: [e.g. RHEL7]: all
 - ERT/Komodo release: main
 - Python version: all
 - Remote/HPC execution involved: [N/A] (valid for both)

**Other**
https://github.com/equinor/ert/pull/3426
This PR changed the behaviour, as ert used to take the minimum between chosen realizations and `MIN_REALIZATIONS`. This issue proposes that the change should stay, but we can stop users from running an experiment that ultimately will fail.

### PR DESCRIPTION
**Pull request by andreas-el**
**Issue**
Resolves #3727 

**Approach**
_Short description of the approach_

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Updated documentation
- [x] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by oysteoh** [comment]
Seems to work as expected, but I wonder if the message could be slightly different... :thinking: At least I suggest an alternative and then we can discuss... 
Instead of 
`Number of active realizations is less than the specified MIN_REALIZATIONS in the config file: 6 < 10`
would this look nicer? 
`Number of active realizations ( 6 ) is less than the specified MIN_REALIZATIONS in the config file ( 10 )`

**Comment by andreas-el** [comment]
> Seems to work as expected, but I wonder if the message could be slightly different... 🤔 At least I suggest an alternative and then we can discuss... Instead of `Number of active realizations is less than the specified MIN_REALIZATIONS in the config file: 6 < 10` would this look nicer? `Number of active realizations ( 6 ) is less than the specified MIN_REALIZATIONS in the config file ( 10 )`

Sure thing. I picked that message since it was already present in the repo for this specific problem. The problem was that it was raised *after* execution.

**Comment by oysteoh** [comment]
> > Seems to work as expected, but I wonder if the message could be slightly different... thinking At least I suggest an alternative and then we can discuss... Instead of `Number of active realizations is less than the specified MIN_REALIZATIONS in the config file: 6 < 10` would this look nicer? `Number of active realizations ( 6 ) is less than the specified MIN_REALIZATIONS in the config file ( 10 )`
> 
> Sure thing. I picked that message since it was already present in the repo for this specific problem. The problem was that it was raised _after_ execution.

But please just suggest other ways of writing it as well - or just disregard my comment if not agree. I just thought it looked a bit silly with the `: 6 < 10` statement  .. :smile:

**Comment by andreas-el** [comment]
> > > Seems to work as expected, but I wonder if the message could be slightly different... thinking At least I suggest an alternative and then we can discuss... Instead of `Number of active realizations is less than the specified MIN_REALIZATIONS in the config file: 6 < 10` would this look nicer? `Number of active realizations ( 6 ) is less than the specified MIN_REALIZATIONS in the config file ( 10 )`
> > 
> > 
> > Sure thing. I picked that message since it was already present in the repo for this specific problem. The problem was that it was raised _after_ execution.
> 
> But please just suggest other ways of writing it as well - or just disregard my comment if not agree. I just thought it looked a bit silly with the `: 6 < 10` statement .. smile

I have absolutely no objections to this. Already changed the PR to this proposal. :+1:

**Review by oysteoh — APPROVED** [review]

**Comment by andreas-el** [comment]
Jenkins test this please!

**Pull request merged**
