### PR TITLE
Update StorageClient url to reflect http_server

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
**Issue**
baseurl was explicitly set in https://github.com/equinor/ert/commit/a3c4ca57e2e633c5d968db25086baa8d50c11194

**Approach**
Reflect the change in `StorageClient` as well.

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
hang on, must fix last number :P

**Comment by sondreso** [comment]
I don't think this change is needed, does it work without it?

**Comment by lars-petter-hauge** [comment]
Must have made a booboo when testing I suppose. Doesn't make a difference no.

Does it make sense to have `0.0.0.0` stated in one place and `127.0.0.1` in the other?

I have little knowlegde of this topic, but I don't know which one would fit more. https://www.howtogeek.com/225487/what-is-the-difference-between-127.0.0.1-and-0.0.0.0/

The `0.0.0.0` can supposedly mean "anything" and is

> basicaly the ‘no particular address’ placeholder.

I'm fine closing this PR though, and I'll fix my other PR's that depends on it.

**Comment by sondreso** [comment]
For future reference: 0.0.0.0 tells flask to bind such that the server is also available to other computers on the network, while explicitly saying 127.0.0.1 means only available locally. In both cases you can reach the server on 127.0.0.1 locally :slightly_smiling_face:

**Pull request closed without merging**
