### PR TITLE
Add validation for FIELD parameter name

### LINKED ISSUE #6070: Detect long parameter names in FIELD when validating config
If you have a FIELD parameter line in the config like:
`FIELD FIELDPARAM PARAMETER fieldparam.grdecl INIT_FILES:fieldparam.grdecl  FORWARD_INIT:True
`
your simulations will go through an ensemble experiment, but fail when internalizing the data with the error message:
```
Simulations failed with the following error: Simulation failed!
Realization: 0 failed after reaching max submit with: Cannot import FIELDPARAM, not present in file /tmp/poly_example/poly_out/realization-0/iter-0/fieldparam.grdecl?
Simulation failed!
```

The problem is the length of the string `FIELDPARAM` , it must be 8 chars or less. This can be detected while validating the config.

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #6070 

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by dafeda** [comment]
Do you know what the reasoning is behind this limit of 8 characters?

**Comment by frode-aarstad** [comment]
> Do you know what the reasoning is behind this limit of 8 characters?

No, perhaps @berland knows..

**Comment by berland** [comment]
I suppose this parameter is meant to be exported as an Eclipse keyword. Eclipse limits keywords to 8 chars.

**Comment by dafeda** [comment]
> I suppose this parameter is meant to be exported as an Eclipse keyword. Eclipse limits keywords to 8 chars.

Thanks, if that's the case we could add a small comment somewhere.

**Review by dafeda — APPROVED** [review]
Suggest we add a comment where we raise error that the requirement is due to Eclipse.

**Comment by frode-aarstad** [comment]
> Suggest we add a comment where we raise error that the requirement is due to Eclipse.

I will add a comment to the exception and in the documentation

**Pull request merged**
