### PR TITLE
Remove unused class History

### PR DESCRIPTION
**Pull request by oyvindeide**
**Issue**
Drive by cleaning while working on seperate issue.

## Pre review checklist

- [x] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Comment by oyvindeide** [comment]
test this please

**Comment by oyvindeide** [comment]
test this please

**Comment by oyvindeide** [comment]
test ert please

**Comment by oyvindeide** [comment]
test this please

**Comment by ManInFez** [comment]
Are you sure history observations are never used?

**Comment by oyvindeide** [comment]
> Are you sure history observations are never used?

History observations are used, but this is not that. The only bit of production code that is actually being deleted is this:

```
    @staticmethod
    def get_source_string(history_source_type: HistorySourceEnum):
        """
        @type history_source_type: HistorySourceEnum
        @rtype: str
        """
        return History._get_source_string(history_source_type)
```

**Pull request merged**
