### PR TITLE
Refactor analysis smoother update

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Review by pinkwah — APPROVED** [review]
Rakett

**Comment by oyvindeide** [comment]
Looks good to me as well, but could you remove ` - rebased successfully`  from the PR title? It goes into the release notes, so then we wont have to remove it later.

**Review by dafeda — APPROVED** [review]
Real nice 👍

**Comment by ManInFez** [comment]
test ert please!

**Comment by ManInFez** [comment]
test ert please!

**Pull request merged**
