### PR TITLE
Ensure communication pipe file descriptor is closed

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves  ~#3639 and~ #3677 

**Approach**
Close it.

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Review by lars-petter-hauge — APPROVED** [review]
Thanks for fixing!

**Comment by xjules** [comment]
We (@lars-petter-hauge) still need to confirm that #3639 is caused by this since currently it looks more like having a huge discrepancy in running time for the actual test function; ranging from `7secs` to like `28secs`. This means just increasing timeout should fix it.

**Comment by lars-petter-hauge** [comment]
Yes, we can remove resolving #3639. We ran main without timeout on the test failing in said issue and then it didn't fail on 100 runs. See also https://github.com/equinor/ert/issues/3639#issuecomment-1202702874 for timings observed during running.

**Comment by berland** [comment]
Tried asserting file descriptors are closed by wrapping the test with the context manager:

```
class AssertNoFileDescriptorLeaks:
    def __init__(self):
        self.fd_dir: Path = Path("/proc/") / str(os.getpid()) / "fd"

    def __enter__(self):
        self.fd_count_at_init = len(list(self.fd_dir.glob("*")))
        return self

    def __exit__(self, type, value, traceback):
        fd_count_now = len(list(self.fd_dir.glob("*")))
        print(f"fd count before: {self.fd_count_at_init}, now: {fd_count_now}\n")
        assert fd_count_now == self.fd_count_at_init
```

but this reveals no change with or without the commit in this PR that closes `fd_read`.

**Comment by berland** [comment]
Keep closed until further investigations finds that this is really an issue.

**Pull request closed without merging**
