### PR TITLE
Removed Free method in ResConfig (src/ert/_c_wrappers/enkf/res_config.py)

### LINKED ISSUE #4259: Remove free method from ResConfig

### PR DESCRIPTION
**Pull request by chandansgowda**
**Issue**
Resolves #4259

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Review by valentin-krasontovitsch — APPROVED** [review]
looks good, thanks for the patch!

**Comment by valentin-krasontovitsch** [comment]
jenkins, test this please

**Comment by oyvindeide** [comment]
Jenkins: test this please

**Comment by valentin-krasontovitsch** [comment]
merged, thanks again for your contribution, @chandansgowda!

**Pull request merged**
