### PR TITLE
Update queue branch from main

### PR DESCRIPTION
**Pull request by xjules**
Major update from main

### CODE REVIEW

**Comment by berland** [comment]
No conflicts? Let's roll!

**Review by berland — APPROVED** [review]

**Comment by xjules** [comment]
> No conflicts? Let's roll!

Yes, no conflicts, but I would like to see a few tests passing at least :)

**Comment by berland** [comment]
> > No conflicts? Let's roll!
> 
> Yes, no conflicts, but I would like to see a few tests passing at least :)

It wasn't passing before either, so that is no reason to hold off a main-update.

**Comment by xjules** [comment]
> > > No conflicts? Let's roll!
> > 
> > 
> > Yes, no conflicts, but I would like to see a few tests passing at least :)
> 
> It wasn't passing before either, so that is no reason to hold off a main-update.

I think github has some issue as now it finally approved that there are conflicts :smile:

**Comment by kwinkunks** [comment]
@xjules Seems green again now?

**Comment by xjules** [comment]
Closing this one as we now upgrade main with cherry-picks of the feature branch.

**Pull request closed without merging**
