### PR TITLE
Add plot for observations

### LINKED ISSUE #7509: Add observation summary when clicking an ensemble in Experiment manager
When clicking an ensemble in the Experiment manager, we would like to show a summary of the loaded observations, and their coverage, for example like:

Image

Image

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #7509

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by frode-aarstad** [comment]
bilde

**Comment by dafeda** [comment]
Not sure I understand the plot.
From my understanding, there is only one observation and one or more responses.
What does the left-hand side plot show?

**Comment by frode-aarstad** [comment]
> Not sure I understand the plot. From my understanding, there is only one observation and one or more responses. What does the left-hand side plot show?

The left column is the observation, now we plot one for each realization but we should only plot one. The right is the responses one for each realization. So in the above image there are 25 responses.

**Comment by dafeda** [comment]
> > Not sure I understand the plot. From my understanding, there is only one observation and one or more responses. What does the left-hand side plot show?
> 
> The left column is the observation, now we plot one for each realization but we should only plot one. The right is the responses one for each realization. So in the above image there are 25 responses.

Yes, only plot one and add error-bars right?

**Comment by frode-aarstad** [comment]
Now left column is observation with +-std dev
image

**Comment by dafeda** [comment]
> Now left column is observation with +-std dev image

image

A box plot consists of these elements.
What does the blue box signify when we only have one observation?
I think we may want to just show an errorbar for the observation.

**Comment by frode-aarstad** [comment]
image

**Pull request merged**
