### PR TITLE
Fix bug when restarting es_mda from iter>0

### LINKED ISSUE #1946: Restarting ES_MDA from an iteration causes a crash
**Describe the bug**
When you attempt to restart ESMDA from an iteration it will crash with the following error message:

```
Traceback (most recent call last):
  File "/prog/res/komodo/2021.08.rc0-py36-rhel7/root/lib64/python3.6/site-packages/ert_gui/model/progress_proxy.py", line 99, in _source_data_changed
    if top_left.internalPointer().type != NodeType.ITER:
AttributeError: 'NoneType' object has no attribute 'type'
```

**To Reproduce**
1. `ert gui poly.ert'
2. Run ESMDA using standard settings, and wait for it to complete
3. Restart ESMDA from `default_2` according to the description here: https://ert.readthedocs.io/en/latest/getting_started/gui/gui.html#restarting-es-mda
4. After clicking start ERT will crash and the error message above will appear. 

**Expected behavior**
No crash

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: 2021.08.rc0-py36
 - Python version: 3.6
 - Remote/HPC execution involved: no

### PR DESCRIPTION
**Pull request by ManInFez**
**Issue**
Resolves #1946

Separate the usage of row of model-index and iteration number.

### CODE REVIEW

**Review by sondreso — APPROVED** [review]
LGTM :ship:

**Comment by ManInFez** [comment]
Test this please!

**Comment by jondequinor** [comment]
Could you add a unit test for this case?

**Comment by ManInFez** [comment]
> Could you add a unit test for this case?

I vote for getting the fix in and I am making an issue to create a test for this :)

**Comment by ManInFez** [comment]
issue for creating test https://github.com/equinor/ert/issues/1948

**Pull request merged**
