### PR TITLE
Use the prefect context to pass url,token and certification info

### LINKED ISSUE #1588: Use prefect context to pass global information to tasks
Prefect has a concept of [context](https://docs.prefect.io/core/concepts/execution.html#context) that we should utilise to share information that all tasks will need, instead of passing them as arguments to the tasks (or directly to the run function). Specifically the url, token and certificate for the evaluation server is information that should be propagated this way.

### PR DESCRIPTION
**Pull request by verveerpj**
**Issue**
Resolves #1588 

**Approach**
Remove the url, token and certification passed to the flow code, and put them in the prefect context. Adapt the tests accordingly.

### CODE REVIEW

**Comment by jondequinor** [comment]
This is cool. Quick question while it is in draft, did you learn anything about context while doing this work? What are the benefits over the explicit passing of arguments to a constructor?

One of the reasons why this issue was created, was because it was smelly that the steps knew about certs and tokens.

**Comment by verveerpj** [comment]
> This is cool. Quick question while it is in draft, did you learn anything about context while doing this work? What are the benefits over the explicit passing of arguments to a constructor?
> 
> One of the reasons why this issue was created, was because it was smelly that the steps knew about certs and tokens. Also, we wanted to learn about contexts.

Initially I was wondering what this issue was needed for, why not just use the constructor of the tasks, right? I just went ahead, and I noticed the code cleaned up very nicely. The url/certs/tokens are kind of orthogonal from the workflow logic, so it its very nice to have them separated by passing them once via a context. Then they become 'globally' available to all the flow-related code, but since it is a context, its still localized nicely.

I think this context should be used with respect though: it is tempting just to throw the context around a big chunk of code, which basically means creating global variables. It should be localized to the code that runs the flow, and it should only contain variables that really are 'context', not intrinsically part of the code the flow runs. The ensemble id is a case where you could have it done one or the other way, but I left it as an argument, since I felt that was intrinsically part of the job that the workflow was doing, whereas a the url/cert/tokens are part of a supporting mechanism. One could discuss about that though.

**Comment by jondequinor** [comment]
Thanks @verveerpj! That's informative and reasonable.

**Review by sondreso — APPROVED** [review]
Nice! 👏

**Pull request merged**
