### PR TITLE
Include last report step in HISTORY_OBSERVATION

### LINKED ISSUE #1820: HISTORY_OBSERVATION does not load the last entry in the summary vector
**Describe the bug**
When loading SUMMARY_OBSERVATIONS the last data point in the summary vector is not loaded, and becomes `nan`.
The responses are loaded for the last time step, indicating that this is not an intended feature.

**To Reproduce**
Add this to: `tests/data/test_integration_data.py`
```python
@pytest.mark.usefixtures("copy_snake_oil")
def test_summary_collector():
    res_config = ResConfig("snake_oil.ert")
    ert = EnKFMain(res_config)
    summary = EclSum("refcase/SNAKE_OIL_FIELD.UNSMRY")
    data = SummaryObservationCollector.loadObservationData(ert, "default_0")

    assert (
        data["FOPR"].values.tolist()
        == summary.numpy_vector("FOPRH", report_only=True).tolist()
    )
```

**Expected behavior**
Expect that test to pass and that the internal `ert` data is the same as the refcase summary vector.

### PR DESCRIPTION
**Pull request by oyvindeide**
**Issue**
When reading HISTORY_OBSERVATIONS, the last entry in the summary file is not loaded by ert.

Closes #1820

### CODE REVIEW

**Comment by oyvindeide** [comment]
Related to: #1820

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Review by markusdregi — APPROVED** [review]
💯

**Comment by markusdregi** [comment]
Jenkins: Add to whitelist

**Comment by markusdregi** [comment]
Jenkins: Test this please

**Comment by oyvindeide** [comment]
test this please

**Comment by oyvindeide** [comment]
test this please

**Comment by oyvindeide** [comment]
Jenkins is failing on a C-test, I was able to replicate it locally, but will hold off on merging until I figure it out.

**Comment by oyvindeide** [comment]
Tracked it down to one of the tests running on internal data (https://github.com/equinor/ert/blob/6ba64458edccf430826235297b9868a489cedb7e/libres/lib/enkf/tests/enkf_obs_fs.cpp#L55). Must be reproduced on a system with access to the internal data. I _suspect_ that the matrix was created by running the script originally, and the comparison is wrong. But have not confirmed that.

**Comment by sondreso** [comment]
>  Must be reproduced on a system with access to the internal data. I suspect that the matrix was created by running the script originally, and the comparison is wrong. But have not confirmed that. To run the internal tests, link to the internal data and set up a correct site config.

I think the above suspicions are correct. I ran the tests with the internal test data, and the matrix comparison fails since the matrixes are no longer of the same size.

**Comment by sondreso** [comment]
So this all comes down to faulty expected test data. Since we now load one more data point for `HISTORY_OBSERVATIONS`, the S-matrix (`S`) changes since (13 extra rows, corresponding to the 13 extra data points loaded). This means that the expected matrix read from disk (`S0`) , no longer matches the `S` matrix exactly. The way I see it we have three options: 

1. Since the extra data points only causes _extra_ rows to be added, we can remove these rows when comparing to `S0`. This is demonstrated in the last commit in this PR. Since this only circumvents the problem and reduces the validity of the test, I don't think we should go for this option. 
2. Rewrite the test to use synthetic data instead, and remove the now test using internal data. The problem with this approach is that the test case at hand is quite complex, and it might not be feasible to create a realistic test case with synthetic data that covers the same set of features that the current test does. 
3. Update the internal test data with a new `S0`, such that the expected matrix `S0` once again matchs the computed `S`. The only hurdle with this approach is the limited number of people with write access to the internal test data. We must also remember to update the test data both in Bergen and Stavanger. 

I recommend going for option 3, and will therefore put this on hold until people with write access to internal test-data is available. I have prepared a file that replaces the outdated S-matrix, so contact me if you pick this up again.

**Comment by oyvindeide** [comment]
> 
>     2. Rewrite the test to use synthetic data instead, and remove the dependency on the internal data. The problem with this approach is that the test case at hand is quite complex, and it might not be feasible to create a realistic test case with synthetic data that covers the same set of features that the current test does.

While we dont test the C functions directly at that low level, there are now tests with synthetic data checking that the correct data is loaded without using internal data. If that is something we can live with, I am a bit in favor of deleting the internal data (with the caveat that it is not used by other tests) and just relying on open data.

>     3. Update the internal test data with a new `S0`, such that the expected matrix `S0` once again matches the computed `S`. The only hurdle with this approach is the limited number of people with write access to the internal test data. We must also remember to update the test data both in Bergen and Stavanger.
> 
> 
> I recommend going for option 3, and will therefore put this on hold until people with write access to internal test-data is available. I have prepared a file that replaces the outdated S-matrix, so contact me if you pick this up again.

I dont disagree with this option, but it could have other knock on effects if any other test is relying on that data, though it being wrong for eternity is not a good option either. I must say I am in favor of deleting the internal data for this case (as that is something we want to do anyway), and if needed add more integration tests that are more controlled and transparent.

**Comment by sondreso** [comment]
I guess I (unintentionally) left out the 4th option which is just delete the test. I think this is a good option, but what makes me a little nervous is that the failing test seems to test a bit more than just the size of the matrix (e.g. active mask). 

> [...] if any other test is relying on that data, [...]

There are at least not any in this repository, all the tests pass with the updated file.

**Comment by oyvindeide** [comment]
> I guess I (unintentionally) left out the 4th option which is just delete the test. I think this is a good option, but what makes me a little nervous is that the failing test seems to test a bit more than just the size of the matrix (e.g. active mask).
> 

This should cover the part of that test that tests the active mask without using any test data:

```cpp
void test_obs_mask_deactivate() {

  obs_data_type * obs_data = obs_data_alloc(1.0);
  obs_block_type * obs_block = obs_data_add_block(obs_data , "OBS", 2 , NULL , false);

  for (int iobs = 0; iobs < 2; iobs++)
    obs_block_iset(obs_block , iobs , iobs , 0.1);

  /* Check that the mask is all true:*/
  const bool_vector_type * pre_deactivate_mask = obs_data_get_active_mask(obs_data);
  test_assert_true( bool_vector_iget(pre_deactivate_mask, 0) );
  test_assert_true( bool_vector_iget(pre_deactivate_mask, 1) );

  /* Check that the we can deactivate a single block in the mask:*/
  obs_block_type * block = obs_data_iget_block(obs_data , 0);
  obs_block_deactivate(block , 0 , false , "---");
  const bool_vector_type * mask = obs_data_get_active_mask(obs_data);
  test_assert_false(bool_vector_iget(mask, 0));
  test_assert_true(bool_vector_iget(mask, 1));
  obs_data_free(obs_data);
}

``` 

> > [...] if any other test is relying on that data, [...]
> 
> There are at least not any in this repository, all the tests pass with the updated file.

Thats good, then I vote for deleting the test data and this test.

**Comment by oyvindeide** [comment]
Jenkins error seems to be unrelated: `/usr/bin/xvfb-run: line x: x Segmentation fault      (core dumped)`

**Review by sondreso — APPROVED** [review]
Nice :clap:

**Pull request merged**
