### PR TITLE
Use setuptools.Extension rather than CMake

### PR DESCRIPTION
**Pull request by dotfloat**
We're currently using CMake for building libres. Since we only support a single configuration for CMake, it's easier to use setuptools' `Extension` mechanism (it's actually distutils).

---

- Setuptools only supports a single `extra_compile_args` that applies to all languages. This means that it attempts to compile C code while applying our C++ standards flag, which is nonsensical. As such, it is necessary to convert all C code to C++ compatible code.
- As such, I found that analysis modules are relying on undefined behaviour (https://github.com/equinor/ert/issues/1821)
- We only use LAPACK (and I think BLAS transitively?). In macOS, this is already installed in `Accelerate.framework`. On Linux we could use `pkg-config` to discover these, but RHEL's `lapack-devel` doesn't ship with a `pkg-config` `lapack.pc`. I decided not to overcomplicate things and just assume that `lapack` exists somewhere in the users environment. It is possible to specify the location of `lapack` via environment variables, and we can add this to the `README`.
- The external analysis modules has proven to be a problem, as it's exceedingly difficult to use in a Python package. I think we should kill that code entirely and rely entirely on internal modules. `RML_ENKF` is internal now, but I wrote code that pretends it's an external library, which is an awful hack. If anyone is using it, they would make a peep and we can actually implement it in a way that makes sense.
- I haven't looked at how to have the testing code work yet. My current plan is to use pytest, and compile the binaries for each test. This could lead to annoyingly long compile times. We could have a pytest fixture that uses some `/tmp` directory for storing `.o` files, and compare timestamps. If the `.cpp` file is newer, recompile.

---

- Moved all C tests into `libres/lib_tests`. This allows us to simply glob after `*.cpp` in `lib` and include all the C++ sources.
- Created a new `CMakeLists.txt` in `libres/lib_tests`. For [boring CMake reasons](https://cmake.org/cmake/help/latest/policy/CMP0079.html), I also had to bump the minimum CMake version to 3.13. This should be fine even if I don't manage to remove CMake in this PR.
- Made `enkf_main_ensemble.cpp` and `enkf_main_manage_fs.cpp` into standalone compilation units. Previously they were `#include`d into `enkf_main.cpp` which is, frankly, madness. The easiest way to accomplish this was to move the definition of `enkf_main_type` into `enkf_main.h`. This is fine because hiding the type accomplishes nothing but forcing us to write getters for everything.

### CODE REVIEW

**Comment by jondequinor** [comment]
@markusdregi how would we proceed to discover use of the external analysis lib feature? Ask Eivind?

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by markusdregi** [comment]
I have ran this by @eivindsm and we have a go on dropping the possibility of linking external analysis modules :free

**Comment by dotfloat** [comment]
Closing due to `setuptools.Extension` not being a good alternative.

Will rewrite `CMakeLists.txt` to behave better instead.

**Pull request closed without merging**
