### PR TITLE
Improve codecov coverage lsf_driver polling and using bhist

### PR DESCRIPTION
**Pull request by jonathan-eq**
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by berland** [comment]
The way I read the existing test code, it _should_ trigger the fallback, but if it does not there might be something wrong with it?

**Comment by xjules** [comment]
It seems that there are still some lines not covered: https://app.codecov.io/gh/equinor/ert/commit/20c62b6965d97318990927be49eeec3acedb4da2/blob/src/ert/scheduler/lsf_driver.py

**Comment by berland** [comment]
So the changes in this commit only serves to verify that the test works as intended? (since bjobs is non-functional, the intention was that the poll function would not work unless bhist is actually working)

**Comment by jonathan-eq** [comment]
> So the changes in this commit only serves to verify that the test works as intended? (since bjobs is non-functional, the intention was that the poll function would not work unless bhist is actually working)

Yes. Maybe the more explicit asserts will have codecov not flag the code as untested.

**Comment by berland** [comment]
> Yes. Maybe the more explicit asserts will have codecov not flag the code as untested.

That would be surprising..

**Pull request merged**
