### PR TITLE
Add test for memory usage on smoother

### LINKED ISSUE #5064: Create memory regression tests for ensemble smoother

### PR DESCRIPTION
**Pull request by JHolba**
**Issue**
Resolves #5064 

**Approach**
Added pytest-memray for measuring peak memory usage.
Wrote code to generate synthetic data for the testing.

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [x] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by dafeda** [comment]
Great stuff 👍 

If not a bunch of extra work, would you mind testing this on my branch that reduces memory usage?

https://github.com/equinor/ert/pull/5050

**Comment by dafeda** [comment]
Great if you add `pytest-memray` to `dev-requirements.txt`.

**Comment by dafeda** [comment]
Commit message almost according to guidelines - it needs to be capitalized 😬

**Comment by JHolba** [comment]
added pytest-memray and fixed commit message

**Review by dafeda — APPROVED** [review]
Nice 👍

**Pull request merged**
