### PR TITLE
Add tox and pre-commit to test suite

### PR DESCRIPTION
**Pull request by oyvindeide**
Running black on a partially blacked repo is a bit tiresome, this makes that process easier by incorporating it in `pre-commit` which filters out non blacked files.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by jondequinor** [comment]
Why remove the test?

**Comment by oyvindeide** [comment]
> Why remove the test?

Because black isnt really supposed to be a `test` it is a command line tool, so here I change it so that it is run from the command line - and a failure will make the test suite fail.

The behavior is the same

**Comment by oyvindeide** [comment]
By the way @jondequinor, do you have any idea why the tests are failing? You have been dealing with this stuff before

**Comment by jondequinor** [comment]
> By the way @jondequinor, do you have any idea why the tests are failing? You have been dealing with this stuff before

Maybe add `libfontconfig`?

**Comment by oyvindeide** [comment]
Closing this as it does the `gui` tests are segfaulting for some reason. Could not replicate locally.

**Pull request closed without merging**
