### PR TITLE
Edit the case prompt for es mda

### LINKED ISSUE #6572: Prompt dialog does not make sense for ES MDA
**Describe the bug**
When running ES MDA from start you get a question about initializing the ensamble from a case, based on the current case in the restart from panel regardless of whether or not the restart run box is ticked.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. `ert gui my_config.ert`
3. Create a new case. 
4. Press Run Experiment in ES MDA panel.

**Expected behaviour**
The question box should only appear in its current form when you actually run a restart run. 

**Screenshots**
image

**Environment**
 - OS: [e.g. RHEL7]
 - ERT/Komodo release: [e.g. 2.18 or 2020.12.00]
 - Python version
 - Remote/HPC execution involved: [yes|no]

**Additional context**

### PR DESCRIPTION
**Pull request by larsevj**
**Issue**
Resolves #6572 

## Pre review checklist

- [x] Read through the code changes carefully after finishing work
- [x] Make sure tests pass locally (after every commit!)
- [x] Prepare changes in small commits for more convenient review (optional)
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [x] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by larsevj** [comment]
Proposed change for ES MDA:
image
image

**Comment by larsevj** [comment]
This would at least make the ES MDA panel more correct in terms of the actual underlying behaviour, but a general solution will probably be introduced when the "cases" are removed altogether? There is still some weird behaviour in the panel, such as the target case format not being autofilled if you have first modified the field yourself.

**Review by dafeda — APPROVED** [review]
Nice catch 👍 
@oyvindeide  might want to have a look as well as we he is the restart-expert.

**Review by andreas-el — APPROVED** [review]
Good job! Only need to fix style and let this one fly! ✈️

**Pull request merged**
