### PR TITLE
Turn on gui tests for mac

### PR DESCRIPTION
**Pull request by dafeda**
## Pre review checklist

- [x] Read through the code changes carefully after finishing work
- [x] Make sure tests pass locally (after every commit!)
- [x] Prepare changes in small commits for more convenient review (optional)
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by eivindjahren — APPROVED** [review]
:+1:

**Review by eivindjahren — CHANGES_REQUESTED** [review]
Thing is, we need to build all versions of python for mac

**Comment by dafeda** [comment]
> Thing is, we need to build with all versions of python for mac. If we don't, then some down stream workflows will stop working because of lacking wheels.

I see, was not aware.
Is it OK if I just test using Python 3.10 to save time you think?

**Review by eivindjahren — APPROVED** [review]
:+1:

**Review by sondreso — APPROVED** [review]

**Pull request merged**
