### PR TITLE
Keep tracker iteration snapshot up to date

### LINKED ISSUE #1608: Total progress calculation is wrong when using ensemble evaluator
Progress from finished realisation is not counted in the progress bar.

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #1608

### CODE REVIEW

**Review by jondequinor — APPROVED** [review]
Excellent catch.

**Comment by DanSava** [comment]
Why did you merge it ?

**Comment by markusdregi** [comment]
Tip: Labeling a PR as a draft prevents your collaborators from accepting and merging PR's ;)

I hope you still come with the test in a separate PR then!

**Comment by DanSava** [comment]
> Tip: Labeling a PR as a draft prevents your collaborators from accepting and merging PR's ;)

Good tip!

> I hope you still come with the test in a separate PR then!

Yep: https://github.com/equinor/ert/pull/1629

**Comment by jondequinor** [comment]
Sorry for merging without tests.

**Pull request merged**
