### PR TITLE
Reorganize ensemble modules into ensemble package

### PR DESCRIPTION
**Pull request by jondequinor**
Preparatory refactor to ease resolving #1717 

Summary of changes

```
 cd ert_shared/ensemble_evaluator/
 git mv entity/ensemble.py ensemble/builder.py
 git mv entity/ensemble_base.py ensemble/base.py
 git mv entity/ensemble_legacy.py ensemble/legacy.py
 git mv prefect_ensemble.py ensemble/prefect.py
```

Then change all imports that were broken.

### CODE REVIEW

**Comment by jondequinor** [comment]
snyk failure must be spurious

**Comment by sregales-TNO** [comment]
Can you rerun the failing tests?

**Comment by jondequinor** [comment]
No, and it doesn't apply. I have not changed packaging, and this passes elsewhere.

**Review by frode-aarstad — APPROVED** [review]
LGTM

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Pull request merged**
