### PR TITLE
Fix restart weights

### LINKED ISSUE #8491: Weights can be modified on ES MDA restart
### What happened? (You can include a screenshot if it helps explain)

Currently there is nothing stopping you from changing the weights when doing a restart of an ES MDA experiment. Since the weights are normalized for each run this might lead to the overall weights used in the normal run + restart run do not have reciprocal sum of 1 as they should. You are currently also able to add new weights on a restart. 

### What did you expect to happen?

The weights should be locked after you have run an es mda run for an experiment.
Relates to https://github.com/equinor/ert/issues/8447

### steps to reproduce

```Python
ert gui poly.ert
run es_mda with default weights
Click restart run and change weights
```

### Environment where bug has been observed

- [X] python 3.8
- [X] python 3.9
- [X] python 3.10
- [X] python 3.11
- [X] python 3.12
- [X] macosx
- [X] rhel7
- [X] rhel8
- [X] local queue
- [X] lsf queue
- [X] slurm queue
- [X] openPBS queue
- [ ] used flag `--enable-scheduler`

### PR DESCRIPTION
**Pull request by andreas-el**
Will add tests when implementation is approved

**Issue**
Resolves #8491 

https://github.com/user-attachments/assets/d448ac8e-b735-43d2-9d69-9470aa61bf12

```
(dev-ert) ➜  33344772-5472-418d-82f2-68eda6eb39af git:(fix_restart_weights) ✗ cat metadata.json
{"weights": "5, 3, 2"}%
```

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by eivindjahren** [comment]
Looks good, but I would like to double check with @dafeda about this change :)

**Comment by dafeda** [comment]
> Looks good, but I would like to double check with @dafeda about this change :)

This makes good sense to me 👍

**Review by eivindjahren — APPROVED** [review]
:+1:

**Review by eivindjahren — APPROVED** [review]
:+1:

**Pull request merged**
