### PR TITLE
Add selection to the file dialog

### LINKED ISSUE #1104: Not possible to select text by mouse in stderr/stdout viewer
RHEL7, user is not able to select text by mouse (f.ex. copying a filepath). Nothing happens when mouse is clicked-dragged.

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #1104 

**Approach**
Change the file dialog to use QPlainTextEdit for the view instead of a custom view. QPlainTextEdit has selection for free so we dont have to implement it ourself.

### CODE REVIEW

**Comment by sondreso** [comment]
@dotfloat was there some performance issues behind the choice of using the custom view in the first place?

**Comment by dotfloat** [comment]
Yeah, so we tried to use `QPlainTextEdit` in the first place, but it was unusable for particularly large text files. Test it with >1000 lines with adding a line every few hundred ms. Last I checked, the implementation does a `O(n)` operation every time a new line is added.

**Comment by frode-aarstad** [comment]
I am not able to reproduce the slowness. I tried with a 10Mb file (100k lines) and adding a new to it every 0.1s. Seems fine

**Comment by jondequinor** [comment]
Even in follow mode?

**Comment by frode-aarstad** [comment]
> 
> 
> Even in follow mode?

yes

**Comment by frode-aarstad** [comment]
> 
> 
> On NFS?

Locally only. Please advice how I can test this on NFS

**Comment by jondequinor** [comment]
$HOME is NFS if you log onto an rgs node.

**Comment by frode-aarstad** [comment]
Any tips on how to provoke a large logfile while running on RGS ?

**Comment by dotfloat** [comment]
If anything, NFS will make it behave better because the throughput is much lower.

What I did was that I changed `poly_example` to `print` at a high rate to simulate a badly written job. Using `QPlainTextEdit` would lock up the entire application and not allow you to kill it.

**Review by dotfloat — APPROVED** [review]
🚀

**Pull request merged**
