### PR TITLE
Reduce log level for MAX_RUNTIME reached and only log once

### PR DESCRIPTION
**Pull request by oyvindeide**
Error level for reached MAX_RUNTIME seems a bit much as this is
not really an error in ert, but something the user should be aware
of. It is also placed inside a while loop, so it it takes time to
kill the process it will flood the logger.

## Pre review checklist

- [x] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Review by ManInFez — DISMISSED** [review]

**Review by markusdregi — CHANGES_REQUESTED** [review]
Could you explain the rationale for making it debug information though? I would see this as useful information for our users. The low discoverability of realisations being killed due to `MAX_RUNTIME` has been brought forward from our users frequently until it improved...

**Comment by oyvindeide** [comment]
> Could you explain the rationale for making it debug information though? I would see this as useful information for our users. The low discoverability of realisations being killed due to `MAX_RUNTIME` has been brought forward from our users frequently until it improved...

Both show up in the user log, so the discoverability is the same. But it also drowns out everything else, one failing ensemble can potentially produce a couple of hundred mb of text. Could change it to just log once regardless if you prefer.

**Comment by markusdregi** [comment]
The current approach looks much better to me :) But, could you explain which problem you are actually trying to solve? Is the issue that by labelling this as `error` it would flood any log handler, including the internal network logger? Or that the terminal is flooded?

I think it makes sense to log the message as a warning once, but depending on the answers above it might make sense to log as a debug statement if we reach the code again? Basically introducing an `else` to your current `if` ☯️

**Comment by oyvindeide** [comment]
> The current approach looks much better to me :) But, could you explain which problem you are actually trying to solve? Is the issue that by labelling this as `error` it would flood any log handler, including the internal network logger? Or that the terminal is flooded?

The main issue that it floods any log handler, more or less regardless of what log level we set (the default is `debug` for the root logger in `ert` at the moment). Nothing is being logged to the terminal, but it is being logged to `ert-log.txt`. And having duplicates of the same message does not really make sense, so in that regard the current approach is better.

> 
> I think it makes sense to log the message as a warning once, but depending on the answers above it might make sense to log as a debug statement if we reach the code again? Basically introducing an `else` to your current `if` ☯️

Maybe, not sure what the value is though, as we will never get a debug message if the `else` happens, and the user would still be flooded with no value being added for them. Not sure how frequent this is, and could there was a perfect storm of circumstances, but monitoring showed a few hundred mbs over a few days, and has since come down.

**Comment by markusdregi** [comment]
My point was that we could do

```python
if not self.timed_out:
    logger.warning(log_message)
else:
    logger.debug(different_log_message)
```

Then we log as a warming when we take down the realisation due to `MAX_RUNTIME`. But, in later iterations of the loop, if we are still not able to take down the realisation we will log what is in the `else` message.

That would not help against flooding the logs, but at the same time I guess it is in these scenarios the debug logging is useful? As in, the tool is stuck in a state where it tries to take down a realisation but has not succeeded in that yet. It is not easy to see that that is the case without any logs...

**Comment by oyvindeide** [comment]
> Then we log as a warming when we take down the realisation due to MAX_RUNTIME. But, in later iterations of the loop, if we are still not able to take down the realisation we will log what is in the else message.

My main problem with that is we are not really able to tell why we are not able to take it down, and so we will potentially create a lot of identical log statements with doubious value for the user (and no value for us as we are not able to see it), drowning out the most important log message that we reached max runtime.

> That would not help against flooding the logs, but at the same time I guess it is in these scenarios the debug logging is useful? As in, the tool is stuck in a state where it tries to take down a realisation but has not succeeded in that yet. It is not easy to see that that is the case without any logs...

I see your point, and as an `WARNING` or `ERROR` message it would make sense, but then I would put some sort of guard on it happening more than one time. I just felt that was too much added state for a logging statement, but will be happy to do that.

**Comment by markusdregi** [comment]
I'm thinking that the ideal solution here would be that attempts at killing is logged regularly as debug information and exceeding maximum runtime is logged as a warning.

A possible solution without drowning the log is to split into two logs, one with debug activated and one without. Or, we could do a counter such that we only log kill attempts % 60 == 0 or similar 🤷🏻

**Comment by jondequinor** [comment]
> Could you explain the rationale for making it debug information though? I would see this as useful information for our users. The low discoverability of realisations being killed due to `MAX_RUNTIME` has been brought forward from our users frequently until it improved...

I'm not sure your concerns @markusdregi are still valid, but we have a mechanism for telling our users that something died due to `MAX_RUNTIME`:

https://github.com/equinor/ert/blob/26525d66f6d9b25a811cf0a4986df92cfc714e0d/ert_shared/models/base_run_model.py#L282-L286

They won't miss this bit of logging.

**Comment by jondequinor** [comment]
As for log levels, I strongly suggest debug/info if it is not an error—which it arguably is not, at least not from an ERT point of view.

**Comment by markusdregi** [comment]
> They won't miss this bit of logging.

Is that true for CLI users as well or only GUI users @jondequinor?

**Comment by markusdregi** [comment]
The good old, all logging is information 🚀 I agree. And I would be fine with making all of the logging labelled as information...

**Comment by oyvindeide** [comment]
This is somewhere in the middle, we are logging to `INFO` if we have reached `MAX_RUNTIME`, and logging to `WARNING` if we keep looping after we tried killing, this may or may not be an error.

**Comment by jondequinor** [comment]
> > They won't miss this bit of logging.
> 
> 
> 
> Is that true for CLI users as well or only GUI users @jondequinor?

Yes

**Comment by jondequinor** [comment]
@oyvindeide do we want this? Is there something unresolved here, still?

**Comment by oyvindeide** [comment]
I will squash once I hear from @markusdregi, I think the final diff is what we discussed.

**Review by sondreso — APPROVED** [review]
LGTM!

**Comment by oyvindeide** [comment]
test required please

**Pull request merged**
