### PR TITLE
Remove irrelevant keywords in snake_oil.ert

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves lengthy snake_oil.ert

**Approach**
✂️ 

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by hnformentin** [comment]
A couple of required tests are not passing in this one as well.

**Comment by berland** [comment]
> Last time we talked about this I understood you prefer not to rerun by others :-)
(that applied only to Torque runs in komodo-releases.. :) )

**Comment by berland** [comment]
The tests in this PR fails due to interference with the code in https://github.com/equinor/ert/blob/main/tests/conftest.py#L229-L235

**Comment by berland** [comment]
> The tests in this PR fails due to interference with the code in https://github.com/equinor/ert/blob/main/tests/conftest.py#L229-L235

Fixed (by not touching the top of the file)

**Review by hnformentin — APPROVED** [review]

**Pull request merged**
