### PR TITLE
Fix run_workflow_widget for Issue #4789

### LINKED ISSUE #4727: RunWorkflowWidget is broken because of removed ert_workflow_list
In commit a6aa00c6a4f9043cd29c8bdcd7b08907ab068ad8 `getWorkflowList()` was removed. This was used by `RunWorkflowWidget`, but because its tests uses a mocked object, we didn't notice that it broke: https://github.com/equinor/ert/blob/ecf11cf8b9471c2cdd4ce18f46151b6df82ca2cb/tests/unit_tests/gui/test_gui_load.py#L23-25 .
We need to at least fix RunWorkflowWidget. It uses `ert.getWorkflowList().getWorkflowNames()` to get the list of workflow names. The way that is done now is by `list(ert.resConfig().workflows.keys())`. The mock needs to be updated accordingly.
Once this is done we should create another issue to remove the mock, and use synthetic test data instead.

### PR DESCRIPTION
**Pull request by Jehan-h20220012**
**Issue**
Resolves #4727 
run_workflow_widget broke due to the removal of workflow_list.

Changes the tests to not use a mock, but instead use a minimal config.

**Approach**
_Short description of the approach_

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Updated documentation
- [x] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by eivindjahren** [comment]
I apologize for having to close this issue, but I am sure we can accomodate helping you get something else merged, see https://github.com/equinor/ert/pull/4789#issuecomment-1415262628 .

**Comment by Jehan-h20220012** [comment]
@eivindjahren okay. 
I cannot show God first issues in assignment so if you can remove that tag it will help me!

**Comment by Jehan-h20220012** [comment]
#4643 issue is good to go for me

**Pull request closed without merging**
