### PR TITLE
Add filename to configuration tokenizer feedback

### LINKED ISSUE #4659: Failure to load observation file does not give descriptive message
As per https://wiki.equinor.com/wiki/index.php/Debugging error message for OBS_CONFIG is confusing It should indicate whether:

* the input file path exists or not.
* the input file format is incorrect

### PR DESCRIPTION
**Pull request by andreas-el**
**Issue**
Resolves #4659 

Turns this;
```
WARNING: Skipping unexpected token "skdfjklsafsdajkldfjas".
```
into this;
```
WARNING: Skipping unexpected token "GEfdsjklfNERAL_OBSERVATION" in file /private/andrli/project/ert/test-data/poly_example/observations.
```

**Approach**
_Short description of the approach_

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by oysteoh** [comment]
is this really resolving the issue you are pointing towards? :thinking:

**Comment by andreas-el** [comment]
> is this really resolving the issue you are pointing towards? thinking

Yes, i think so. The referred issue was regarding handling/parsing of observations, were feedback was cryptic.

Providing jibberish in the observation file, would cause feedback regarding the jibberish, but no indication where the problem lies.
This PR tries to rectify this (last) withstanding issue. The others were already accounted for.

**Comment by oysteoh** [comment]
> > is this really resolving the issue you are pointing towards? thinking
> 
> Yes, i think so. The referred issue was regarding handling/parsing of observations, were feedback was cryptic.
> 
> Providing jibberish in the observation file, would cause feedback regarding the jibberish, but no indication where the problem lies. This PR tries to rectify this (last) withstanding issue. The others were already accounted for.

Then i understand! Thanks :)

**Comment by oysteoh** [comment]
Not saying it is wrong - but - is this making it clear for the user what is wrong? ( Removed `G`  from `GENERAL_OBSERVATION` in the `poly.ert` )

```
WARNING: Skipping unexpected token "ENERAL_OBSERVATION" in file /datadisk/repos/ert/test-data/poly_example/observations.

WARNING: Skipping unexpected token "POLY_OBS" in file /datadisk/repos/ert/test-data/poly_example/observations.

WARNING: Skipping token "DATA" in unknown class.
WARNING: Skipping token "=" in unknown class.
WARNING: Skipping token "POLY_RES" in unknown class.
WARNING: Skipping token ";" in unknown class.
WARNING: Skipping token "INDEX_LIST" in unknown class.
WARNING: Skipping token "=" in unknown class.
WARNING: Skipping token "0,2,4,6,8" in unknown class.
WARNING: Skipping token ";" in unknown class.
WARNING: Skipping token "RESTART" in unknown class.
WARNING: Skipping token "=" in unknown class.
WARNING: Skipping token "0" in unknown class.
WARNING: Skipping token ";" in unknown class.
WARNING: Skipping token "OBS_FILE" in unknown class.
WARNING: Skipping token "=" in unknown class.
WARNING: Skipping token "poly_obs_data.txt" in unknown class.
```

**Comment by andreas-el** [comment]
> Not saying it is wrong - but - is this making it clear for the user what is wrong? ( Removed `G` from `GENERAL_OBSERVATION` in the `poly.ert` )
> 
> ```
> WARNING: Skipping unexpected token "ENERAL_OBSERVATION" in file /datadisk/repos/ert/test-data/poly_example/observations.
> 
> WARNING: Skipping unexpected token "POLY_OBS" in file /datadisk/repos/ert/test-data/poly_example/observations.
> 
> WARNING: Skipping token "DATA" in unknown class.
> WARNING: Skipping token "=" in unknown class.
> WARNING: Skipping token "POLY_RES" in unknown class.
> WARNING: Skipping token ";" in unknown class.
> WARNING: Skipping token "INDEX_LIST" in unknown class.
> WARNING: Skipping token "=" in unknown class.
> WARNING: Skipping token "0,2,4,6,8" in unknown class.
> WARNING: Skipping token ";" in unknown class.
> WARNING: Skipping token "RESTART" in unknown class.
> WARNING: Skipping token "=" in unknown class.
> WARNING: Skipping token "0" in unknown class.
> WARNING: Skipping token ";" in unknown class.
> WARNING: Skipping token "OBS_FILE" in unknown class.
> WARNING: Skipping token "=" in unknown class.
> WARNING: Skipping token "poly_obs_data.txt" in unknown class.
> ```

I'd argue so, -- yes. The first warning indicates the actual problem, the following issues are caused by this. Alternatively we could improve those messages as well, providing a path for them.
The wording in the warning can be changed if that's what you are referring to.
The file referred to is correct, i assume you meant you edited the observation file which is referred to from poly.ert.
I have no problem accepting either outcomes, improving this, or skipping the whole PR.

**Comment by oysteoh** [comment]
After the discussion we had i think it makes sense merging it as it provides more help than what the users currently have. The error messages is better - which is a step in the right direction!

**Review by oysteoh — APPROVED** [review]

**Comment by eivindjahren** [comment]
> > Not saying it is wrong - but - is this making it clear for the user what is wrong? ( Removed `G` from `GENERAL_OBSERVATION` in the `poly.ert` )
> > ```
> > WARNING: Skipping unexpected token "ENERAL_OBSERVATION" in file /datadisk/repos/ert/test-data/poly_example/observations.
> > 
> > WARNING: Skipping unexpected token "POLY_OBS" in file /datadisk/repos/ert/test-data/poly_example/observations.
> > 
> > WARNING: Skipping token "DATA" in unknown class.
> > WARNING: Skipping token "=" in unknown class.
> > WARNING: Skipping token "POLY_RES" in unknown class.
> > WARNING: Skipping token ";" in unknown class.
> > WARNING: Skipping token "INDEX_LIST" in unknown class.
> > WARNING: Skipping token "=" in unknown class.
> > WARNING: Skipping token "0,2,4,6,8" in unknown class.
> > WARNING: Skipping token ";" in unknown class.
> > WARNING: Skipping token "RESTART" in unknown class.
> > WARNING: Skipping token "=" in unknown class.
> > WARNING: Skipping token "0" in unknown class.
> > WARNING: Skipping token ";" in unknown class.
> > WARNING: Skipping token "OBS_FILE" in unknown class.
> > WARNING: Skipping token "=" in unknown class.
> > WARNING: Skipping token "poly_obs_data.txt" in unknown class.
> > ```
> 
> I'd argue so, -- yes. The first warning indicates the actual problem, the following issues are caused by this. Alternatively we could improve those messages as well, providing a path for them. The wording in the warning can be changed if that's what you are referring to. The file referred to is correct, i assume you meant you edited the observation file which is referred to from poly.ert. I have no problem accepting either outcomes, improving this, or skipping the whole PR.

So the warnings given indicate that this isn't a great parser, but the error message is better. Is this an "Invented by ERT" file format? If so, I would argue using the overloaded terms "class", "subclass" and "singleton" is very confusing.

**Pull request merged**
