### PR TITLE
Fix typo valye -> value

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves silli typo

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Review by kwinkunks — APPROVED** [review]
Did nothing ever try to read this valye? If not, why is it there?

For sure if it stays, needs to be fixed.

**Comment by berland** [comment]
> Did nothing ever try to read this valye? If not, why is it there?
> 
> For sure if it stays, needs to be fixed.

Good point, as the env variable is never referenced anywhere in the test code. I am not sure if the test-data serves a purpose as example data outside the automated test suite, but for sure there could have been a test that this SILLY_VAR actually is present on the compute node side (it gets injected into jobs.json)

**Comment by berland** [comment]
I'll remove it. No point in writing a test for it, passing of envs to jobs.json is alreacy covered.

**Comment by berland** [comment]
Superseded by #5387

**Pull request closed without merging**
