### PR TITLE
Pin conan<2 and conan-cmake=0.18.1

### PR DESCRIPTION
**Pull request by eivindjahren**
conan-cmake is not compatible with conan version 2
## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Updated documentation
- [x] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Review by oyvindeide — APPROVED** [review]
Can you check why the jenkins tests fail before merging?

**Review by andreas-el — APPROVED** [review]
Goodie!

**Comment by andreas-el** [comment]
Jenkins retest please!

**Comment by eivindjahren** [comment]
jenkins test this please

**Comment by eivindjahren** [comment]
jenkins test this please!

**Pull request merged**
