### PR TITLE
Avoid passing enkf_main_type to enkf_main_log_step_list()

### PR DESCRIPTION
**Pull request by BjarneHerland**
It was only used to extract log-path, so do this in caller and change
signature.

### CODE REVIEW

**Comment by dafeda** [comment]
What do you think about adding a test of this function?

**Comment by BjarneHerland** [comment]
> What do you think about adding a test of this function?

Not sure about the value of testing this particular function...  IIRC we plan to replace the logging-mechanism in any case. What do you think?

**Comment by dafeda** [comment]
> > What do you think about adding a test of this function?
> 
> Not sure about the value of testing this particular function... IIRC we plan to replace the logging-mechanism in any case. What do you think?

Probably not that valuable, but I tend to default to testing functions I'm making changes to.
The test might at least help someone else understand the code a bit better, or act as a starting point for testing other stuff.

**Review by dafeda — APPROVED** [review]
LGTM 👍

**Pull request merged**
