### PR TITLE
Remove config_help.py

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
**Issue**
This file will is not runnable.

Need to figure out where/how this is used, and if it is necessary to keep the functionality.

### CODE REVIEW

**Review by sondreso — APPROVED** [review]
This can safely be removed, don't think we will develop the current tooltip help anymore!

**Comment by sondreso** [comment]
Merging as Jenkins is down :slightly_smiling_face:

**Comment by lars-petter-hauge** [comment]
I suppose I could've included slightly more context in the commit message there. I just wasn't sure if we were to remove it, or if it needed to be improved.

**Comment by sondreso** [comment]
No worries, I have the context and wanted to delete this file before, glad you did it :smile:

**Pull request merged**
