### PR TITLE
tests close properly

### PR DESCRIPTION
**Pull request by mortalisk**
Spent way to much time figuring out why the tests weren't shutting down properly. Now they do.

### CODE REVIEW

**Comment by jondequinor** [comment]
Why didn't they? What were the faulty assumptions?

**Comment by mortalisk** [comment]
I'm not really sure actually. At least I had to cancel tasks that were waiting for messages that would never arrive. And make sure the loop is ran to allow things to finish properly. But there are quite a bit of changes which I don't know what effect they had.

**Comment by mortalisk** [comment]
I'm not really sure actually. At least I had to cancel tasks that were waiting for messages that would never arrive. And make sure the loop is ran to allow things to finish properly. But there are quite a bit of changes which I don't know what effect they had.

**Comment by jondequinor** [comment]
Could we remove mocking from the evaluator entirely? I think we're at a point where the evaluator should receive a `Ensemble` and just press `run` on it. For integration tests with a focus on monitoring, this `Ensemble` would then be producing mock events on `run()`.

What do you think?

**Review by jondequinor — APPROVED** [review]
LGTM!

**Pull request merged**
