### PR TITLE
Create ert package

### LINKED ISSUE #1786: Create ert python module
Create a separate module called ert and setup CI to run mypy, pylint, flake8 and black on this module. Create a matching test setup according to best practices for python testing.

### PR DESCRIPTION
**Pull request by verveerpj**
**Issue**
Resolves #1786

**Approach**
Create a minimal package, add to the style and typing actions.

Also disabled pylint in two places, where it seems to behave incorrectly.

### CODE REVIEW

**Comment by verveerpj** [comment]
Jenkins, test this please

**Comment by jondequinor** [comment]
Would it be possible to move the `ert` package to `src/ert`? There are many reasons as to why, let me know if you want them. 😁

**Comment by verveerpj** [comment]
> Would it be possible to move the `ert` package to `src/ert`? There are many reasons as to why, let me know if you want them. 😁

That would also be very much my preference. But recently we discussed that this is not possible, because we are using skbuild.

**Comment by jondequinor** [comment]
I think that only affects the use of the root package in package_dir. Which is not something we have to use?

**Comment by verveerpj** [comment]
> I think that only affects the use of the root package in package_dir. Which is not something we have to use?

I have been trying that, by adding a `package_dir `option with just an entry for `ert`, in various forms, but no luck so far.

**Comment by jondequinor** [comment]
Okay, then never mind my comment.

**Review by jondequinor — APPROVED** [review]

**Pull request merged**
