### PR TITLE
Delete workflows related to obs/data ranking

### PR DESCRIPTION
**Pull request by oyvindeide**
## Pre review checklist

- [x] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Comment by oyvindeide** [comment]
test required please

**Comment by oyvindeide** [comment]
Test ert please

**Comment by oyvindeide** [comment]
test ert please

**Comment by jondequinor** [comment]
Is there some context to this change?

**Comment by oyvindeide** [comment]
It is related to this: https://github.com/equinor/ert/issues/1880 but does not solve it.

**Pull request merged**
