### PR TITLE
Fix bug in run analysis tool

### LINKED ISSUE #6741: Adaptive Localization fails with AttributeError 'AnalysisTimeEvent' object has no attribute 'msg'
**Describe the bug**
Running adaptive localization manually on drogon causes failure.

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert` (main-branch) in a unstable komodoenv
2. `ert gui drogon_ahm`
3. Run ensemble experiment
4. Run manual update with adaptive localization turned on
5. Crashed with AttributeError: 'AnalysisTimeEvent' object has no attribute 'msg'

**Expected behaviour**
Run adaptive localization without crashing

**Environment**
 - OS: RHEL7
 - ERT/Komodo release: main
 - Python version 3.8
 - Remote/HPC execution involved: no

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #6741 

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

## Pre review checklist

- [ ] Read through the code changes carefully after finishing work
- [ ] Make sure tests pass locally (after every commit!)
- [ ] Prepare changes in small commits for more convenient review (optional)
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kvashchuka** [comment]
I see that there is no test here. However, it might be too difficult to reproduce this failure in a test. Could you evaluate adding test and whether it brings value to add it?

**Comment by frode-aarstad** [comment]
> I see that there is no test here. However, it might be too difficult to reproduce this failure in a test. Could you evaluate adding test and whether it brings value to add it?

I think its not worth adding a test for this. Better typing should have caught this

**Comment by dafeda** [comment]
I rebased one of my branches on this and started an update with Adaptive Localization using Drogon.
It did not crash.
However, if I try running from this branch I get an error related to the new API of `iterative_ensemble_smoother`, so you'll probably need to rebase on `main`.

**Comment by frode-aarstad** [comment]
Rebased on main

**Comment by dafeda** [comment]
image

Works 👍

**Review by dafeda — APPROVED** [review]

**Pull request merged**
