### PR TITLE
Rename JobQueue to Scheduler, move job_queue module to scheduler module

### LINKED ISSUE #6692: Rename JobQueue to Scheduler
This includes renaming the `job_queue` module to `scheduler`.

### PR DESCRIPTION
**Pull request by xjules**
**Issue**
Resolves #6692

### CODE REVIEW

**Comment by berland** [comment]
poly case runs through?

**Comment by xjules** [comment]
> poly case runs through?

Yes

**Review by berland — APPROVED** [review]
then I say just merge it to avoid clashes over time :)

**Comment by berland** [comment]
😱

**Pull request merged**
