### PR TITLE
Move and update installed workflow doc

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
While working on a workflow issue, I thought that it would be nice just to add what is necessary to run the workflows (it wasn't as clear as I would like it to be). I might add an example (unless it's covered in the other chapter) perhaps demonstrating how arguments can be passed along (which very often is the part that is documented in the workflow_jobs description)

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by jepebe** [comment]
Depending on when PR #libres993 is merged this list will change.

**Comment by lars-petter-hauge** [comment]
The workflows added through the `ert_workflow_jobs` extension are the ones coming from outside of libres and ert (not built-ins, but the ones from e.g. semeio). The PR you're referring to should not change this I believe - or at least it won't remove any of them. We might have to add more documentation though, guess they should be listed in `built-ins` in such a case.

**Comment by jondequinor** [comment]
What is the progress on this issue? Is it really a draft or ready for review? In the latter case, could you rebase on master and rerun the tests?

**Comment by lars-petter-hauge** [comment]
This is a forgotten issue to be honest, and I think it was pretty much ready for review. It's a small change, adding a link to the tutorial which shows how this is done.

**Review by sondreso — APPROVED** [review]

**Pull request merged**
