### PR TITLE
Delete unused arg_pack.h

### LINKED ISSUE #2594: Remove unused `arg_pack.h`
Remove unused `arg_pack.h`

### PR DESCRIPTION
**Pull request by dafeda**
**Issue**
Resolves #2594

## Pre review checklist

- [ x] Added appropriate labels

### CODE REVIEW

**Review by eivindjahren — APPROVED** [review]

**Comment by eivindjahren** [comment]
weirdly this seems to change the behavior of some `ert_gui` tests. May be worth having a look.

**Comment by dafeda** [comment]
> weirdly this seems to change the behavior of some `ert_gui` tests. May be worth having a look.

All tests have passed, which  ones have changed behaviour?

**Comment by eivindjahren** [comment]
> All tests have passed, which ones have changed behaviour?

Not sure but coverage no longer hits `ert_gui.ertwidgets.validationsupport::presentError` might be a fluke.

**Comment by eivindjahren** [comment]
Btw, the coverage changes I am looking at is here: https://app.codecov.io/gh/equinor/ert/compare/2595/changes

**Pull request merged**
