### PR TITLE
Rephrase start simulation button

### LINKED ISSUE #4374: Rephrase "Start simulation" button.
`Start simulation` is slightly misguiding, as one would typically think of a simulator in the forward model when talking about simulation. `Run` might be better, suggestions are welcome.

We are in the process of naming an instance of a `mode` run to `Experiment`, hence `Run Experiment` would make sense in the long run.

### PR DESCRIPTION
**Pull request by jonathan-eq**
**Issue**
Resolves #4374

**Approach**
Rephrased "Start Simulation"-button to "Run Experiment" as "start simulation" can be misleading.

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Updated documentation
- [x] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by hnformentin** [comment]
Nice PR :-) 
I made a quick search in ert repo and there are more instances of "Start simulation" than the ones substituted so far (e.g. in documentation and comments). 
Would you mind to take a look and include those who are relevant?
Also, what do you think about labelling this change as "release notes"? Maybe Improvements category?

**Comment by hnformentin** [comment]
I was running ert and observed that this PR may need to modify other wordings.

For example in the screenshoot below, what do you think about "Experiment running" instead of "Simulations running" and "Experiment - poly.ert" instead of "Simulations - poly.ert"?

Screenshot 2023-08-02 at 07 39 23

**Comment by jonathan-eq** [comment]
Semeio fails, but I cannot merge in integration test fix without having ERT changes in first.
https://github.com/equinor/semeio/pull/533

**Comment by jonathan-eq** [comment]
Created a new issue for rephrasing the rest of the code to "experiment" instead of "simulation"
**Issue** https://github.com/equinor/ert/issues/5771

**Review by dafeda — COMMENTED** [review]
Nice 👍

**Review by dafeda — APPROVED** [review]

**Pull request merged**
