### PR TITLE
Add parameter counts in the GUI

### LINKED ISSUE #4958: Display the number of parameters in the GUI
It would be nice if the number of parameters in the case are shown next to the parameter names in the GUI.

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #4958 

**Approach**
_Short description of the approach_

## Pre review checklist

- [x] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Updated documentation
- [ ] Ensured new behaviour is tested

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by dafeda** [comment]
Nice feature 👍 

Looking at `snake_oil_field.ert` we for example get `PERMX (500`.
Perhaps it would be better to show `PERMX (nx, ny, nz)` instead to make it clear that this is a 3D parameter?

image

**Comment by dafeda** [comment]
Should we add the total number of parameters as well?

**Comment by frode-aarstad** [comment]
> Nice +1
> 
> Looking at `snake_oil_field.ert` we for example get `PERMX (500)`. Perhaps it would be better to show `PERMX (nx, ny, nz)` instead to make it clear that this is a 3D parameter?
> 
> image

Should we do similar for Surface ie: (ncol, nrow) ?

**Comment by dafeda** [comment]
> > Nice +1
> > Looking at `snake_oil_field.ert` we for example get `PERMX (500)`. Perhaps it would be better to show `PERMX (nx, ny, nz)` instead to make it clear that this is a 3D parameter?
> > image
> 
> Should we do similar for Surface ie: (ncol, nrow) ?

Yes, I think that makes sense.

**Comment by frode-aarstad** [comment]
I have changed the parameter output as requested and tried to add some formatting to the output to make it more readable when the numbers are big.

**Comment by frode-aarstad** [comment]
image

**Review by dafeda — APPROVED** [review]
Very nice 👍

**Pull request merged**
