### PR TITLE
Have repeated flaky tests run new python instance

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
**Approach**
Garbage cleaning and session controlled objects in tests could reduce the usage of `pytest-repeat`. Instead we completely run a new python instance on each try. 

## Pre review checklist

- [x] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
Tested that the script runs as expected on internal CI

**Review by BjarneHerland — CHANGES_REQUESTED** [review]
Looks good but could we comment in run_libres_ert_tests() why certain tests are masked out? Ideally, there should also be some comment/placeholder for how/where I tailor this script to my own PR in case I want to stress-test some particular test.

**Comment by lars-petter-hauge** [comment]
I used the same test setup that we are already running - not that that is any excuse. There are no comments on those tests.

I'll do some checking and see if we can add the reason as to why they should be ignored (and if it is because of flakyness we can simply remove it, as we are in fact looking for it).

I can add a comment on how one would swap out for a specific test

**Review by BjarneHerland — APPROVED** [review]
👍

**Comment by lars-petter-hauge** [comment]
test ert please

**Pull request merged**
