### PR TITLE
Api case names

### LINKED ISSUE #2193: Fetch casename from storage api
In the qt plotter, retrieving casenames should be backed by storage api ( ensemble names )

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #2193 

Duplicate of https://github.com/equinor/ert/pull/2291, now closed. Because we want to do the testing on the `api_adoption` branch.

### CODE REVIEW

**Comment by DanSava** [comment]
jenkins test this please

**Comment by DanSava** [comment]
Jenkins test this

**Review by oysteoh — APPROVED** [review]
Given the tests are running along with the documentation of the flaky ert test in a new issue( or reopen an older issue - i suspect amongst others this issue is related to the same behavior https://github.com/equinor/ert/issues/2381 ) i would say this is good to go! 🚀

**Comment by DanSava** [comment]
I don't understand why the 3.10 tests are not starting @oysteoh do you have any idea?

**Comment by oysteoh** [comment]
> I don't understand why the 3.10 tests are not starting @oysteoh do you have any idea? Also, why is 3.10 tested?

Have no idea - haven't seen those before i think? @markusdregi  have we started to test with python 3.10?

**Comment by DanSava** [comment]
I think it might be linked to the fact that this PR is merging into a feature branch `api_adoption` and not the main branch. I opened a new PR from a branch in my fork and had the same suite of tests for 3.10, which are not showing up for PR that go directly to `main`

**Pull request merged**
