### PR TITLE
Fix minor typo, follwing -> following

### PR DESCRIPTION
**Pull request by berland**

### CODE REVIEW

**Review by jondequinor — APPROVED** [review]
Oddly consistent typo 🤔 

Thank!

**Comment by jondequinor** [comment]
Jenkins test this please

**Comment by sondreso** [comment]
Jenkins test this please

**Comment by markusdregi** [comment]
Jenkins: Test this please

**Comment by markusdregi** [comment]
I'm suspecting Jenkins was stalling due to merge issues with `main`, so I did a rebase...

**Comment by sondreso** [comment]
Jenkins ok to test

**Pull request merged**
