### PR TITLE
Remove C Torque driver and tests

### LINKED ISSUE #7912: Remove TORQUE driver and tests from JobQueue
Due to the lack of usage and at the same time the focus is on the PBS driver we should remove TORQUE driver from JobQueue.

### PR DESCRIPTION
**Pull request by jonathan-eq**
**Issue**
Resolves #7912 

**Approach**
✂️ 

(Screenshot of new behavior in GUI if applicable)

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by berland** [comment]
Do we know if some of the test codes deleted here have not (yet?) been ported to the new Scheduler?

**Comment by berland** [comment]
Should there be changes to ert/config/parsing/queue_system.py as well?

**Comment by jonathan-eq** [comment]
> Should there be changes to ert/config/parsing/queue_system.py as well?

It is used by scheduler too, so I cannot change too much there unless I split it into LegacyQueueSystem and SchedulerQueueSystem. I tried doing this, and it created mypy typing issues. There is probably a better way around this, but I am not sure how much work should be put into it when it is going away regardless.

**Comment by jonathan-eq** [comment]
> Do we know if some of the test codes deleted here have not (yet?) been ported to the new Scheduler?

I will double check!

**Review by berland — APPROVED** [review]
Looking good!

**Comment by berland** [comment]
Before merge, do we need to also disable some Torque testing in komodo-releases/.github/workflows?

**Comment by jonathan-eq** [comment]
> Before merge, do we need to also disable some Torque testing in komodo-releases/.github/workflows?

Yes, let's merge this one first. https://github.com/equinor/komodo-releases/pull/5810

**Pull request merged**
