### PR TITLE
Output the number of reals running in existing runpaths

### LINKED ISSUE #4410: Mention how many of the realizations are running in existing run paths
From a previous PR.

> Could we also mention how many of the realizations are running in existing run paths? I think a common way to run us to use `Single realization test-run` followed by a full ensemble. So in that case say: `1 out of N realizations are running in existing run paths`

_Originally posted by @oyvindeide in https://github.com/equinor/ert/pull/4244#discussion_r1036787847_

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #4410 

**Approach**
image

(Screenshot of new behavior in GUI if applicable)

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by dafeda** [comment]
To make the review process easier, I think a screenshot would be useful here.

**Comment by frode-aarstad** [comment]
Added screenshot

**Comment by dafeda** [comment]
> Added screenshot

Ah, so this will not show in the GUI, just in the CLI?

**Comment by frode-aarstad** [comment]
> > Added screenshot
> 
> Ah, so this will not show in the GUI, just in the CLI?

It is in the GUI aswell.

**Review by dafeda — APPROVED** [review]

**Pull request merged**
