### PR TITLE
Move all Jenkinsfiles into one place

### LINKED ISSUE #1809: Cleanup lingering Jenkinsfiles
**Problem description**
Now that we have unified libres and ert there are Jenkinsfiles lingering around that can be unified/cleaned up. Currently, there are two pipelines for testing komodo. [example](https://github.com/equinor/ert/tree/main/libres/ci/jenkins)

**Describe solution**
Unify all CI files under one umbrella/directory project_root/ci.

### PR DESCRIPTION
**Pull request by kvashchuka**
**Issue**
Resolves #1809 

**Approach**
Libres Jenkinsfiles are moved to `ci/jenkins`, where other Jenkins files reside. Plus doubling Jenkinsfile-komodo files were deleted

### CODE REVIEW

**Comment by mortalisk** [comment]
I have a question:
 * How is the start_tests run, when testKomodo.groovy is running run_tests?

And a thing to remember after merging, is to update the Jennkins job for ert to run the correct script.

But this looks good!

**Review by mortalisk — APPROVED** [review]

**Comment by markusdregi** [comment]
Is this PR continuing the setup of running the tests both against a fresh build on RHEL7 on-premise with internal test data available (which appears to not be running right now, see https://github.com/equinor/ert/issues/1845) and a non-required run against the Komodo bleeding build?

**Comment by kvashchuka** [comment]
> Is this PR continuing the setup of running the tests both against a fresh build on RHEL7 on-premise with internal test data available (which appears to not be running right now, see #1845) and a non-required run against the Komodo bleeding build?

The required Jenkins build doesn't pass because we moved stuff around. That is why a new pipeline was created in Jenkins, called `sharlon_anna_ert_pr` (https://ci.equinor.com/scout/job/sharlon_anna_ert_pr/). That one is running `ci/jenkins/Jenkinsfile-libres` and pass :)

Also, we are not sure how to move forward with it, because now the required test is failing and it needs to be updated in Jenkins almost simultaneously with the merge of this PR. Or what should be the order of events in this case?

**Comment by markusdregi** [comment]
The way to get this in is that you convince someone with admin powers that this is fine, then we use the admin super powers to merge it and immediately afterwards update the Jenkins job... 💪🏻

So, you are claiming that this PR then continues running the two different Jenkins jobs? One against a clean internal environment and one against komodo/bleeding?

**Comment by kvashchuka** [comment]
> The way to get this in is that you convince someone with admin powers that this is fine, then we use the admin super powers to merge it and immediately afterwards update the Jenkins job... 💪🏻
> 
> So, you are claiming that this PR then continues running the two different Jenkins jobs? One against a clean internal environment and one against komodo/bleeding?

It does run two different Jenkins jobs - one against komodo/bleeding (Komodo PR build), and one against a clean environment (https://ci.equinor.com/scout/job/sharlon_anna_ert_pr/), but in the second one only libres is tested. I believe it was like this before as well

**Comment by kvashchuka** [comment]
PR description.

Prior to this PR there were three `Jenkinsfile-komodo` files in ert project:
1. in `ert` directory. Deleted because it does not seem to be doing anything - it is calling non-existent in ert root directory `testkomodo.sh` script
2. in `ert/ci/jenkins` directory. Left unchanged
3. in `ert/libres/ci/jenkins` directory. Since it is a subset of `Jenkinsfile-komodo` from the previous point, it was deleted

`ert/libres/testjenkins.sh` is moved to `ert/ci/jenkins` and renamed to `test_libres_jenkins.sh`. It is called in `Jenkinsfile-libres` that is now moved from ert root to `ert/ci/jenkins` folder, where now all Jenkins files reside. 

`ert/libres/ci/jenkins/testkomodo.sh` is deleted, because mostly it is subset of `ert/ci/jenkins/testkomodo.sh`. I am saying mostly, because `ert/ci/jenkins/testkomodo.sh` does not have `run_tests` function https://github.com/equinor/ert/blob/main/libres/ci/jenkins/testkomodo.sh#L29 
However, `start_tests()` function is called and running is happening there. This might not be optimal, but it is not a change introduced in this PR. But it, of course, can be fixed here, if needed

**Review by markusdregi — APPROVED** [review]
I have gone through all of the logs on Jenkins; both for the Komodo job and comparing the previous ERT-PR job with the temporary one created for this PR and it all looks good 👍🏻

**Comment by kvashchuka** [comment]
IMPORTANT! In order to merge this PR you should:
1. Find someone with admin powers who can merge it with not all required tests passing 
2. Immediately afterwards update the Jenkins job. To do so, open `ert_PR` configuration https://ci.equinor.com/scout/job/ert_PR/configure and change the field `Script Path` to `ci/jenkins/Jenkinsfile-libres`
3. To make sure that it all works, create a dummy PR and see that two Jenkins tests pipelines are green

**Pull request merged**
