### PR TITLE
Write forward model stdout and stderr to logs/

### LINKED ISSUE #1903: Store job std{out,err} logs in a separate directory
Currently, the `stdout` and `stderr` logs from jobs are written into the runpath directory as `[job name].stdout.[job#]`. A complicated pipeline may have hundreds of these files, which makes it difficult for users to debug or otherwise look at other files.

I propose we put all of these logs into a subdirectory of runpath called `logs/` without adding this as an option. The location of the logs is an implementation detail, and if anyone is actually using these to do useful work (other than a human reading them) then we'll discover it swiftly with such an aggressive implementation.

### PR DESCRIPTION
**Pull request by dafeda**
**Issue**
Resolves #1903

**Approach**
_Short description of the approach_

## Pre review checklist

- [x] Added appropriate release note label
- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by oyvindeide** [comment]
To me this looks like a good solution, but know @sondreso has some opinions here as well.

**Comment by oyvindeide** [comment]
For reference, I checked a few external plugins, and some of them configure `stdout`/`stderr` and some dont, so variable how this will affect users.

**Comment by dafeda** [comment]
> For reference, I checked a few external plugins, and some of them configure `stdout`/`stderr` and some dont, so variable how this will affect users.

Sure, but I think it's still nice that ERT's default jobs don't clutter the runpath.

**Comment by oyvindeide** [comment]
> > For reference, I checked a few external plugins, and some of them configure `stdout`/`stderr` and some dont, so variable how this will affect users.
> 
> Sure, but I think it's still nice that ERT's default jobs don't clutter the runpath.

I agree, was just assesing the possible impact this change would have

**Comment by dafeda** [comment]
> NB: These needs a corresponding update: https://github.com/equinor/semeio/tree/main/semeio/jobs/config_jobs
> 
> (and probably in more repos..)

That would be great yes, but can be made as a separate issue in semeio I think.

**Comment by dafeda** [comment]
test this please

**Pull request merged**
