### PR TITLE
Remove all code related to PC extraction in enkf_main

### LINKED ISSUE #2366: Remove PC extraction implemented in enkf_main
PC analysis can be done with the MISFIT_PREPROCESSOR job, thus the code in enkf_main and surroundings involved with PC extraction can be removed

### PR DESCRIPTION
**Pull request by ManInFez**
Remove PC extraction from analysis config

**Issue**
Resolves #2366

### CODE REVIEW

**Comment by dafeda** [comment]
The description of the keyword `ENKF_NCOMP` references `PC`.
Should we update this?

https://github.com/equinor/ert/blob/main/docs/rst/manual/reference/configuration/keywords.rst

**Comment by dafeda** [comment]
The architecture roadmap says:

"This is
particularly directed towards correlated observations and we expect to support
outlier detection, PCA scaling and localisation as part of the standard tooling
of ERT."

Are jobs defined in `semeio` considered standard tooling since `semeio` is a dependency of `ert`?

https://github.com/equinor/ert/blob/main/docs/rst/manual/architecture/roadmap.rst#observation-tooling

**Review by dafeda — APPROVED** [review]
LGTM 👍 

Great catch!

**Comment by ManInFez** [comment]
ENKF_NCOMP is nr of computers

Semeio is considered a part of ERT package we deliver

**Comment by dafeda** [comment]
> ENKF_NCOMP is nr of computers
> 
> Semeio is considered a part of ERT package we deliver

Ah, I thought NCOMP := Number of Components

**Pull request merged**
