### PR TITLE
Add observations to responses query

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves equinor/webviz-ert#214

**Approach**
Add observations to the response response

### CODE REVIEW

**Review by jondequinor — COMMENTED** [review]
But what if you're only interested in the list?

**Comment by oysteoh** [comment]
> But what if you're only interested in the list?

Guess we could hide the observation loading behind a flag in the api? But is it worth it? Datasets we have been looking at shows that the amount of observations is quite limited, maybe like ~5 on a vector with ~1000 entries.

**Review by oysteoh — APPROVED** [review]
I'll say approve, but with the possibility of @jondequinor to argue we should improve the api with this feature. From my point of view - currently we have one consumer, and that consumer needs the observations to be present. YAGNI tells me we should wait with implementing a feature until it is actually needed, but i'm open for discussing this 😸

**Comment by frode-aarstad** [comment]
Jenkins test this please

**Pull request merged**
