### PR TITLE
Expose ert_share_path

### PR DESCRIPTION
**Pull request by oyvindeide**
If other packages are using the shared resources from ert we can
expose them through a function so we are free to move them around
without breaking the api.

### CODE REVIEW

**Review by sondreso — COMMENTED** [review]
Could we have a test for this, and maybe a comment? Just so it's not removed because it appears unused.

**Comment by oyvindeide** [comment]
> Could we have a test for this, and maybe a comment? Just so it's not removed because it appears unused.

Test seems a bit strange doesnt it? Comment makes sense 👍

**Comment by jondequinor** [comment]
Is this necessary? Linux has a `share` folder for this specific reason. Architecture independent shareable files.

**Comment by oyvindeide** [comment]
> Is this necessary? Linux has a `share` folder for this specific reason. Architecture independent shareable files.

I guess you could argue that, but in this context I feel the `distutils` argument makes more sense:

> The distutils have traditionally allowed installation of “data files”, which are placed in a platform-specific location. However, the most common use case for data files distributed with a package is for use by the package, usually by including the data files in the package directory.

**Review by sondreso — APPROVED** [review]

**Pull request merged**
