### PR TITLE
Add positive_int validation schema for NUM_CPU and MAX_SUBMIT

### PR DESCRIPTION
**Pull request by xjules**
**Issue**
Resolves https://github.com/equinor/ert/issues/7294
Resolves https://github.com/equinor/ert/issues/8078

**Approach**
Implement positive_int validation

(Screenshot of new behavior in GUI if applicable)

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Review by oyvindeide — COMMENTED** [review]
Nice! Can you also add a test?

**Comment by oyvindeide** [comment]
Should we also validate it in the scheduler, or is it unlikely to be called stand-alone?

**Comment by berland** [comment]
NUM_CPU is not the responsibility of the Scheduler, it should be encoded into the built Realization objects, which the drivers should pick information from: https://github.com/equinor/ert/issues/8087

**Comment by oyvindeide** [comment]
> NUM_CPU is not the responsibility of the Scheduler, it should be encoded into the built Realization objects, which the drivers should pick information from: #8087

My comment was related to MAX_SUBMIT, which could be 0, which is the responsibility of the scheduler?

**Comment by xjules** [comment]
> Should we also validate it in the scheduler, or is it unlikely to be called stand-alone?

Hm, do you mean like to raise `ValueError` when the scheduler starts?

**Comment by berland** [comment]
> My comment was related to MAX_SUBMIT, which could be 0, which is the responsibility of the scheduler?

Ah! It might make sense for the scheduler to allow max_submit == 0, it serves as a "dry-run" feature (even proven to work in the wild!). But it should throw a ValueError if it is negative.

**Review by berland — APPROVED** [review]
:+1:

**Pull request merged**
