### PR TITLE
Fix environment test

### PR DESCRIPTION
**Pull request by BjarneHerland**

### CODE REVIEW

**Comment by BjarneHerland** [comment]
Umm...  sorry! Included WIP for something else. Will resubmit asap...

**Comment by sregales-TNO** [comment]
Test this please

**Comment by oyvindeide** [comment]
Jenkins: test this please

**Review by oyvindeide — COMMENTED** [review]
Rebase and squash and it looks good :+1:

**Comment by oyvindeide** [comment]
Meant squash down to one commit, we use rebase when merging.

**Comment by oyvindeide** [comment]
@BjarneHerland can you rebase on main and squash down to one commit?

**Review by oyvindeide — APPROVED** [review]
LGTM! Thanks for for improving the test running.

**Pull request merged**
