### PR TITLE
Add and use ert3.workspace.export_json function

### LINKED ISSUE #2279: Make export functionality unaware of the workspace structure
Relevant code:

https://github.com/equinor/ert/blob/bb16b5393df4593dd0eee7604fefbfd484b5129a/ert3/engine/_export.py#L88-L91

https://github.com/equinor/ert/blob/bb16b5393df4593dd0eee7604fefbfd484b5129a/ert3/engine/_sensitivity.py#L46-L50

### PR DESCRIPTION
**Pull request by verveerpj**
**Issue**
Resolves #2279

**Approach**
Replace explicit creation of export files by a new `export_json` function that lives in the `workspace `module.

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Review by sondreso — APPROVED** [review]
LGTM!

**Comment by sondreso** [comment]
Jenkins test this please!

**Comment by verveerpj** [comment]
Jenkins, test this please

**Pull request merged**
