### PR TITLE
Avoid erroneous developer commits to main branch

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves developers forgetting to checkout a new branch before commiting.

**Approach**
`pre-commit`

Example of classical developer error that is guarded by this commit:
```
HAVB@AC-Y72WJR4W4M:~/projects/ert] main$ git commit -am "Avoid erroneous developer commits to main branch"
don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
check json...........................................(no files to check)Skipped
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
ruff.................................................(no files to check)Skipped
ruff-format..........................................(no files to check)Skipped
clang-format.........................................(no files to check)Skipped
cmake-format.........................................(no files to check)Skipped
cmake-lint...........................................(no files to check)Skipped
```

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by xjules** [comment]
Don't understand this tbh. What's the issue - is it to avoid `force-push`?

**Comment by berland** [comment]
We should never commit to our local `main`, we should only ever do `git commit` when another branch is checked out. 

When we commit to local `main` branch, we need to clean up with `git reset --hard origin main.` 

This PR will make `git commit` fail unless you have checked out another branch than `main`

**Review by jonathan-eq — CHANGES_REQUESTED** [review]
Can we change the commit message to something like `Have pre-commit protect main branch`?

**Comment by berland** [comment]
> Can we change the commit message to something like `Have pre-commit protect main branch`?

Fixed!

**Review by jonathan-eq — APPROVED** [review]
Very good!

**Pull request merged**
