### PR TITLE
Reduce use of `type: ignore`

### PR DESCRIPTION
**Pull request by pinkwah**
This is just the low-hanging fruit. I left the record mess alone for now. Reduced usage from 30-something to 6.

### CODE REVIEW

**Comment by sregales-TNO** [comment]
please look to #2642

**Comment by sondreso** [comment]
This PR needs a rebase, but otherwise it looks good to me. Update and I will approve it!

**Comment by oyvindeide** [comment]
Can you rebase this and merge? @pinkwah

**Comment by pinkwah** [comment]
Closing due to incompatibility between what I did to hack around lack of `numpy.typing` in Python 3.6 and recent versions of mypy. We should consider doing something similar when we drop 3.6.

**Pull request closed without merging**
