### PR TITLE
Increase responsiveness of run dialog under heavy load

### PR DESCRIPTION
**Pull request by JHolba**
The pydantic version is causing our GUI to freeze for several seconds on heavy updates. 

**Approach**
Using TypedDict eliminates most of the freeze duration.

- [x] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Comment by JHolba** [comment]
> Very good, but I think this would benefit from using TypedDict rather than plain dict.
Changed to TypedDict

**Comment by berland** [comment]
Looks good, but needs conflict resolution.

**Comment by JHolba** [comment]
> Looks good, but needs conflict resolution.

All conflicts have de-escalated

**Review by berland — APPROVED** [review]
lgtm!

**Pull request merged**
