### PR TITLE
Some housekeeping in the analysis code

### PR DESCRIPTION
**Pull request by joakim-hove**
1. The module `std_enkf_debug.c` is changed to C++ and moved to common directory of analysis modules. Might be natural to kill off completely? But for now I suggest to keep it - debugging and testing is all the rage these days?
2. The `ies` module is moved from `analysis/modules` to `analysis/ies`

### CODE REVIEW

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by oyvindeide** [comment]
> 1. The module `std_enkf_debug.c` is changed to C++ and moved to common directory of analysis modules. Might be natural to kill off completely? But for now I suggest to keep it - debugging and testing is all the rage these days?

We were thinking to kill it off completely here: https://github.com/equinor/ert/pull/2399 We are all for testing and debugging, but were originally going to do that directly on module, however if there are good reasons to keep it, we can do that. 

>     2. The `ies` module is moved from `analysis/modules` to `analysis/ies`

No problem with that 👍

**Comment by joakim-hove** [comment]
> however if there are good reasons to keep it, we can do that.

I don't have a clear plan for how the `std_enkf_debug` can/should be used in the future, so if you already plan to remove it completely I support that. Will remove the two relevant commits from this PR.

**Comment by sondreso** [comment]
Jenkins ok to test

**Comment by joakim-hove** [comment]
The failing test is opaque to me - would be good if someone could post an error message of some kind.

**Comment by oyvindeide** [comment]
Will check, one sec

**Comment by oyvindeide** [comment]
It is not related to your PR, we seem to be having some issues with github at the moment:
`ERROR: Maximum checkout retry attempts reached, aborting`, so basically, we will try again in a while 🤷‍♂️

**Comment by joakim-hove** [comment]
> It is not related to your PR, we seem to be having some issues with github at the moment: [...]

Thank you!

**Comment by oyvindeide** [comment]
jenkins: test ert please

**Comment by joakim-hove** [comment]
Hmm - why is not the ci running?

**Comment by sondreso** [comment]
Jenkins add to whitelist

**Comment by sondreso** [comment]
That :arrow_up: gives you access to run this and future PRs on Jenkins. You have also now been given write access to this repo (pending accept of invitation), which allows you to run the Github Actions workflows from your fork :slightly_smiling_face:

**Comment by sondreso** [comment]
Or on closer inspection you should already have access to run from you fork, could you try rebasing and force push? :thinking:

**Comment by joakim-hove** [comment]
> Jenkins add to whitelist

Thank you :smile:

> you should already have access to run from you fork, could you try rebasing and force push?

I have just done that - let us see what happens.

**Comment by sondreso** [comment]
I see that it runs now, might have been related to this that it was not triggering: https://www.githubstatus.com/incidents/98jx6ncp3s4z

**Comment by joakim-hove** [comment]
Can this be merged?

**Comment by joakim-hove** [comment]
Sorry to repeat myself:

> The failing test is opaque to me - would be good if someone could post an error message of some kind.

**Comment by oyvindeide** [comment]
You probably came in the middle of a rebuild of `bleeding`, lets just try a restart of the tests, jenkins: test this please

**Comment by joakim-hove** [comment]
test this please

**Comment by joakim-hove** [comment]
test this please

**Review by oyvindeide — APPROVED** [review]
LGTM!

**Pull request merged**
