### PR TITLE
Add migrations for simulation arguments

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #my_issue

**Approach**
_Short description of the approach_

(Screenshot of new behavior in GUI if applicable)

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Added appropriate release note label
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [ ] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

**Review by oyvindeide — COMMENTED** [review]
Looks good, but should also bump the storage version to v5 as some v4 storages wont have simulation arguments?

**Comment by frode-aarstad** [comment]
If we bump local storage to 5 what else needs to be changed?

**Comment by oyvindeide** [comment]
> If we bump local storage to 5 what else needs to be changed?

Need to add another level to the migrations, but that should be it.

**Comment by frode-aarstad** [comment]
> > If we bump local storage to 5 what else needs to be changed?
> 
> Need to add another level to the migrations, but that should be it.

How do I determine what needs to be migrated in this new level?

**Comment by frode-aarstad** [comment]
Not relevant any more

**Pull request closed without merging**
