### PR TITLE
Ignore expected exception from file-parsing in c++ in torque driver

### PR DESCRIPTION
**Pull request by berland**
**Issue**
Resolves spamming the terminal with:
```
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-429759, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-780383, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-558744, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-237647, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-361596, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-92518, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-866519, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-212679, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-943649, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-1849, is it empty?
** Warning: Failed to parse file /tmp/ert-qstat-std-12678-99291, is it empty?
```

when running ert on Azure.

Bonus fix: Skip deleting a tmp-file if there is an error to be debugged.

**Approach**
Ignore the expected exception at end-of-file.

## Pre review checklist

- [ ] Added appropriate release note label
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

Adding labels helps the maintainers when writing release notes. This is the [list of release note labels](https://github.com/equinor/ert/labels?q=release-notes).

### CODE REVIEW

**Comment by berland** [comment]
This will need a back-port to 4.1 as PR#xx that introduced this bug was back-ported.

**Comment by berland** [comment]
Reviewer: One or two commits?

**Comment by hnformentin** [comment]
So basically the error message was because art was trying to parse an empty file, right?
Nice PR and I think it is fair to keep both commits.

**Comment by hnformentin** [comment]
Missing release-notes labels.

**Comment by berland** [comment]
> So basically the error message was because art was trying to parse an empty file, right? Nice PR and I think it is fair to keep both commits.

That was the intention of the error message, but it was triggered on every file, even if it was not empty..

**Review by hnformentin — APPROVED** [review]
LGTM!

**Pull request merged**
