### PR TITLE
Use plain qstat by default

### PR DESCRIPTION
**Pull request by berland**
The proxy script is deploy-specific and should not be the default in the driver.

**Issue**
Resolves future bug

**Approach**
Move the qstat_proxy configuration to ert-configurations. 

(Screenshot of new behavior in GUI if applicable)

## Pre review checklist

- [x] Read through the code changes carefully after finishing work
- [ ] Make sure tests pass locally (after every commit!)
- [x] Prepare changes in small commits for more convenient review (optional)
- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [ ] Updated documentation
- [ ] Ensured that unit tests are added for all new behavior (See 
    [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)),
    and changes to existing code have good test coverage.

## Pre merge checklist
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by berland** [comment]
Relates to https://github.com/equinor/ert-configurations/pull/79

**Review by jonathan-eq — APPROVED** [review]
LGTM, but I dont understand why the proxy script would be deploy specific? Wouldnt we use the proxy on every instance of TORQUE to avoid dos-ing the server?

**Comment by berland** [comment]
> LGTM, but I dont understand why the proxy script would be deploy specific? Wouldnt we use the proxy on every instance of TORQUE to avoid dos-ing the server? EDIT: Is this only Equinor Azure specific?

I think the reason the Equinor Torque cluster is ddos-able is due to some DNS dependency (which is also flaky) when it is processing the qstat request. 

As an example, a Torque interface to a slurm cluster set up ad-hoc on a single multi-core computer should have no problem processing the qstat requests.

**Comment by berland** [comment]
That said, we will however build something similar to the qstat proxy into a new queue code, maybe that is a reason to keep it.

**Comment by berland** [comment]
Lets keep it in for now.

**Pull request closed without merging**
