### PR TITLE
Auto-generate documentation for ert3 plugins

### LINKED ISSUE #3133: Create automatically generated documentation for transformation plugins

### PR DESCRIPTION
**Pull request by sondreso**
**Issue**
Resolves #3133

**Approach**
Inject the plugin fields when generating documentation for configurations.
Add separate section with auto-generated documentation for each plugin category.

## Pre review checklist

- [x] Added appropriate labels

Adding labels helps the maintainers when writing release notes, see sections and the
corresponding labels here: https://github.com/equinor/ert/blob/main/.github/release.yml

### CODE REVIEW

**Comment by jondequinor** [comment]
This is really good. Checks all the boxes. Is there anything missing?

**Comment by sondreso** [comment]
No, should be ready for review now! The only thing I am not super happy about is the reference to the plugin section in the different configs:
image

But due to a lot limitations, and not wanting to go to deep into the pydantic implementation/make to big of a hack, I think this is OK :slightly_smiling_face:

**Review by jondequinor — APPROVED** [review]
Golden 🥇

**Comment by sondreso** [comment]
Jenkins test this please

**Comment by sondreso** [comment]
Forgot to fix the history....

**Pull request merged**
