### PR TITLE
Run test in tmpdir

### PR DESCRIPTION
**Pull request by oyvindeide**
Test needs to run in tmdir to avoid polluting test folder.

### CODE REVIEW

**Review by markusdregi — COMMENTED** [review]
The changes looks good, but which files is it that the evaluator does create?

**Comment by oyvindeide** [comment]
I get `dask-worker-space` in my tests folder, does it not occur for you?

**Comment by markusdregi** [comment]
Oh, I do. But users will not in general be happy with `ert` starting to produce files in the `CONFIG_PATH`. Could you report this as a potential issue or at least discussion point for the owls?

**Review by markusdregi — APPROVED** [review]
LGTM 👍

**Comment by sondreso** [comment]
We are aware of this side-effect :slightly_smiling_face:

**Comment by markusdregi** [comment]
Then it is all good 🚀 Thanks for the update @sondreso

**Pull request merged**
