### PR TITLE
Add storage url to env

### LINKED ISSUE #2273: ERT should provide connection string through an environment variable
Something like `ERT_STORAGE_CONNECTION_STRING`

### PR DESCRIPTION
**Pull request by frode-aarstad**
**Issue**
Resolves #2273

### CODE REVIEW

**Comment by frode-aarstad** [comment]
Test this please

**Comment by frode-aarstad** [comment]
Test ert please

**Comment by frode-aarstad** [comment]
Test ert please

**Review by oysteoh — APPROVED** [review]
Looks good! 🚀

**Comment by oysteoh** [comment]
Please remember to squash and make a proper commit message 👍

**Comment by oysteoh** [comment]
Jenkins: Test this please!

**Pull request merged**
